### ISSUE TITLE
Lint errors underline

### ISSUE THREAD

**Issue by marselmustafin** [python-mode/python-mode#1000]
Is it possible to underline specific lint errors, except of add signs at the left of editor? I use `terryma/vim-multiple-cursors` plugin, and linti signs begin to blink on each multilne symbol entering. This is gonna get pretty ugly.

**Comment by diraol** [comment]
Hi @marselmustafin, I don't know any way of doing it.

I mean, as far as I know python-mode does not provide a way of changing how the signs are presented, which means that, in order to do that, you may need to hack it.
