### ISSUE TITLE
Syntax error while processing lint.vim

### ISSUE THREAD

**Issue by biycyr** [python-mode/python-mode#1001]
Hello, this problem seems to have been posted in several issues, but I haven't find the right answer to solve mine. The error messages keep popping up every time I want to create or edit any python files.

### Here is the debug log
[pymode_debug_file.txt](https://github.com/python-mode/python-mode/files/2940631/pymode_debug_file.txt)

### vim version
[vim_version.txt](https://github.com/python-mode/python-mode/files/2940632/vim_version.txt)

### Python version
`sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
`

### Python mode branch
**develop**

According to previous issues, this may have something to do with the python version, so i added `let g:pymode_python = 'python'` to my .vimrc, but it does not work. 

BTW, I installed python-mode with Vundle. Would that be a problem?

Thanks

**Comment by diraol** [comment]
Hi @biycyr sorry for taking so long to answer.

Vundle is not a problem usually, but can you certify that the submodules have been cloned correctly, please?

**Comment by biycyr** [comment]
Hi @diraol thanks for replying.

I am not quite sure how I am supposed to do that. But I have run `git submodule update --init --recursive` in `~/.vim/bundle/python-mode`, as in #901 .

Also, Here is my .gitmodules(I have changed the file name so that it can be uploaded) if you need it.
[gitmodules.txt](https://github.com/python-mode/python-mode/files/2982087/gitmodules.txt)

my output of running `git config -l` in all submodule directories:
[config.txt](https://github.com/python-mode/python-mode/files/2982206/config.txt)

and my output of `git lg`:
[git_log.txt](https://github.com/python-mode/python-mode/files/2982218/git_log.txt)



Thanks again!
