### ISSUE TITLE
the file has no mark

### ISSUE THREAD

**Issue by smilesun** [python-mode/python-mode#1002]
I have set the following
```
Enable functionality                                      *'g:pymode_breakpoint'*
>
    let g:pymode_breakpoint = 1

Bind keys
>
    let g:pymode_breakpoint_bind = '<leader>b'
```
when I open a python file and execute leader+b, i got "the file has no mark"

i am using neovim. 
Is there something i forget to do?

**Comment by diraol** [comment]
That's weird, I've tested it both in my system and in a clean docker environment and everything seems to be working fine.

It may be something with neovim (I've tested with vim only).

Anyone else that may have tested it with neovim?
