### ISSUE TITLE
b:pymode_modified does not exist (plugin conflict)

### ISSUE THREAD

**Issue by glentner** [python-mode/python-mode#1006]
I've been using python-mode for a long time and rarely had issues. However, I've lately had this issue where it complains about "b:pymode_modified" not existing. I've run all the debugging steps suggested and even dug into the plugin code myself. I looks as though `python-mode` is fine.

I systematically disabled all my other plugins and re-enabled them one at a time. It appears that `Xuyuanp/nerdtree-git-plugin` is causing the error. I'm not sure how yet, but I can reliably reproduce the error by toggling this other plugin on and off.

I'm posting the issue here because I thought others using this plugin might be interested. 

Maybe there is a collision in the buffer pre/post write hooks?

**Comment by diraol** [comment]
Hi @glentner I'm not sure if the "plugin order" matters, but can you try changing the order in which you load both plugins?

**Comment by glentner** [comment]
I'll give that a try and report back.

**Comment by PegasusWang** [comment]
Same problem.  conflict with https://github.com/Xuyuanp/nerdtree-git-plugin

**Comment by nineKnight** [comment]
It happens to me when nerdtree is toggled.
Add this into your .vimrc and it may help:
```
let NERDTreeIgnore=['\.pyc', '\~$']
```
But the root solution is about b:pymode_modified. I try changing it to t:pymode_modified and it seems to be fixed. @diraol

**Comment by unicell** [comment]
Hit the same thing with `nerdtree-git-plugin` installed. Confirmed the issue went away after updating `NERDTreeIgnore`

**Comment by unicell** [comment]
Adding `let NERDTreeIgnore=['\.pyc', '\~$']` does not fix the issue my side, but turning off `nerdtree-git-plugin` does make it go away.

**Comment by glentner** [comment]
I think the issue has been resolved, I'm no longer having this problem when using the latest version of each.
