### ISSUE TITLE
python-mode automatically installs with python 3 even when python 2 is default

### ISSUE THREAD

**Issue by alpha0mega96** [python-mode/python-mode#1008]
I installed python-mode via vim-plug.

It automatically installed itself in python 3 mode. I am working on python 2 (2.7) and hence all libraries that have been renamed in python 3 (3.5) are now marked as errors.

**Comment by diraol** [comment]
`python-mode` defaults to python3, if it exists in the environment.

If you want to use python2 you can set it at your `.vimrc` with:

`let g:pymode_python = 'python'`
