### ISSUE TITLE
Do not open extra quickfix window in new split

### ISSUE THREAD

**Issue by dbankmann** [python-mode/python-mode#1010]
Hi, 
I recently installed the `python-mode` plugin, so I may not be aware of all possible options yet.
I currently experience the following problem.
I opened two files belonging to the same project in a split window. However, after changing the top file and saving, the quickfix window appears also below the top window.
So in total, there are now 2 quickfix windows, one for the top file and one for the bottom file, which of course, consumes a lot of space.
It would be much more preferable to only have one quickfix window opened with the information of the currently active buffer.

These are the options I currently use:

	let g:pymode = 1
	let g:pymode_python = 'python3'
	let g:pymode_indent = 1

	let g:pymode_lint = 1
	let g:pymode_lint_on_write = 1
	let g:pymode_lint_on_fly = 1
	let g:pymode_lint_message = 1
	let g:pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
	let g:pymode_lint_cwindow = 1
    	let g:pymode_lint_signs = 1

	let g:pymode_lint_todo_symbol = 'WW'
    	let g:pymode_lint_comment_symbol = 'CC'
    	let g:pymode_lint_visual_symbol = 'RR'
    	let g:pymode_lint_error_symbol = 'EE'
    	let g:pymode_lint_info_symbol = 'II'
    	let g:pymode_lint_pyflakes_symbol = 'FF'
    	let g:pymode_options_max_line_length = 99
    	let g:pymode_lint_options_pep8 =
       		 \ {'max_line_length': g:pymode_options_max_line_length}
	
	let g:pymode_rope = 1
	set completeopt=menuone,noinsert
    	let g:pymode_rope_completion = 1
    	let g:pymode_rope_complete_on_dot = 1

**Comment by KamranMaharov** [comment]
I have tried reproduce this unwanted behavior, but couldn't. Quickfix window always opened at the current buffer.
How did i do:
Opened extra buffer with both :split and pymode's "gotodefinition" features, and then saved the file.

It may have something to do with pymode parameters. Here's my vimrc:
```
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'python-mode/python-mode', { 'branch': 'develop' }
call plug#end()

let g:pymode = 1
"let g:pymode_paths = []
let g:pymode_options_max_line_length = 99
let g:pymode_python = 'python' "could be python3 or disable

let g:pymode_rope = 1
set completeopt=menuone,noinsert
let g:pymode_rope_completion = 1
let g:pymode_rope_complete_on_dot = 1

let g:pymode_virtualenv = 0 "1
let g:pymode_rope_goto_definition_cmd = 'vnew'
"don't remove whitespaces for the sake of PR
let g:pymode_trim_whitespaces = 0
```

By the way, thank you for `set completeopt=menuone,noinsert` line, i was looking for it. ))

**Comment by diraol** [comment]
Hi guys, sorry for not answering, I've really been without time to dedicate to the project. =(

@dbacc I totally agree with you. I have already complained (to myself) about it many times, but never opened an issue about it.

As I've said, I'm without time to try to improve `python-mode` (not even some minor fixes and updates I've been able to do).

So, any kind of contribution here would be very welcome!

Btw, with `quickfix` you mean the panel that contains the linter results/evaluations right?

@KamranMaharov try doing the following:

1. Open a python file (`a.py`): `vim a.py`
1. Split the window with other python file: `:split b.py`
1. Run `PymodeLint` in the current buffer: `:PymodeLint`
1. Move to the other buffer: `<ctrl>+w + <arrow>`
1. Run `PymodeLint` in the other buffer: `:PymodeLint`

This should give you something like the image below:
![vim](https://user-images.githubusercontent.com/192702/55075229-390a1780-5071-11e9-9985-f692114c9dae.jpg)

Or, even worst, if you do:

1. Open a python file (`a.py`): `vim a.py`
1. Run `PymodeLint` in the current buffer: `:PymodeLint`
1. Split the window with other python file: `:split b.py`
1. Run `PymodeLint` in the other buffer: `:PymodeLint`
1. Move to the other buffer: `<ctrl>+w + <arrow>`
1. Run `PymodeLint` in the other buffer: `:PymodeLint`

You will get something like:
![vim2](https://user-images.githubusercontent.com/192702/55075341-8090a380-5071-11e9-9874-1b5e016dbae8.jpg)

**Comment by dbankmann** [comment]
@diraol Yes, exactly!

It seems like the whole 'problem' ist that linting information is printed to location lists instead into the quickfix window. Is there a special reason for this?

**Comment by diraol** [comment]
Hum..... no idea if there is a special reason for that.

I think we can try to change the behavior and see if any kind of problem arises.

Can you give it a try?

**Comment by dbankmann** [comment]
Well, for example in `loclist.vim` one could replace `lopen` by something like

```
	windo if  &buftype == "locationlist" | lclose | endif
        botright lopen
```
