### ISSUE TITLE
How to integrate Django help, and autocompletion into vim?

### ISSUE THREAD

**Issue by Migacz85** [python-mode/python-mode#1011]
Hi
I know that this is loosely corelated with pymode. Which is great tool. But I started recently coding in python using Django. Pymode have shortuct `shift+K`. Is there any way that I can integrate help system to the Django framework so I will be able to read what Django specific functions can do in Vim? 

Also I'm interested it its possible to make an autocompletion - but to Django specific functions. 

Any suggestions, tips tricks that can help with vim and Django  are really welcome.

**Comment by diraol** [comment]
Hi @Migacz85 

Not sure about `shift+K`, but if you have django installed into the python environment that vim is reading from (probably your current python env in the shell session), then the autocomplete will work nicely. =)

**Comment by Migacz85** [comment]
Hi
@diraol 
I see tha we have `PymodeVirtualenv` option, but when I'm running is saying that it needs argument.
I was trying to path to my virtual environment but without success.
Normally I'm activating virtual env by 	`source venv/bin/activate` 
I also put to my `.vimrc` code for autodetection but I'm not sure it is working. How I can check that I'm in venv?

**Comment by Migacz85** [comment]
I tested this entering manually to venv, I have something like this:
Is really sluggish, slow, and it looks like its importing everything. Hmmm any idea how to scan for only Djangoish classes? In insert mode when I'm typing I press `ctrl + p`

![pymode venv](https://user-images.githubusercontent.com/25789997/54878484-a3c71300-4e25-11e9-838f-f3afa83c5091.gif)
