### ISSUE TITLE
Travis CI tests Failing

### ISSUE THREAD

**Issue by diraol** [python-mode/python-mode#1019]
Not sure why, but it seems that something has changed in Travis CI and because of that our tests are failing.

We need to fix it.

It can be a nice opportunity to improve our test environment with a dockerized version (https://github.com/python-mode/python-mode/issues/977). This way we will be more agnostic to travis or other ci envs and also will be able to better test `python-mode` locally.

Thoughts about it? Anyone willing to help (It's been hard for me to find time to work on `python-mode`).

P.s.: https://changelog.travis-ci.com/upcoming-python-default-version-update-96873

**Comment by KamranMaharov** [comment]
It looks like this one has been failing:
https://github.com/python-mode/python-mode/blob/develop/tests/test_bash/test_folding.sh#L11

On my local environment `bash -x test.sh` passes all the test cases, but i use old version of vim.
```VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 17 2018 14:12:39)```
```Included patches: 1-72```

But, when launched from travis ci, it is failing.
Maybe it's related to vim version? What do you think?
It seems travis always uses latest, up-to-date vim.
https://travis-ci.org/python-mode/python-mode/builds/513822410#L2462

**Comment by diraol** [comment]
Yeah, I couldn't figure out the reason why the tests are failing.

And I haven't had time to look at what is going on also.

Any help is very welcome! (And I really think that moving to a dockerized version would benefit us!).

So, #977 can be a way to overcome this issue with Travis.

In #977 I've tested with vim compiled from the sources, so maybe even more recent than the one used by Travis.

**Comment by KamranMaharov** [comment]
Regenerated failure.
1)Updated vim to the latest version using`brew upgrade vim` (Mac OS X).
2)`cd python-mode/tests`
3)`bash -x test.sh` (this generates `/tmp/pymode_vimrc` as a side effect)

After this,
`vim temp.py`, then `echo &shiftwidth` gives 4. (which is expected).
But, `vim -u /tmp/pymode_vimrc temp.py`, then `echo &shiftwidth` gives 8. (this is something new which is happening after vim upgrade, it was yielding 4 before).

In that particular failing test case, this &shiftwidth vim variable is being used here:
https://github.com/python-mode/python-mode/blob/develop/autoload/pymode/folding.vim#L70
Which is the reason why test case fails.


It seems
https://github.com/python-mode/python-mode/blob/develop/after/indent/python.vim#L8
this line is not being hit in Travis environment, even though plugin is being added to runtimepath in `/tmp/pymode_vimrc`.


`grep "runtimepath" /tmp/pymode_vimrc`:
`set runtimepath+=/Users/kamranmaharov/.vim/plugged/python-mode`

**Comment by KamranMaharov** [comment]
@diraol , issue was related to new plugin layout which is coming with new vim version.
https://vimhelp.org/repeat.txt.html#%3Apackloadall

i'm not an expert in ci systems and maybe not the best solution to this, but created PR to address this ci failure.
https://github.com/python-mode/python-mode/pull/1024
please let me know if it works for you.
