### ISSUE TITLE
Syntax highlighting for matrix multiplication operator?

### ISSUE THREAD

**Issue by larrybradley** [python-mode/python-mode#1021]
Python 3.5 introduced a new matrix multiplication operator (`@` and `@=`; https://www.python.org/dev/peps/pep-0465/).  Currently the `@` symbol is always highlighted as a decorator.  It would be great if the matrix multiplication operator could be highlighted the same way as other python operators.  It could be tricky in some line-continuation cases where the second line looks like a decorator:

```python
(array1
 @ array2)

(array1
 @array2)
```
Thanks.

**Comment by diraol** [comment]
Hum... indeed this is a very tricky one.

I do agree that we should look for support for it, but I won't be able to put effort on it.

If you can give a try and propose a solution it would be very nice! =)

**Comment by qoheniac** [comment]
Same issue here: https://github.com/vim-python/python-syntax/issues/42

And here the implementation in the Vim repository:
https://github.com/vim/vim/blob/a87b72cc316e065d66dcbcf7ec1cde330adef3a3/runtime/syntax/python.vim#L111
