### ISSUE TITLE
pymode won't install

### ISSUE THREAD

**Issue by chivalry** [python-mode/python-mode#1022]
I realize I'm probably just missing a simple step somewhere, but I follow the instructions for installation by recursively cloning the repository into my plugins directory, where I've confirmed other plugins are located that work. But when I open vim, or MacVim, and execute `:help pymode`, I get an error: `E149: Sorry, no help for pymode`.

I `cd`ed into `~/.vim/plugins/start` and executed `git clone --recursive https://github.com/python-mode/python-mode.git` (copy and pasted from your instructions. I then quit MacVim and relaunched it with the above described results. I also tried Terminal's vim, same results.

As requested, Here's the [debugvimrc.vim](https://github.com/python-mode/python-mode/files/3109773/debugvimrc.vim.txt) (given a `.txt` extension to allow uploading).

**Comment by diraol** [comment]
Hi @chivalry sorry for taking so long to answer.

We may have a problem with our documentation. The right flag is not `--recursive`.

Take a look at: https://github.com/python-mode/python-mode/pull/1013
