### ISSUE TITLE
Have pymode read a project's setup.cfg or other file that specify longer line lengths

### ISSUE THREAD

**Issue by chivalry** [python-mode/python-mode#1025]
I'm experimenting with pymode, and saw that it's using the default 79 character line lengths. I'm working in a project that has a `setup.cfg` file that sets flake8's max line length to 99, my own preference.

If there's any interest, I can edit the plugin to read any of the various configuration files used by flake8 and use that as the max line length. I just don't want to do it if it would be rejected as opposed here.

In the meantime, I'll set my vimrc to use the longer lines. I think project-specific overrides would be nice because I use 99 characters for private projects and 79 characters for various open source projects I contribute to.

**Comment by diraol** [comment]
Hi @chivalry, sorry for taking long to answer.
I haven't had time to dedicate myself to the project. But for sure contributions are more then welcome!

It would be very nice to be able to have local config files "per-project", not only for flake8 but also for other linters. =)

**Comment by chivalry** [comment]
I'll get on it, then. :) I'm rather a Python newbie, so I'm unfamiliar with other linters, but I'll work it in for flake8 and then research support for others.
