### ISSUE TITLE
goto define.

### ISSUE THREAD

**Issue by rideoff** [python-mode/python-mode#1026]
![图片](https://user-images.githubusercontent.com/8640579/57181079-d56dd800-6ec1-11e9-8190-f791f36f62c0.png)
![图片](https://user-images.githubusercontent.com/8640579/57181087-f20a1000-6ec1-11e9-9758-4134a0c3854b.png)
How to switch between two defined files?
Thank you

**Comment by diraol** [comment]
Hi @rideoff, I didin't understand your question. Would you please elaborate it a little bit more, please?

**Comment by rideoff** [comment]
49/5000  
Thank you for your answer. When jumping to the definition, you need to manually select the file to jump to. I would like to ask how to move the cursor up and down to select the file
