### ISSUE TITLE
Error in pymode#buffer_post_write

### ISSUE THREAD

**Issue by Migacz85** [python-mode/python-mode#1027]
Not quite sure what is causing this error. I messed up something or this is an bug?
It occurs in rare situation when writing a file.

![image](https://user-images.githubusercontent.com/25789997/57200376-25f93a00-6f83-11e9-9e17-f5a635b648e6.png)

**Comment by diraol** [comment]
@Migacz85 can you try getting the latest version of python-mode and also removing all "temporary" files from python-mode path and subpaths? (take a look at our README, there is a oneliner with `find` to delete them.
