### ISSUE TITLE
2 Errors on any python file I open

### ISSUE THREAD

**Issue by rwideman** [python-mode/python-mode#1031]
Mac OS Mojave, latest brew/vim, vim 8.1.1450.  I am using vim-plug and I have validated that with python-mode removed I do NOT get these errors, with it installed I do. Using Python 3 and on any python file I open these errors show.

Errors:
Error detected while processing function pymode#breakpoint#init:
line   27:
/must>not&exist/foo:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by diraol** [comment]
Hi @rwideman you are probably using an old version of python-mode of you are using the wrong branch.

Please, take a look at our readme on how to install python-mode. There are also some tips about it over there from common problems.
Oh, and make sure you are using the `develop` branch.

**Comment by rwideman** [comment]
yes, this was it, my apologies
