### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by ncpnc** [python-mode/python-mode#1035]
I love python-mode.
I've been using it a lot last two years. Unfortunately it seems that project can't keep up up with the world with current contributors engagement. @klen apparently abandoned the project two years ago. #823 is open since dec 2017 and no one really made a serious effort to deal with it, although it made python-mode unusable (most of it cool features) with vim8. @diraol stated in may that he "haven't had time to dedicate himself to the project.".
Of course no one is blaming anyone for that, we all know how the open-source free projects like this works, and it all depends on work-life-hobby balance. Still, it seems that project is slowly dying. 
Is there a chance for improvement? Any future plans? I am unable to dedicate my personal time for the project at this moment of my life, although watching it dying is painful, because there's still no better alternative.
Either way, I'd like to thank all of the contributors. You made my job mych easier and additionaly python-mode proved to be best way to learn python according to its guidelines.

**Comment by diraol** [comment]
Hi @ncpnc,

I am myself a daily user of this extension, and I've become a kind of "maintainer" of it for this same reason.

As I've said, I haven't had time for the project, and that won't change. Actually I'll have less and less time in a few months (my child is expected to September).

I'd love to see a group maintaining `python-mode`. Is is a hard job for one single person, so a group of three or four would fit perfectly. That wouldn't require tons of hours of dedication.

Really, IMHO the best perspective to the project is to have its users helping maintaining it.

We do have some users helping a bit with it, like @zcodes and @cdleong. @fmv1992 did a great job too.

So, I'm absolutely open to suggestions.

I've tried myself to think in the project development/future by creating some issues, documenting it and pinning them.

One last thing. Reviews on the current Pull Requests are also welcome. ;)
Thanks @ncpnc for you interest in the project!
