### ISSUE TITLE
ModuleNotFoundError: No module named 'pymode.libs.six'

### ISSUE THREAD

**Issue by ljl3937** [python-mode/python-mode#1040]
I'm using a Mac here,when I opened the .py file with vim, the error was as follows:

```
Error detected while processing function pymode#breakpoint#init[29]..provider#python3#Ca
ll:
line   18:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'pymode.libs.six'
Press ENTER or type command to continue
```

But I didn't find this class library.

**Comment by fmv1992** [comment]
I had the same problem. I will submit the solution soon.

**Comment by diraol** [comment]
You are probably missing the step to clone the submodules. Please, look at
the Readme's FAQ and install sections.

**Comment by ljl3937** [comment]
> You are probably missing the step to clone the submodules. Please, look at the Readme's FAQ and install sections.

I installed it in vim-plug mode, so there is no cloning. So far, there is no problem with the cloning installation.

**Comment by fmv1992** [comment]
I was having this problem; 7fbf9eb0a18c093f841a1e5afe2f57a6df2e6337 can't harm.

**Comment by ljl3937** [comment]
@fmv1992 Thank you very much!
