### ISSUE TITLE
Visual selection has to go one character past

### ISSUE THREAD

**Issue by kevinkjt2000** [python-mode/python-mode#1042]
Say I have the following file:
```python
def eggs():
    bacon = ["spam"]
```
and I want to refactor that file to be:
```python
def eggs():
    spam = "spam"
    bacon = [spam]
```
For a long while I struggled through what I thought was a reproduction of https://github.com/Microsoft/vscode-python/issues/1568, but it turns out that it may have been a user error based on my visual selection.

I selected `"spam"` by placing my cursor in the middle of the word, pressing `va"` from command mode, and then I invoked pymode_rope_extract_variable_bind by pressing `<C-c>rl`. This however leads to the same rope error message as that vscode-python issue `[Pymode]: error: Extracted piece should contain complete statements`.

An idea hit me, so I tried going one past with my selection. I selected `"spam"]` (including a character that I don't want to refactor), and to my surprise this worked and only extracted what I wanted, leaving the `]` where it was.

Is going one past an intentional design decision?  This feels strange to me compared to when I do any other visual operations in vim that operate on exactly what is selected.

**Comment by kevinkjt2000** [comment]
Versions:
python-mode 7fbf9eb0a18c093f841a1e5afe2f57a6df2e6337
rope 0.14.0
nvim 0.4.2

Relevant configuration:
```
" Some python ropeproject settings
let g:pymode_rope = 1
let g:pymode_rope_goto_definition_cmd = 'e'

" Disable pymode linting, since ALE handles that
let g:pymode_lint = 0
```

**Comment by avacariu** [comment]
This seems like it should've been fixed by this commit: https://github.com/python-mode/python-mode/commit/4d12b1599f2c0ef5a35619f790c0506faf8be034

FWIW, this works fine for me on Mac using Vim 8.1.2234. I notice in Rope's documentation [they say](https://github.com/python-rope/rope/blob/master/docs/library.rst#performing-refactorings):

> Where start and end are the offsets of the region to extract in resource. Be careful when calculating the offsets. DOS line-endings and multi-byte characters are considered to be one character.

However, I tried your example with both Unix and DOS line-endings and it works for me in both cases.

**Comment by kevinkjt2000** [comment]
I just realized that `master` is not the default branch for this project, and that several releases have come from `develop`. I'll switch branches and consume all these bugfixes and features that I have been missing out on!

**Comment by diraol** [comment]
> I just realized that `master` is not the default branch for this project, and that several releases have come from `develop`. I'll switch branches and consume all these bugfixes and features that I have been missing out on!

Yeah, that has been like this for a long time.

Since we have fixed a ton of issues and done many upgrades to python-mode, I'm planning to merge develop back to the master branch and keep both in sync to avoid this kind of issues for our users.

But nice that it is working :)
