### ISSUE TITLE
Vim pymode in windows

### ISSUE THREAD

**Issue by marcelosena** [python-mode/python-mode#1044]
I am trying to use pymode in Windows but I am having a hard time. I have managed to clone it into C:\Users[USER].vim\pack\python-mode\start\python-mode and vim seems to run normally in python 2 (this is what `:python import.sys; sys.version()` prints:

`2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]  `

But when I try using `:help pymode` it says nothing is founds. Moreover, one of the reasons I would like to use pymode is that I would like to switch vim to python 3.

Any help is appreciated, I am beginner with Vim (and I am using windows, which I have the impression is a not common choice for vim users).

Im using vim version 8.1.2231.

Thanks.

**Comment by diraol** [comment]
Hi @marcelosena, yeah, vim and windows together is not the most common set of tools. I don't even have a windows to test things here.

Regarding python-mode help not showing up, take a look at this section from our Readme:
https://github.com/python-mode/python-mode#symlinks-on-windows

Regarding python version, you should check:
 - which python version you have installed and in your Path
 - Which python version your vim was compiled with;
 - Which python version is the default on your OS.

One of these options may help you.
