### ISSUE TITLE
imp module is deprecated in favour of importlib

### ISSUE THREAD

**Issue by undertakingyou** [python-mode/python-mode#1045]
Error detected while processing function pymode#breakpoint#init:
line 27:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Seems that the breakpoint.vim file uses an import that throws a python depreciation error.

**Comment by undertakingyou** [comment]
I have created a PR of my fix that resolved the issue for me. https://github.com/python-mode/python-mode/pull/1046

Please note, I ran `:help pymode-development` as instructed in the readme, and and vim said that particular help doesn't exist. If there is something different that I should do on my branch, please let me know.

**Comment by diraol** [comment]
Hi @undertakingyou As I've commented in your PR, imp module was deprecated in recent python versions, but we still support older versions, thus I am not sure if we can really remove it. :(

But it shouldn't be a problem if you setup is correct, in terms of python version with which vim was built and the current running and configured versions.
