### ISSUE TITLE
lint.vim & python3.8.0 

### ISSUE THREAD

**Issue by YHYJ** [python-mode/python-mode#1048]
i use Arch Linux, just upgraded to python3.8.0, now `lind.vim` error occurred in python-mode, then i uninstalled python-pylint and the bug was fixed.

**Comment by diraol** [comment]
Hi @YHYJ yeah, we haven't made any updates in order to support python 3.8, we have plenty of not updated dependencies and other issues.
Would you mind taking a look at this comment that I think can help with this issue: 
https://github.com/python-mode/python-mode/issues/935#issuecomment-554782399

**Comment by diraol** [comment]
@YHYJ do you mind trying the branch from this Pull Request (https://github.com/python-mode/python-mode/pull/1058) to see if the newer version of our dependencies fix it for you?

**Comment by YHYJ** [comment]
Thank you! I installed flake8 and pylint, no matter what I set `pyflakes` or `pylint` to `g:pymode_lint_checkers
`, I get an error: 
```python
NameError: name 'code_check' is not defined
```

**Comment by Gako358** [comment]
any news on pymode regarding python 3.8?

**Comment by diraol** [comment]
Hey guys, sorry for the late reply.
We have just updated all submodules to their latest releases. So I guess it should be working fine with python 3.8.

Just remember that, depending how you have built your Vim eventually your Vim will be statically linked to other python versions.

**Comment by lucomsky** [comment]
@diraol, it looks like you have a bug in your commit 1e97e4d8fa427f7b3262b2daadff8d32ca5be536:
```
git submodule update --init --recursive
error: Server does not allow request for unadvertised object f436ccc6b55b33381a295ded753e467953cf4379
Fetched in submodule path 'submodules/pylama', but it did not contain f436ccc6b55b33381a295ded753e467953cf4379. Direct fetching of that commit failed.
```

**Comment by diraol** [comment]
Hi @lucomsky, that is weird.

I've just tested `git clone --recurse-submodules https://github.com/python-mode/python-mode.git` and it worked perfectly here.

Btw, if you got to pylama's repo you can see that the last commit is exactly this commit:

https://github.com/klen/pylama

I'd guess you have had a networking intermittent error?

**Comment by lucomsky** [comment]
I reinstalled the plugin. Error have gone.
