### ISSUE TITLE
Asteroid needs updating

### ISSUE THREAD

**Issue by vyasr** [python-mode/python-mode#1052]
The commit of `asteroid` that is currently pinned to causes problems for `pylama.lint`: 
```
AttributeError: 'TreeRebuilder3' object has no attribute 'visit_constant'
```
I was able to resolve the problem by simply checking out the master branch of the `asteroid` submodule, but I don't know if that is a feasible general solution or if it breaks compatibility. It sounds like moving on from python2 is part of the plan whenever the developers have time, so that may help ameliorate this issue. I'm happy to submit a PR updating the submodule, but I don't have access to very many different setups and architectures to be sure that my changes are sufficiently backwards-compatible, so let me know what makes sense.

I'm not sure if this is the problem with #1043 or #1048. Based on the long history of issues that mention some issue with `lint.py` (#750, #908, #959, #961, #844... etc) it seems like python-mode runs into various issues (particularly due to python2 compatibility), so those issues may be unrelated. On the other hand, #972 and the corresponding PR look like they were intended to address more general import problems that were related to those other issues, in which case the problem i'm reporting is probably separate.

I've attached the requested output file, which contains the full traceback (I replaced my home directory with `${HOME}`)
[pymode_debug_file.txt](https://github.com/python-mode/python-mode/files/3942346/pymode_debug_file.txt)

**Comment by diraol** [comment]
Hi @vyasr do you mind testing the follow pull request to check if the updates are not breaking everything, please?

https://github.com/python-mode/python-mode/pull/1058

Thanks!

**Comment by vyasr** [comment]
Can confirm that it works! At least on my current machine, which is Arch Linux. Nothing else is obviously broken by this change.

**Comment by zhyu** [comment]
I'm having the same issue. And I can confirm the pull request works on my machine, which is macOS.

**Comment by diraol** [comment]
Update merged! Also I've done another submodule update ;)

Feel free to reopen the issue in case the error persists.
