### ISSUE TITLE
This Vim cannot execute :py3 after using :python

### ISSUE THREAD

**Issue by matianhe3** [python-mode/python-mode#1053]
Error detected while processing function pymode#run#code_run:
line   10:
E837: This Vim cannot execute :py3 after using :python
E263: Sorry, this command is disabled, the Python library could not be loaded.

VIM version: 8.1
Python version: 3.7.5

**Comment by diraol** [comment]
@matianhe can you confirm that your vim was built with python3 support? (can you paste here the output of `vim --version | grep python`?)

**Comment by matianhe** [comment]
> @matianhe can you confirm that your vim was built with python3 support? (can you paste here the output of `vim --version | grep python`?)

![image](https://user-images.githubusercontent.com/24929062/70537633-bd6adf00-1b9b-11ea-8aac-06e4bc2b6e56.png)

**Comment by matianhe3** [comment]
![image](https://user-images.githubusercontent.com/24929062/70537633-bd6adf00-1b9b-11ea-8aac-06e4bc2b6e56.png) @diraol

**Comment by diraol** [comment]
@matianhe I remember reading that vim with both python and python3 support enabled is problematic. You probably should choose one of them.

Take a look at this: https://github.com/vim/vim/issues/3585

**Comment by diraol** [comment]
@matianhe did it work?

**Comment by matianhe3** [comment]
@diraol yes, It looks like work.

**Comment by noscripter** [comment]
I've run into the same issue, here is the solution, just prepend the following snippet to your `$MYVIMRC` file:

```viml
if has('python3')
endif
```

more details and the solution contribution can be found here: https://robertbasic.com/blog/force-python-version-in-vim/

Happy hacking with vim!
