### ISSUE TITLE
 from imp import find_module 

### ISSUE THREAD

**Issue by kerwinxu** [python-mode/python-mode#1062]
#from imp import find_module
from importlib.util import find_spec as find_module

**Comment by diraol** [comment]
? @kerwinxu

**Comment by McSinyx** [comment]
I think @kerwinxu is trying to report the deprecation of `imp`, which is already fixed on `develop` by #1051.

**Comment by diraol** [comment]
Yeap, probably.

I'll close this issue. If he wants to state something else he can feel free to reopen the issue ;)
