### ISSUE TITLE
Question: "[Pymode]: error: Pymode requires vim compiled with +python. Most of features will be disabled." Both +python and +python3 available though

### ISSUE THREAD

**Issue by al3xandru** [python-mode/python-mode#1064]
Following the instructions in the debug section, this is the error I'm seeing when trying to open a python file.  I've looked for similar issues but none seem to indicate towards a solution. I'm running latest Macvim with latest python-mode on macOS 10.14.6

```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
macOS version
Included patches: 1-2234  

 +python/dyn
+python3/dyn
```

What else should I check?  thank you

**Comment by diraol** [comment]
@al3xandru vim does not work properly with both python2 and 3 at the same time. This is a known issue - and we have faced it here some times.
I need to go AFK now but you may find some issues here in python-mode with a link to a vim issue about it.
The solution? Build vim with only python3 support.

**Comment by UlionTse** [comment]
Have any best answer?

**Comment by diraol** [comment]
Hi @UlionTse, as I've said, this is a limitation from vim, not from python-mode. So my best answer still is build vim with only python3 support.

**Comment by UlionTse** [comment]
@diraol Thanks. I upgraded my Mac from Mojave to Catalina  today, it becomes ok.

**Comment by AceofSpades5757** [comment]
Hi, I wanted to mention that after building and installing Vim on Windows, the following, similar issue occurred.

`[Pymode]: error: Pymode requires vim compiled with +python3 (exclusively). Most of features will be disabled.`

Listed from `:version`. _Dynamic Python 3 was tried as well._

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 21 2020 23:41:04)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-1883

-python
+python3
```

This was finally **solved** by adding `let g:pymode_python = 'python3'` to my `.vimrc`/`_vimrc` file.
_Note that the line has to come before `python-mode` is loaded._

Answer found on #884.

**Comment by elig0n** [comment]
I've managed to run Pymode with both python (2) and python3 compiled support.
I simply set the following three variable appropriately

set pythonthreehome="C:\\Python38\\"
let &pythonthreedll="C:\\Python38\\python38.dll"
let $PYTHONHOME="C:\\Python38\\"

and 
let g:pymode_python = 'python3'
