### ISSUE TITLE
mypy support

### ISSUE THREAD

**Issue by JackLeo** [python-mode/python-mode#1066]
PyLamas module that is mainly used for python-mode provides support for mypy, it would be great if it supports would be included in python-mode as well.

**Comment by diraol** [comment]
Hi @JackLeo I'd love that, but unfortunately I don't have time to implement it. I'm having difficulties even to find spare time to do maintenance ... (you can see it by the time it took to me to answer to your message!)

But I totally agree that this would be a nice addition and it would be wonderful to receive such contribution ;)
