### ISSUE TITLE
Vim: Caught deadly signal ABRT

### ISSUE THREAD

**Issue by DasHammett** [python-mode/python-mode#1067]
Hi, 

I am experiencing an total crash on VIM while using the plugin, freshly cloned as of today.

OS:
Gentoo Linux
Kernel 5.6.4

vim version:
`
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 17 2020 17:04:39)
Included patches: 1-114
Modified by Gentoo-8.2.0114
Compiled by hammett@Hammett
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   -toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
-cscope            +localmap          +rightleft         +wildignore
+cursorbind        -lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             -sound             +xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=znver2 -O2 -pipe -fomit-frame-pointer -fgraphite-identity -floop-nest-optimize -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: x86_64-pc-linux-gnu-gcc   -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl   -lacl -lattr -ldl     -L/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm`

Python version:
`Python 3.6.9`

I am unable to check which Python version python-mode loads as vim crashes

Please see below the last lines of vimlog.
`Executing: runtime! ftplugin/python.vim ftplugin/python_*.vim ftplugin/python/*.vim
Searching for "ftplugin/python.vim ftplugin/python_*.vim ftplugin/python/*.vim" in "/home/hammett/.vim,/home/hammett/.vim/bundle/Nvim-R,/home/hammett/.vim/bundle/doorboy.vim,/home/hammett/.vim/bundle/gruvbox,/home/hammett/.vim/bundle/python-mode,/home/hammett/.vim/bundle/stellarized,/home/hammett/.vim/bundle/vim-airline,/home/hammett/.vim/bundle/vim-airline-themes,/home/hammett/.vim/bundle/vim-easy-align,/home/hammett/.vim/bundle/vim-grammarous,/home/hammett/.vim/bundle/vim-multiple-cursors,/home/hammett/.vim/bundle/vim-repl,/home/hammett/.vim/bundle/vimtex,/usr/share/vim/vimfiles,/usr/share/vim/vim82,/usr/share/vim/vimfiles/after,/home/hammett/.vim/bundle/vimtex/after,/home/hammett/.vim/bundle/python-mode/after,/home/hammett/.vim/after"
Searching for "/home/hammett/.vim/ftplugin/python.vim"
Searching for "/home/hammett/.vim/ftplugin/python_*.vim"
Searching for "/home/hammett/.vim/ftplugin/python/*.vim"
Searching for "/home/hammett/.vim/bundle/Nvim-R/ftplugin/python.vim"
Searching for "/home/hammett/.vim/bundle/Nvim-R/ftplugin/python_*.vim"
Searching for "/home/hammett/.vim/bundle/Nvim-R/ftplugin/python/*.vim"
Searching for "/home/hammett/.vim/bundle/doorboy.vim/ftplugin/python.vim"
Searching for "/home/hammett/.vim/bundle/doorboy.vim/ftplugin/python_*.vim"
Searching for "/home/hammett/.vim/bundle/doorboy.vim/ftplugin/python/*.vim"
Searching for "/home/hammett/.vim/bundle/gruvbox/ftplugin/python.vim"
Searching for "/home/hammett/.vim/bundle/gruvbox/ftplugin/python_*.vim"
Searching for "/home/hammett/.vim/bundle/gruvbox/ftplugin/python/*.vim"
Searching for "/home/hammett/.vim/bundle/python-mode/ftplugin/python.vim"
Searching for "/home/hammett/.vim/bundle/python-mode/ftplugin/python_*.vim"
Searching for "/home/hammett/.vim/bundle/python-mode/ftplugin/python/*.vim"
chdir(/home/hammett/.vim/bundle/python-mode/ftplugin/python)
`
The vimlog has >1M rows, should you need more lines, let me know, of perhaps I can share the entire log with you.

It would seem `ftplugin/python.vim` needs to be executed, but it is not found in the ftplugin folder

**Comment by DasHammett** [comment]
Update:
I have downgraded vim to 8.1 and I no longer have a crash
`VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 18 2020 12:27:02)
Included patches: 1-1486
Modified by Gentoo-8.1.1486
Compiled by hammett@Hammett
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
+clientserver      +job               -perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
-cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       -lua               -ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       +xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              -mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=znver2 -O2 -pipe -fomit-frame-pointer -fgraphite-identity -floop-nest-optimize -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: x86_64-pc-linux-gnu-gcc   -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -ldl   
`

**Comment by diraol** [comment]
Hi @DasHammett I haven't tested vim 8.2 until now, but one thing I saw on your outputs is that you have vim with both python and python3.

Please, take a look at this comment: https://github.com/python-mode/python-mode/issues/1053#issuecomment-564069826
