### ISSUE TITLE
"let g:pymode_options_max_line_length" is ignored when set in .lvimrc

### ISSUE THREAD

**Issue by andymwood** [python-mode/python-mode#1068]
In ~/.vim/vimrc, I have:
```
let g:pymode_options_max_line_length = 90
```

I want to override this for a particular project. So I'm using [vim-localvimrc](https://github.com/embear/vim-localvimrc/tree/master), and in .lvimrc I have
```
let g:pymode_options_max_line_length = 119
```

The option appears to be set correctly - when I type `:echo g:pymode_...` it returns 119. But when I type `:PymodeLint` I get
```
views.py|37 col 91 C| E501 line too long (93 > 90 characters) [pep8]
```

**Comment by diraol** [comment]
Hi @andymwood,

Can you try setting up setup.cfg under your project's directory in order to setup pylint configs for this specific issue?

**Comment by andymwood** [comment]
I've figured out the problem. Adding the following to .lvimrc fixes it:
```
let g:pymode_lint_options_pylint = {'max-line-length': g:pymode_options_max_line_length}
```
