### ISSUE TITLE
3rd party modules? 

### ISSUE THREAD

**Issue by JohnSparham** [python-mode/python-mode#1069]
having an issue with :PythonRun, I'm new to python-mode and using macvim 

I get this error message for every 3rd party module I try to import, I'm using "requests" for this example 

> pyTest.py|6 error| in <module> import requests ModuleNotFoundError: No module named 'requests'

if I run the script with vim command  :!python3 <filename> it works fine.

with :PythonRun  print(sys.executable) ->/usr/local/Cellar/macvim/8.1-161/MacVim.app/Contents/MacOS/Vim

with :!python3 <filename> print(sys.executable) -> /Library/Frameworks/Python.framework/Versions/3.7/bin/python3

**Comment by diraol** [comment]
Hi @JohnSparham I don't recognize this command (`PythonRun`). It is not provided by python-mode as far as I know.
