### ISSUE TITLE
Mark shift Space as an error

### ISSUE THREAD

**Issue by AKielhorn** [python-mode/python-mode#1071]
I often enter a shift Space because I hold down the shift key too long.

I've added the shift Space as an Error in my configuration and would suggest to do that in the official version as well.

`
diff --git a/syntax/python.vim b/syntax/python.vim
index b7666d8..f1d630b 100644
--- a/syntax/python.vim
+++ b/syntax/python.vim
@@ -160,6 +160,8 @@ endif
         syn match pythonSpaceError  "\s\+$" display
     endif
 
+   " Shift Space
+    syn match pythonError " " display
 " }}}
 
 " Strings {{{
`

**Comment by diraol** [comment]
Hi @AKielhorn, I don't think I understood the issue correctly.

**Comment by AKielhorn** [comment]
On a german keyboard the = sign is shift-0.

If you type
a = b
it is easy to hit the space bar, while you hold down the shift key.
Shift space is an No-Break-Space and thus incorrect syntax.
Since you can't see the difference it would be nice to have that marked an an error.
