### ISSUE TITLE
Error detected while processing function pymode#init:

### ISSUE THREAD

**Issue by Edward66** [python-mode/python-mode#1072]
I  google this question for a while, however, not able to solve it.   My python version is 3.6.8 , neovim version is 0.3.8 and system is MacOs 15.15.3 . Can anybody help me  ? thank you!
`
Error detected while processing function pymode#init:

line    2:

E121: Undefined variable: import

line    3:

E121: Undefined variable: sys

line    4:

E121: Undefined variable: sys

Error detected while processing /Users/liangshaohua/.vim/plugged/python-mode/autoload/pymode/virtualenv.vim:

line    3:

E121: Undefined variable: from

Error detected while processing /Users/liangshaohua/.vim/plugged/python-mode/ftplugin/python/pymode.vim:

line   25:

E121: Undefined variable: from

Press ENTER or type command to continue
`

**Comment by usmcamp0811** [comment]
I've got the same problem running `Arch Linux`, `Python 3.8.1`, and `NVIM v0.4.3`

**Comment by smilesun** [comment]
same problem here with debian 9

**Comment by diraol** [comment]
Hi all, can you provide more info from your systems please?

Like, which is the commit hash from your python-mode?

Are your python-mode submodules updated?

How did you installed python-mode?

Can you try reinstalling python-mode from scratch following https://github.com/python-mode/python-mode#how-to-install ?

**Comment by smilesun** [comment]
@diraol Hi Diraol, obviously it works on my old machine, but when I run plugin update again, it shows the same error as @Edward66  posted above. So obviously, the new commit has broken pymode somehow.  I use Bundle as the manager and I always run Bundle update.

**Comment by smilesun** [comment]
Plugin 'python-mode/python-mode', { 'branch': 'develop' }  
is the line i put in my vimrc for Bundle

**Comment by smilesun** [comment]
here is the error message 
```
main.py" 219L, 9676C                                                                                                                                                                                       
Error detected while processing function pymode#init:                                                                                                                                                       
line    2:                                                                                                                                                                                                  
E121: Undefined variable: import                                                                                                                                                                            
E15: Invalid expression: import sys, vim                                                                                                                                                                    
line    3:                                                                                                                                                                                                  
E121: Undefined variable: sys                                                                                                                                                                               
E15: Invalid expression: sys.path.insert(0, vim.eval('a:plugin_root'))                                                                                                                                      
line    4:                                                                                                                                                                                                  
E121: Undefined variable: sys                                                                                                                                                                               
E15: Invalid expression: sys.path = vim.eval('a:paths') + sys.path                                                                                                                                          
Error detected while processing /home/sunxd/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:                                                                                                         
line    3:                                                                                                                                                                                                  
E121: Undefined variable: from                                                                                                                                                                              
E15: Invalid expression: from pymode.virtualenv import enable_virtualenv                                                                                                                                    
Error detected while processing function pymode#breakpoint#init:                                                                                                                                            
line    9:                                                                                                                                                                                                  
E15: Invalid expression: << EOF                                                                                                                                                                             
E15: Invalid expression: << EOF                                                                                                                                                                             
line   11:                                                                                                                                                                                                  
E492: Not an editor command: from importlib.util import find_spec                                                                                                                                           
line   13:                                                                                                                                                                                                  
E110: Missing ')'                                                                                                                                                                                           
E15: Invalid expression: ('wdb', 'pudb', 'ipdb', 'pdb'):                                                                                                                                                    
line   19:                                                                                                                                                                                                  
E170: Missing :endfor                      
```

**Comment by Edward66** [comment]
@diraol Hi Dirao, I installed python-mode via vim-plug.
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' } is the line i put in my vimrc for Bundle

**Comment by diraol** [comment]
Hum.... You all are using NVim.... that had escaped from my initial reading.

I have never used it, to be honest.

vim + python-mode is working nice for me in at least three computers, all of them with debian and vim installed with *only* _python3_ support (no python2 suuport).

Can you please follow the [Troubleshooting Section](https://github.com/python-mode/python-mode#troubleshootingdebugging) to gather more information, please?

**Comment by smilesun** [comment]
If i change the python interpreter to be python3 instead of python, it will then work. But still pymode is using a wrong python version, since I am using anaconda.

**Comment by deploy-soon** [comment]
Same problem running Ubuntu 18.04, Python 3.6.10 :: Anaconda, and VIM 8.0

**Comment by deploy-soon** [comment]
I think the above error was caused because the command `PymodePython` set to `echo`

https://github.com/python-mode/python-mode/blob/30a73d861aba2e1a5e0693d3a3df30293182efe2/plugin/pymode.vim#L287-L312

To handle this problem
@Edward66 @usmcamp0811 
How about change the `g:pymode_python` in `~/.vimrc`
```
let g:pymode_python='python3'
```

@smilesun 
To specify anaconda python interpreter, you can set interpreter version explicitly
```
let g:pymode_virtualenv=1
let g:pymode_virtualenv_path='/home/soon/anaconda3'
```

**Comment by diraol** [comment]
> think the above error was caused because the command PymodePython set to echo

Hum... good catch.... Any suggestion what to do with it @deploy-soon?

**Comment by deploy-soon** [comment]
In `pymode#init`, the command `PymodePython import sys, vim` often read to `echo import sys, vim` and vim tries to read it as some functions, finally this becomes E121, E15 errors.  How about change `echo` command to `return` command to avoid these errors. @diraol

**Comment by Edward66** [comment]
> I think the above error was caused because the command `PymodePython` set to `echo`
> 
> https://github.com/python-mode/python-mode/blob/30a73d861aba2e1a5e0693d3a3df30293182efe2/plugin/pymode.vim#L287-L312
> 
> To handle this problem
> @Edward66 @usmcamp0811
> How about change the `g:pymode_python` in `~/.vimrc`
> 
> ```
> let g:pymode_python='python3'
> ```
> 
> @smilesun
> To specify anaconda python interpreter, you can set interpreter version explicitly
> 
> ```
> let g:pymode_virtualenv=1
> let g:pymode_virtualenv_path='/home/soon/anaconda3'
> ```
Thank you,  i works!
