### ISSUE TITLE
jump from if to else and elif

### ISSUE THREAD

**Issue by smilesun** [python-mode/python-mode#1073]
I tried [] ][ and ]m and it does not work, suppose I am currently at "if", then after 100 lines, there is a elif, how can i jump to there?

**Comment by lieryan** [comment]
Simplest way currently is just to do a /-search: `/else` or `/elif` (this is just vim, no python-mode).

This simple match pattern isn't smart, so if you have nested if-elif-else, it will match all the inner ones as well.

If you want the search match to be able to handle nested if-elif-else, you can add a mapping like this in your .vimrc:

    nnoremap g/e /^<C-R>=repeat(" ", indent('.'))<CR>\zs\(if\\|else\\|elif\)<CR>

This search pattern jumps to an if/else/elif keyword that have the same indentation level as the line under the cursor. Note this search pattern won't work correctly in files that uses tab for indentation.
