### ISSUE TITLE
Editing single-quoted strings crashes

### ISSUE THREAD

**Issue by NeilGirdhar** [python-mode/python-mode#1074]
To reproduce:

1. vim a.py
2. Type `i` to enter insert mode, then
```
'a'
``` 
then escape to exit insert mode.
3. Type `h` to go left so that the cursor is over the `a`.
4. Type `i` to enter insert mode, then `a_`.

Python mode crashes.

[My vimrc](https://termbin.com/38w9)

**Comment by lieryan** [comment]
Can't reproduce this.

**Comment by NeilGirdhar** [comment]
Thanks a lot for trying!  Did you try it with my vimrc?  i can take an asciicinema if that helps?

**Comment by lieryan** [comment]
I'd suggest you should trim down your vimrc to the minimal configuration that still causes a crash. 

Also, add environment info like what Vim version, python version, which distro, and python-mode version that you're using. 

Try varying some of these environments and figure out which ones crashes and which ones would make the crash disappear.

**Comment by NeilGirdhar** [comment]
Sorry, this is actually an issue with mucomplete.  My bad.

**Comment by NeilGirdhar** [comment]
@lieryan Sorry, this is happening again.  Says:

```
Error detected while processing function pythoncomplete#Complete[35]..provider#python#Call:
line 18
  File "<string>", line 1
    vimcomplete('a', ''x_')
                        ^
```

**Comment by NeilGirdhar** [comment]
My vimrc:
```
set nocompatible
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'lifepillar/vim-mucomplete'

call vundle#end()
filetype plugin indent on

let g:mucomplete#enable_auto_at_startup = 1
```

**Comment by NeilGirdhar** [comment]
Only happening in neovim though.

**Comment by NeilGirdhar** [comment]
Ah, got it.  I have to `pip3 install --upgrade pynvim`
