### ISSUE TITLE
Add Better refactoring UI

### ISSUE THREAD

**Issue by blayz3r** [python-mode/python-mode#1076]
From
![image](https://user-images.githubusercontent.com/12205650/75100340-3cb46000-559a-11ea-9b36-ec17d85c9577.png)

Maybe to something like this
![image](https://user-images.githubusercontent.com/12205650/75100355-8735dc80-559a-11ea-979e-b1113e200125.png)

**Comment by lieryan** [comment]
What problem is this trying to solve?

Vim is not \<insert-whatever-other-text-editor\>, of course things looks different.

The current refactoring UI works just fine, in what ways would the UI in the screenshot be "better" than the current UI?
