### ISSUE TITLE
syntax highlighting issue

### ISSUE THREAD

**Issue by lodagro** [python-mode/python-mode#1078]
![image](https://user-images.githubusercontent.com/1094464/75522174-9b019880-5a09-11ea-9012-67f847a65ee5.png)

Somehow in the middle of the docstring the syntax highlighting goes wrong.
When removing either the ```"``` around annotation, or replacing ```"``` with ```'``` for arg1_default or removing the ```)``` after TODO highlighting is back ok again.

With ```let g:pymode_syntax=0``` highlighting is ok.

**Comment by diraol** [comment]
I don't remember how we do syntax highlighting, if it is something built in (most likely) or an external tool, but I'd say that if is missing "Annotations" recognition.

Any help to review the plugin in order to improve this point is very welcome!

**Comment by diraol** [comment]
Btw, those are the two files that would need to be updated to support annotations:

https://github.com/python-mode/python-mode/tree/develop/syntax
