### ISSUE TITLE
How to desactivate some warnings or errors raidsed by PymodLint?

### ISSUE THREAD

**Issue by lalebarde** [python-mode/python-mode#1082]
I have many warnings and errors I don't want like `line too long`:

![image](https://user-images.githubusercontent.com/3611049/77856118-44989d00-71f5-11ea-9a68-6ac8e300e87d.png)

How can I desactivate them please?

Following the documentation, I have tried editing  `~/.pylint.rc` but it is not taken into account:
```
let g:pymode_lint_ignore = ["E203", "E262", "E265", "E302", "E501", "E702", "W0401", "W0404", "W0611", 
let g:pymode_lint_sort = ['E', 'C', 'I']
```

**Comment by lalebarde** [comment]
There was a typo above, I have tried the following syntax without success:
```
let g:pymode_lint_ignore = ["E203", "E262", "E265", "E302", "E501", "E702", "W0401", "W0404", "W0611"]
let g:pymode_lint_ignore = "E203, E262, E265, E302, E501, E702, W0401, W0404, W0611"
let g:pymode_lint_ignore = "D203, D262, D265, D302, D501, D702, D0401, D0404, D0611"
let g:pymode_lint_options_pep8 = {'ignore': 'D100,D101,D102,D103'}
let g:pymode_lint_options_pep8 = {'ignore': 'E203,E262,E265,E302,E501,E702,W0401,W0404,W0611'}
```

**Comment by diraol** [comment]
Hi @lalebarde ! Sorry for the late answer, things are going crazy over here.... ;)

To disable linter rules using `python_mode` config (`g:pymode_lint_ignore`) you should add them to your `.vimrc` file.

The `~/.pylint.rc` file should contain pylint style config, like [this](https://github.com/PyCQA/pylint/blob/master/pylintrc).

**Comment by diraol** [comment]
Hi @lalebarde were you able to try what I said?
