### ISSUE TITLE
Indexed dunder names in strings destroy indentation, which is bad

### ISSUE THREAD

**Issue by leycec** [python-mode/python-mode#1083]
Firstly, thanks for all the voluminous volunteerism! `python-mode` is the central dogma of my workflow. @diraol and friends: *you deserve all the Internet karma.*

Secondly, embedding an **indexed dunder name** (i.e., a Python identifier both prefixed and suffixed by `__` and then indexed with `[`- and `]`-delimited syntax, like `__idunderevenknow__[punsforlife]`) within a Python string fundamentally destroys indentation for the remainder of the current buffer.

That's kinda bad.

## MLE for the checkmate

Minimal length example (MLE) or it didn't happen, so:

```
uwutm8 = '__muhsweetsweetdunder__[idonteven]'
```

Define a new Python file containing the above one-liner, open that file under `python-mode` with Vim, and hit `o`. That's it. Pretty minimal, eh?

If your Vim installation is anything like mine (*...it's probably not*), you should note that the cursor now jumps to the character on the next line immediately under the `i` in `idonteven` (i.e., the 35th column). This is, of course, horribly wrong. The cursor should instead jump to the first character of the next line (i.e., the first column).

Pictorially, here's what currently happens and what *should* happen – where `^` denotes the position of the cursor after hitting `o`:

```
column:  12345678901234567890123456789012345678901234567890
content: uwutm8 = '__muhsweetsweetdunder__[idonteven]'
cursor:                                    ^   # what currently happens
cursor:  ^                                     # what should happen instead
```

To compound matters, `python-mode` *permanently* shifts its indentation level to the 35th column. This is basically insane and renders `python-mode` unusable for *any* Python buffers containing such strings – like, say, the [runtime type checker I might currently be implementing if it weren't for this bug](https://github.com/beartype/beartype).

I half-heartedly tried debugging this myself but rapidly became lost within the labyrinthine bowels of the `python-mode` codebase. `pymode#indent#get_indent()` looks superficially sane, but I'm dead-sure there's something stinky and insane lurking in there.

## `python-mode` for life

`python-mode` is just how I roll. It's also the fragile fulcrum holding up my quasi-religious infatuation with Vim. So, it'd be super-sweet if this could be resolved before the next apocalypse. Thanks for all the continued plugin excellence, all!

**Comment by leycec** [comment]
**lolbro.** I just discovered this issue is confined to single-quoted strings. Double-quoted strings exhibit the correct behaviour, which is beyond bizarre (but such is life with Vim):

```
# This actually does the right thing rather than destroying everything.
uwutm8 = "__muhsweetsweetdunder__[idonteven]"
```

I don't pretend to understand reality. I only document it.

**Comment by leycec** [comment]
**ohboy.** While double-quoted strings formatted as above *do* exhibit the correct behaviour with respect to indentation, I've just discovered that they cause syntax highlighting to non-deterministically fail for the remainder of the current buffer. For unknown and probably horrible reasons, these sorts of strings cause `python-mode` to incorrectly match the rest of the buffer as (*...wait for it*) a single huge comment. Yeah. That's awful.

By "non-deterministically," I mean I can't find a minimal length example exhibiting the failure despite stumbling over it often enough in an 800-line buffer to know that it's happening. I'm now skirting the above issues entirely by splitting these strings over multiple lines in a manner that disrupts dunder matching: e.g.,

```
# This behaves correctly with respect to indentation and syntax highlighting. Yay!
uwutm8 = (
    "_"
    "_muhsweetsweetdunder_"
    "_[idonteven]"
)
```

I mean, that's cray-cray. But at least there are no runtime performance concerns... *I hope.*

**EDIT:** Actually, even *that* doesn't work. Syntax highlighting still fails. Whatever eldritch and unspeakable things are happening here must be operating at the Python AST level – maybe? I don't quite know what to make of any of this, but it sure is frustrating. Let's blame Rope.

**Comment by diraol** [comment]
Hello @leycec !

Quick question, have you tried your example with a clean vim setup with only python-mode and no other plugins or non-default-vim-configs? I'm asking this because I've just tried your MLE and I could not reproduce that behavior here, regarding indentation.

To do the test, what I did was:

`vim -u "<path_to_python_mode_folder>/debugvimrc.vim" mle.py`

Could you please try this? And the also share here the `/tmp/pymode_debug_file.txt` file :)

**Comment by leycec** [comment]
**Fascinating.** If you can't reproduce this, I devoutly believe you. Let's bisect my `dein` plugin setup and see if I can't isolate this further for you. I suspect a silent plugin conflict, but... this sure is a bizarro issue.

Thanks for bearing with me, @diraol! You're unspeakably awesome. :+1: 

**EDIT:** Indeed, `debugvimrc.vim` is a choice find. A vanilla Vim setup fails to replicate this, so this is all on my non-trivial `dein` configuration... *somehow.* I'm closing this for now to spare everyone's sanity. If bisecting plugins yields any fruit, I'll reopen this with apologies. Muchas gracias, amigo.

**Comment by leycec** [comment]
**Oh, wait.** `vim -u ~/.vim/dein/repos/github.com/python-mode/python-mode/debugvimrc.vim mle.py` superficially works, but doesn't actually appear to enable `python-mode` – at least, not with respect to indentation. If I define a trivial one-line file resembling the following, I expect hitting `o` in Normal mode to add a new line indented under that one-liner:

```
if True:
```

That doesn't happen. The cursor remains unindented on the newly added line (i.e., remains at the first column). Does `debugvimrc.vim` properly indent the above one-liner for you? I'm probably doing something painfully foolish. Please educate my ignorance away, Vim Sempai.

**Comment by diraol** [comment]
Hi @leycec, indeed, that default config does not have indentation (or syntax highlight btw) enabled by default.

Try adding the following to the debugvimrc.vim file:

```
filetype plugin indent on
syntax on
```

**Comment by leycec** [comment]
**Sweetness.** Thanks for the prompt education, as always. Let's give that a-go!

**Comment by leycec** [comment]
`</sigh>`

Unsurprisingly, this is entirely my fault – though I'm unsure how or why yet. `vim -u ~/.vim/dein/repos/github.com/python-mode/python-mode/debugvimrc.vim mle.py` now fails to replicate this issue, [exactly as you say](https://github.com/diraol). If I successfully bisect the culprit in my plugin configuration, I'll promptly let everyone know.

Until then, may the sanitary N95 mask be with you on your plague-ridden journey through the 2020's! :mask:

**Comment by diraol** [comment]
Hey @leycec ! Well, at least we have discovered new things! :)

Yeah, my current vim setup is also causing trouble to my python-mode setup and I haven't had time to fix it yet (I haven't been coding too much python, so this is lowering my priority in fixing my own setup :man_shrugging: )

Anyway, let us know if we can help ;)

And be safe! Cheers!

**Comment by leycec** [comment]
**Bisection: _complete_.** Labourously bisecting both my set of dein plugins *and* non-dein Vim configuration yielded the true culprit. Taiko drum roll, please. Without further ado, the problematic plugin is...

...`python-mode`! I know, right? Of course, `python-mode` with the default configuration is just fine – as demonstrated above. It's `python-mode` with a [custom spell-checking configuration](https://vi.stackexchange.com/a/24534/16249) that induces this anomalous behaviour, which is sad but sadly true.

I recently enabled spell checking on Python docstrings and comments, which worked well. I then [disabled spell checking for a laundry list of various word fragments that should *never* be spell checked](https://vi.stackexchange.com/a/24534/16249), which superficially also worked well but actually caused `python-mode` to subtly fail with this issue. Specifically, I defined a `~/.vim/after/syntax/python.vim` file containing exactly:

```
" Avoid spell checking URIs.
syntax match NoSpellPythonUri
  \ /\v\w+:\/\/[^[:space:]]+/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell

" Avoid spell checking both CamelCase-formatted identifiers and uppercase
" identifiers. Since most languages (excluding Raku) prohibit Unicode in
" identifiers, these matches are intentionally confined to ASCII codepoints
" (e.g., "[A-Z]" rather than "[[:upper:]]").
syntax match NoSpellPythonCaps
  \ /\v<[A-Z]([A-Z0-9]{-1,}|[a-z0-9]+[A-Z0-9].{-})>/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell

" Avoid spell checking snake_case-formatted identifiers.
syntax match NoSpellPythonSnake
  \ /\v<\w+_.{-1,}>/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell

" Avoid spell checking "@"-prefixed identifiers.
syntax match NoSpellPythonDecorator
  \ /\v\@[a-zA-Z].{-}>/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell

" Avoid spell checking ":"-delimited substrings.
syntax match NoSpellPythonColons
  \ /\v:[^:]+:/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell

" Avoid spell checking "`"-delimited substrings.
syntax match NoSpellPythonTicks
  \ /\v`[^`]+`/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell

" Avoid spell checking '"'-delimited filetyped filenames matched as a
" double-quoted substring containing a filename prefix, a period, and one to
" four characters comprising a filetype.
syntax match NoSpellPythonPath
  \ /\v"[^"]+.[^"]{1,4}"/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell
```

**Exactly one of the above `syntax` statements is the culprit.** Can you guess which? I never would have been able to, but you are a just and erudite man. The culprit was... *the snake_case matcher:*

```
" Avoid spell checking snake_case-formatted identifiers.
syntax match NoSpellPythonSnake
  \ /\v<\w+_.{-1,}>/ transparent
  \ contained containedin=pythonComment,python.*String contains=@NoSpell
```

I didn't see that one coming. But... there it is. I need `python-mode` more than I need to avoid spell-checking snake_case identifiers in comments and docstrings, so I've just disabled the above `syntax` statement with a note redirecting here.

Clearly, this is low priority. And... I can't fault you for shifting volunteer efforts away from `python-mode`. If Python isn't bringing in those paper dollars, you go wherever the fragrant money flows. I just thought *somebody* else in the world who isn't me might hit a similar issue and scratch their head in confusion until it bleeds.

Now they don't have to. Thanks for all the intrepid volunteerism, @diraol. Whether you come back to `python-mode` or not, your work has been a tremendous boon to us all in the Python **+** Vim community. You'll always be amazing – and so will `python-mode`. :smiling_face_with_three_hearts:

**Comment by diraol** [comment]
Wow! This was a quite impressive investigation @leycec ! Well done!

To be honest with you, I have limited Vim Script knowledge and adding to it my lack of free time, it will be quite hard for me to try to fix this specific issue. So, if you can find some time digging around in python-mode codebase to be able to improve it to have such options withing python-mode and with configs to enable/disable them, that would be extremely awesome! And for sure you have more context in order to do it than I do at this moment since you have been digging it.

Despite the fact that this is not exactly a bug in python-mode, I'd say it would be an improvement to be made, I'll let the issue open (and If I can find some time to look at it I'll give it a try, but that won't happen soon I guess :)

But again, thanks for the dedication and the shared knowledge!

And I have to say that I'm only maintaining this plugin, but it wouldn't be here if it wasn't for Kirill Klenov and Felipe M. Vieira, among all other contributors!
