### ISSUE TITLE
error in my code

### ISSUE THREAD

**Issue by macegosso** [python-mode/python-mode#1085]
that's my code

import random
horast = input("Digite a quantidade de horas trabalhadas");
horasg = input("Digite o  ganho por hora trabalhada");

sbruto = horasg * horast;

zero = (0/100) *sbruto;
tres = (3/100) *sbruto;
cinco = (5/100) *sbruto;
dez = (10/100) *sbruto;
onze = (11/100) *sbruto;
vinte = (20/100) *sbruto
sl900 = (sbruto - zero - dez - tres - onze );
sl1500 = (sbruto - cinco - dez - tres - onze);
sl2500 = (sbruto - dez - dez - tres - onze);
sl2501 = (sbruto -  vinte - dez - tres - onze);

if sbruto <= 900 :
  print ("Seu salário bruto é de {}", sbruto )
  print ("(-) IR (0%) : R$", zero )
  print ("(-) INSS (10%): R$",dez )
  print ("(-) Sindicato (3%): R$", tres )
  print ("FGTS (11%): R$",onze )
  print ("Total de descontos: R$", zero + dez + onze + tres )
  print ("Salário Liquido: R$ {}", sl900

elif sbruto >= 900 and sbruto <= 1500:
  print ("Seu salário bruto é de {}", sbruto )
  print ("(-) IR (5%) : R$", cinco )
  print ("(-) INSS (10%): R$",dez )
  print ("(-) Sindicato (3%): R$", tres )
  print ("FGTS (11%): R$",onze )
  print ("Total de descontos: R$", zero + dez + onze + tres )
  print ("Salário Liquido: R$ {}", sl1500

elif sbruto >1500 and <2500 :
  print ("Seu salário bruto é de {}", sbruto )
  print ("(-) IR (10) : R$", dez )
  print ("(-) INSS (10%): R$",dez )
  print ("(-) Sindicato (3%): R$", tres )
  print ("FGTS (11%): R$",onze )
  print ("Total de descontos: R$", zero + dez + onze + tres )
  print ("Salário Liquido: R$ {}", sl2500

else sbruto >2500 :
  print ("Seu salário bruto é de {}", sbruto )
  print ("(-) IR (20%) : R$", vinte )
  print ("(-) INSS (10%): R$",dez )
  print ("(-) Sindicato (3%): R$", tres )
  print ("FGTS (11%): R$",onze )
  print ("Total de descontos: R$", zero + dez + onze + tres )
  print ("Salário Liquido: R$ {}", sl2501

on the "elif sbruto >= 900 and sbruto <= 1500:" is giving a synthax error

**Comment by diraol** [comment]
1) Next time you add some code, use the "code block" to keep the code indentation.

2) You are missing the closing parenthesis in the last `print` statement of each if/elif/else group.

**Comment by diraol** [comment]
@macegosso ?
