### ISSUE TITLE
pymode/__init.py__ using .autopep8 instead of autopep8 with no leading '.'?

### ISSUE THREAD

**Issue by AKS2346** [python-mode/python-mode#1087]
I was getting an error importing from autopep8.    The code says 
"from .autopep8 import fix_file"

changing this to : 
"from autopep8 import fix_file"  #Took out the leading . from autopep8

worked for me.  

Should this be changed? or Have I done something incorrect somewhere?

**Comment by diraol** [comment]
This should work.

My guess is that you haven't cloned the submodules.

If you have cloned/installed `python-mode` manually, try removing the `python-mode` directory and cloning it again with `git clone --recurse-submodules https://github.com/python-mode/python-mode`.

Other wise try running `git submodule update --init --recursive`.

**Comment by AKS2346** [comment]
Thank you D.  I"ll take a look at how I cloned it.  Appreciate your help.  It does work now very smoothly.  But better to have a full installation.
