### ISSUE TITLE
How to remove vertical line/separator

### ISSUE THREAD

**Issue by qazip** [python-mode/python-mode#1089]
Sorry that I don't know the correct word for the line, else I could probably search for it!

After installing python-mode, there is now a vertical line/separator, which probably signals X characters, the recommended line width. How do I remove that?

**Comment by jakecolston** [comment]
I think you're referring to the PEP8 max line length visual?  The one which shows you if you are crossing the recommended max line length?
If so, this should be configured in your `.vimrc` with a line like:
`let g:pymode_options_max_line_length = 119`
where 119 would be the last character position _before_ the vertical line.

**Comment by jakecolston** [comment]
If you want to completely remove it, this worked for me:
`let g:pymode_options_colorcolumn = 0`

**Comment by diraol** [comment]
@qazip does that works for you? :)

Thanks @jakecolston for answering!
