### ISSUE TITLE
Requires python issue on Mac OS

### ISSUE THREAD

**Issue by dr-costas** [python-mode/python-mode#1090]
Hi, 

I have the following VIM installation: 

```bash
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2020 00:47:07)
macOS version
Included patches: 1-539
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +fullscreen        +num64             +textobjects
+browse            -gettext           +odbeditor         +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl/dyn          +toolbar
+cindent           +job               +persistent_undo   +transparency
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static
```

When I'm doing `:echo has("python")` I get an `1`, but when I'm using Pymode and VIM starts, I get the error: 

`[Pymode]: error: Pymode requires vim compiled with +python. Most of features will be disabled`

Python version: 

`Python 3.7.3`

Any help?

**Comment by diraol** [comment]
Hi @dr-costas.

First thing I'd add here is that `python-mode` does not support python2 anymore. We have dropped Python2 support in favor of Python3. Because of that what we do check is if `python3` is available or not.

Also, worth saying that it was a known problem that working with vim compiled with support for both python and python3 has been a known issue for a long time, and usually compiling vim with only python3 support usually solve many problems.

We've talked about it in this issue (and the linked ones too):
https://github.com/python-mode/python-mode/issues/1070

**Comment by dr-costas** [comment]
Hi @diraol 

Thank you for the answer. 

I think I cannot understand your message. Why are you mentioning about Python 2? Both the version of Python that I have/use and the Python that VIM is compiled is Python 3, as seen from my post. 

Am I missing something?

**Comment by diraol** [comment]
@dr-costas,
from your own post we can see that you vim was compiled with support to `python` (python2) and `python3`:
![image](https://user-images.githubusercontent.com/192702/82126165-49071e00-9781-11ea-80e8-98a6b1cfe74c.png)

Also, `:echo has("python")` is a test for python2 as far as I know. If you wanna test for python3 you have to do `:echo has("python3")`.

Last but not least, as I've said, Vim (not python-mode) has some issues handling two python versions at the same time (`python` and `python3`).

Ps.: I've just noticed in the warning you have shared that we are sending the wrong message with it. We missed this warning message when we dropped python(2) support, I'll update it to state clearly that we need python3. ;)

**Comment by dr-costas** [comment]
@diraol 

Oh, I see! Now makes more sense. I will do what you said and update you here. 

Thnx!

**Comment by dr-costas** [comment]
Hi, 

I managed to run Vim without the issue, though now I'm getting 

'Abort trap 6.'

I made another issue, to have things a bit tidy.
