### ISSUE TITLE
Struggling with rope autocompletion

### ISSUE THREAD

**Issue by dhavalsavalia** [python-mode/python-mode#1092]
Hello,

Wonderful plug-in first of all. And sorry for being ignorant.
I enabled completion on `dot` and while it is working great! I have to press `tab` or `shift+tab` to get to desired completion. I think I am doing something wrong here.
Is there a way to start typing name of variable, method and get to the completion rather than pressing `tab` every time. Right now, after pressing `dot` it places first result and any text I type is appended to it.

What would be better practice here?

I am using MacVim as vim client.

Thanks and stay safe!

**Comment by diraol** [comment]
Hi @dhavalsavalia !

`python-mode` autocompletion is provided by the `rope` tool, so if you wanna change autocompletion behavior you need to set the configs for Rope plugin..

Take a look at python-mode docs about it:
https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L397

One important warning. We are keeping `rope` updated, but we haven't changed the `pymode_rope` configs for a while, so it is possible that some of those configs misbehave. If you find any of these configs that does not work anymore, drop an issue about it and let's try to fix it :)
