### ISSUE TITLE
How do I convert month name to number in Jupyter notebooks?

### ISSUE THREAD

**Issue by ShantelWilson** [python-mode/python-mode#1098]
Hi Everyone, 
I'm trying to do a bar plot in matplotlib.pyplot but I wanted to convert the name of the month to a number first?

I'm in Jupyter notebooks. Any idea how can I do this? I appreciate any advice you can give me!

Thank you! 
![Movie Jupyter](https://user-images.githubusercontent.com/61215041/89740580-9ed12680-da4f-11ea-9398-fed7ec004c34.png)

**Comment by diraol** [comment]
Hi @ShantelWilson your question is not related to python-mode, so I'd suggest you to look for a better forum for this.

[Stackoverflow](https://stackoverflow.com/) is a better fit for your question, adding tags such as `python`, `data science`,  `matplotlib`, `pandas` and so on. For sure your chances of getting an answer there are way better than here. :smiley: 

This issue tracker is specific for `python-mode` vim plugin problems.

Best regards!
