### ISSUE TITLE
[pylint E0401] [E] Unable to import 'xxxxxxx' (import error)

### ISSUE THREAD

**Issue by Adolf-L** [python-mode/python-mode#1101]
![image](https://user-images.githubusercontent.com/10137107/91147493-ee1f8400-e6ea-11ea-847a-ef9b15c83875.png)

As you can see, my vim with pymode plugin doesn't work normal.  How to fixed it 

when I use Pycharm it works ok. as you can see
![image](https://user-images.githubusercontent.com/10137107/91147717-3b035a80-e6eb-11ea-8468-31cad9d5844e.png)

I guess the problem comes from python-mode or configuration? or  may I need do some configuration of pymode to fix this ?

**Comment by danuker** [comment]
What happens when running the file from a terminal? Which Python is the terminal using? (`which python`)

Do you have a virtual environment?
