### ISSUE TITLE
Preview window

### ISSUE THREAD

**Issue by jfernandz** [python-mode/python-mode#1106]
Is there any possibility of setting up the preview window to the right side? I've reading [the docs](https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L140) but I don't see how many options does admit `g:pymode_preview_position` I've tried the most usual and didn't work. I guess this feature must be improved.

**Comment by diraol** [comment]
I've never seen this in python-mode, probably it would be something to be added/coded indeed.
