### ISSUE TITLE
ModuleNotFoundError: No module named 'pylama'

### ISSUE THREAD

**Issue by ahmadshiddiq** [python-mode/python-mode#1109]
So I just installed this plugin, after installing the plugin I found an error when open the python file. Error quite good, he said everything. Should I reinstall this plugin or I can fix this without reinstall?
I'm still learning python, I didn't much know about the module or something.

Here the image:
[image](https://user-images.githubusercontent.com/53107961/96327684-fb5f4c00-1065-11eb-8cc4-9418d9682ace.png)

**Comment by diraol** [comment]
Hi @ahmad-shiddiq, welcome!

How did you install `python-mode`?

Have you seen our documentation on how to do it? https://github.com/python-mode/python-mode#how-to-install

**Comment by ahmadshiddiq** [comment]
Yep, I use these for installing plugin : `Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }`

**Comment by diraol** [comment]
Try running these two commands inside python-mode directory:
```
git submodule sync --recursive
git submodule update --recursive --init --force
```

**Comment by ahmadshiddiq** [comment]
Yeah, that fixed, but need a long time to download those things.
