### ISSUE TITLE
Run PyLint in background

### ISSUE THREAD

**Issue by jonasdiemer** [python-mode/python-mode#111]
The linter takes some time to execute, during which vim is unusable. This is especially annoying during save (I know lint-on-save can be turned off, but I want to use it).

Syntastic seems to be able to run the linter in the background, see e.g. https://github.com/scrooloose/syntastic/pull/243

It would be great if python-mode could do the same.

**Comment by sassanh** [comment]
@klen is it working in current versions too? When I write the file it still takes quit time (like 7-10 seconds) to check. Is there an option that should be set or is this functionality removed in later versions?

**Comment by dapicester** [comment]
@klen is this working in latest 0.9.0? Should I change any setting?
