### ISSUE TITLE
Error in simple C++ methods and objects code

### ISSUE THREAD

**Issue by ShantelWilson** [python-mode/python-mode#1110]
Hi Everyone,

I am making this simple class and object program that takes in a number then multiplies it by a number then returns that value.
Also the second method adds to numbers then returns that value. 

I am getting errors on line 1 that said **LNK1120	1 unresolved externals**	and 
**Error	LNK2019	unresolved external symbol "public: __thiscall c1::c1(void)" (??0c1@@QAE@XZ) referenced in function _main**

Also, on line 35 Im getting  **C4244	'return': conversion from 'int' to 'float', possible loss of data	MidTermPractice2**		

I tried to debug the code myself but can't seem to find out what is causes this. 
Any help or advice would be greatly appreciated!

``
#include<iostream>
using namespace std;

class c1
{
	float f;
	

public:
	c1();

	float multiply(int a);
	float max(int b, int c);

};

float c1::multiply(int a) {

	cout << "Please enter a number:" << endl;
	cin >> a;
	return a * f;
		
};

float c1::max(int b , int c) {

	cout << "Please enter a number" << endl;
	cin >> b;
	cout << "Please enter another number" << endl;
	cin >> c;
	return b + c;
	

};
int main()
{

	c1 obj1;

	obj1.multiply(9);

	obj1.max(9,8);

	return 0;
};``

**Comment by diraol** [comment]
Hi @ShantelWilson, you have created this issue with your question in `python-mode` issue tracker.

`python-mode` is a [vim](https://www.vim.org/) plugin for python development. It has no relationship at all with C++.

If you need help with C++ coding, I'd suggestion you to ask in [stackoverflow](https://stackoverflow.com/), there it will be much easier for you to find the help you need.

Regards,

Diego
