### ISSUE TITLE
stuck on saving a python file.

### ISSUE THREAD

**Issue by GregXu247** [python-mode/python-mode#1122]
the vim interface is shown below:
-------------------------------------------------------------
 D/test.py                                                                           
-  1 import numpy as np                                                              
   2                                                                                 
   3 if __name__ == '__main__':                                                      
   4     print("hello world!") #helloworld!                                          
~                                                                                    
~                                                                                    
~                                                                                    
 ~/Desktop/test.py   CWD: /home/linus   Line 4  Col 38                               
[Pymode] Init Rope project: /home/linus
------------------------------------------------------------
![屏幕截图 2021-02-21 112501](https://user-images.githubusercontent.com/16523275/108614671-95316e00-7437-11eb-98b0-e33ac2a7e713.png)

**Comment by diraol** [comment]
Hi, can you please try following our "Debug/Troubleshooting" section and provide more info, pleae?
https://github.com/python-mode/python-mode#troubleshootingdebugging

**Comment by GregXu247** [comment]
tried with annother project folder, nomore stuck. 
it looks like the stuck will happen when saving a python file in '/home/user' path, because the path contain too much files and folders.

**Comment by diraol** [comment]
Oh, indeed. The problem is trying to run `rope` in the home/root directory. Well spotted!
