### ISSUE TITLE
Can fix out of range Index Error for string manipulation problem.

### ISSUE THREAD

**Issue by ShantelWilson** [python-mode/python-mode#1129]
Hi Everyone, 

I am trying to create a program that takes two strings, string A and string B, then form a new string by concatenating multiple copies of String B. I used to while loop to know when to increment the index by in each array Somehow on line 18 I keeping getting an out of range Index Error and I can't understand how to fix it.

When I ran through the code j is 4 and the length of the string actually is 3. 

Here my code:

```
def solve(stringA, stringB):
    count: dict = {}

    for char in stringB:
        if char not in count:
            count[char] = 1
    for char in stringA:
        if char not in count:
            return None

    i = 0
    j = 0
    numStrings = 0
    result = ""
    string = ""
    while i in range(len(stringA)): # and 
        while j in range(len(stringB)):
            if stringA[i] != stringB[j]:
                j += 1

                string += "#"
            if stringA[i] == stringB[j]:
                string += stringB[j]
                i += 1
                j += 1
        if j > len(stringB) - 1:
            j = 0
            numStrings += 1
            result +=  string + " + "
            string = ""

    return result, numStrings   
    
    

print(solve("ZAZA", "BAZ"))
```
I appreciate any help or tips you can give me!

**Comment by diraol** [comment]
Hi @ShantelWilson, this issue tracker is focused on python-mode itself, and the error you posted is not related to python-mode, it is just a python error. So I'd suggest you to look for more proper places to ask, such as StackOverflow or python forums.
