### ISSUE TITLE
Invalid syntax (pyflakes E) in my code.  Please help ASAP.

### ISSUE THREAD

**Issue by ShauryaS12** [python-mode/python-mode#1131]
Hello,
I have an invalid syntax (pyflakes E) in my code below. I don't know why this problem in coming. Could anyone know why? Please tell me how to fix it. Thank you in advance

doom_env = gym.wrappers.Monitor(doom.env, "videos", force = True)

![my problem in ai](https://user-images.githubusercontent.com/83806162/117408616-d06b1580-af2d-11eb-83dd-51aefdd4b43e.JPG)

**Comment by diraol** [comment]
Hi @ShauryaS12 this issue tracker is focused in `python-mode` itself, and the error you posted is not related to `python-mode`, it is just a `python` error. So I'd suggest you to look for more proper places to ask, such as StackOverflow or python forums.
