### ISSUE TITLE
i am getting syntax error for this code

### ISSUE THREAD

**Issue by shubhamdl** [python-mode/python-mode#1132]
# Loop to calculate predict salary variables
    for i inrange(len(data.experience)):
        tmp = data.experience[i] * Beta + b
        salary.append(tmp)

MSE = mse(data.salary, salary)
return MSE

**Comment by diraol** [comment]
Hi @shubhamdl this is not an error from `python-mode`  itself, this is a python coding issue, so I'd advise you to look for help in more proper places such as StackOverflow or python forums. You will get much better as faster help in such places.

Regarding your issue, you didn't even say which error you're seeing, but I guess you are missing a space after the `in` operator in the first line.
