### ISSUE TITLE
  File "<ipython-input-67-4994ae760189>", line 2     urlimp=name.get()     ^ IndentationError: unexpected indent

### ISSUE THREAD

**Issue by V-iji7968** [python-mode/python-mode#1144]

**Comment by diraol** [comment]
Although there is no issue description, it doesn't seem to be a problem with python-mode, but an issue with the user python code itself (highlighted by the linter).

So it would be better to find help within python forums (or stackoverflow). The goal of this issue board is to handle python-mode tool errors.
