### ISSUE TITLE
This plugin is too slow

### ISSUE THREAD

**Issue by pychego** [python-mode/python-mode#1148]
 After I install Python mode, every time I open a python program  It takes nearly two seconds. Here is the loading time of the plugin:

883.361ms: sourcing /Users/chegopy/.vim/plugged/python-mode/ftplugin/python/pymode.vim

**Comment by diraol** [comment]
What are the conditions in which you are opening your python code?
Because it is directly related to the number of packages/modules/files that python-mode needs to read.
