### ISSUE TITLE
What is proper way to jump back after RopeGotoDefinition?

### ISSUE THREAD

**Issue by yevgenko** [python-mode/python-mode#150]
Ideally something similar to what CTags' Ctrl+T does

**Comment by SameerAsal** [comment]
Hi, 

When I use "RopeGoToDefinition" directly vim open a new buffer and moves to that buffer, which is the behaviour I prefer, using the pymode_rope_goto_definition (or whatever function pymode_rope_goto_definition_bind points to) it always opens a new spli window weather I use "new" or "vnew" . 

What other third option can I use to open the destination in a new buffer without bertical or horizontal splitting?
