### ISSUE TITLE
"no documentation found for 'print'" when press "K"

### ISSUE THREAD

**Issue by quchunguang** [python-mode/python-mode#156]
"no documentation found for 'print'" when press "K" on print
only show documents on some syntax like 'if', and standard library like 'os'( but not include the methods in it, only package itself!).

I have installed python-doc by,
    $ sudo apt-get install python-doc python3-doc
but issues still here.

OS: lubuntu 12.04

```
:call pymode#troubleshooting#Test()
```
# Pymode diagnostic

VIM:703, OS: Linux, multi_byte:1, pymode: 0.6.9
## Pymode variables:

let pymode = 1
let pymode_path = 1
let pymode_paths = []
let pymode_doc = 1
let pymode_doc_key = 'K'
let pymode_run = 1
let pymode_run_key = '<leader>r'
let pymode_lint = 1
let pymode_lint_checker = 'pyflakes,pep8,mccabe'
let pymode_lint_ignore = 'E501'
let pymode_lint_select = ''
let pymode_lint_onfly = 0
let pymode_lint_config = '/home/qcg/.vim/bundle/python-mode/pylint.ini'
let pymode_lint_write = 1
let pymode_lint_cwindow = 1
let pymode_lint_message = 1
let pymode_lint_signs = 1
let pymode_lint_jump = 0
let pymode_lint_hold = 0
let pymode_lint_minheight = 3
let pymode_lint_maxheight = 6
let pymode_rope = 1
let pymode_folding = 1
let pymode_breakpoint = 1
let pymode_syntax = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = []
pymode_utils_whitespaces:1
pymode_options:1
## VIM python paths:

/home/qcg/.vim/bundle/python-mode
/home/qcg/.vim/bundle/python-mode/pylibs
/home/qcg/dev/workspace_cdt/testpy
/usr/lib/python2.7
/usr/lib/python2.7/plat-linux2
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PIL
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7

**Comment by timfeirg** [comment]
from what I know, 'pydoc' works sometimes for built-in libs and never for my own project, but 'rope show doc' can always find documentation no matter where they're from.
why not drop 'pydoc' and  `let g:pymode_rope_show_doc_bind = 'K'` by default?
