### ISSUE TITLE
code completion with vim-iphyton instead of rope

### ISSUE THREAD

**Issue by mictadlo** [python-mode/python-mode#176]
Hi,
code completion with vim-iphyton ( https://github.com/ivanov/vim-ipython  )  instead of rope works great. Maybe any plans to remove rope?
##

**Comment by brycepg** [comment]
I think a IPython integration with this project is out of scope. (I know this is a very old comment but also python-rope is still being maintained while that plugin hasn't seen a commit in almost two years).
