### ISSUE TITLE
rope causes occasional hanging of vim

### ISSUE THREAD

**Issue by erezsh** [python-mode/python-mode#209]
Tested on Linux + vim (or gVim)

Occasionally when saving complex source code, vim writes the file and then may hang for several seconds.

changing /pylibs/ropevim.py:add_hook to return immediately (instead of hooking write) solves the problem.

**Comment by vineetp13** [comment]
still an issue on vim on OS X. 
After adding in "import numpy", when I try to use numpy.zeroes, it freezes.

**Comment by LuRsT** [comment]
Thanks @vineetp13, 2016 and I got this problem too :(. Should `let g:pymode_rope_lookup_project = 0` be a default?

**Comment by fmv1992** [comment]
I think it should or update the way rope works.

Currently I'm studying 'Learn Vimscript the Hard Way' and hope to be able to help this repos soon.

**Comment by LuRsT** [comment]
Awesome @fmv1992, but for the meantime I disabled rope completely while this is sorted, since that config above didn't work, it just delayed the rope_lookup a bit

**Comment by fmv1992** [comment]
Sure thing.

I did this too. Worth checking out:

https://valloric.github.io/YouCompleteMe/

I'm using and I'm very happy with it.

**Comment by LuRsT** [comment]
Thanks for the suggestion @fmv1992, but I wasn't even using rope's autocompletion feature :D. But I may look into that plugin :+1:

**Comment by revolter** [comment]
Still an issue in neovim on macOS Sierra.

**Comment by YOnoda** [comment]
This is not occasional but very frequent, happens whenever I save the buffer...
