### ISSUE TITLE
<C-space> rope completion doesn't respect completeopt (and/or needs "longest" option)

### ISSUE THREAD

**Issue by derekleverenz** [python-mode/python-mode#225]
I have <code>completeopt+=longest,menuone</code> set in my vimrc, but
when I use <C-space> to trigger the rope completion, it automatically fills in one of the available completions. If not reading the main completeopt, perhaps it could have its an option to set completion options for it, such as longest?
##

**Comment by rajaravivarma-r** [comment]
I pushed a fix for this issue [here](https://github.com/python-mode/python-mode/pull/782)

Behavior before patch:
![without patch](https://user-images.githubusercontent.com/1841235/28531544-bf51005e-70b4-11e7-9229-87970be38fd4.gif)

Behavior after patch:
![with patch](https://user-images.githubusercontent.com/1841235/28531565-d80eb17c-70b4-11e7-8125-771983f1099e.gif)
