### ISSUE TITLE
Saving is slow with large numbers of files in .ropeproject

### ISSUE THREAD

**Issue by mstave** [python-mode/python-mode#290]
If you really intend to have a project with lots (tens of thousands) of files, then being slow isn't unexpected.

If you have tens of thousands of files in a subdirectory that you consider unrelated to the python file you are editing, and you are not savvy in the ways of how rope default projects are created, you may wait 30 seconds when you :w and not know why.

After a few hours searching the web failed, I eventually found config.py in .ropreproject which said something about "by default it scans all files in the project", and the lightbulb went on.

I'm not sure if there's a code fix for this, other than to perhaps give a warning with large numbers of files, but a quick mention in the readme may spare others what I went through.

One workaround is to move the .py you want to edit into it's own subdir, and use a new default project.

Another is to somehow specify which subdirs to exclude.
##

**Comment by mcepl** [comment]
If you can reproduce the issue without `python-mode` (i.e., uninstall it completely, and install [rope](https://github.com/python-rope/rope), [ropemode](https://github.com/python-rope/ropemode), and [ropevim](https://github.com/python-rope/ropevim; and I think you will), please file an issue report at `ropevim` issue tracker. Thank you.

But really. Rope and the default configuration is optimized for normal use. Tens of thousand of files is not a normal situation. If you can suggest some way how to make `rope` be more robust (or how to make documentation more clear), I am all ears (and I would gladly welcome a pull request).
