### ISSUE TITLE
Improve documentation for PymodeRopeAutoImport / does not work for "os"

### ISSUE THREAD

**Issue by blueyed** [python-mode/python-mode#325]
I did not manage to get the auto-import feature to work, and the documentation is lacking in that regard.

Shouldn't it work with standard modules, like "os" and "re" always?

I am getting the following error:
"[Pymode] Global name os not found."

**Comment by lsimmons2** [comment]
@klen I'm trying to get autoimports working as I've seen them working in other plugins like `vim-go` where running the auto import command a) adds missing imports, b) removes unused imports, and c) reorders the imports left - all without having to place your cursor over anything specific. 
Is this what `PymodeRopeAutoImport` is supposed to do?
