### ISSUE TITLE
freezes when autocompletion enabled

### ISSUE THREAD

**Issue by sc68cal** [python-mode/python-mode#342]
Tracking down an issue between `0.6.19` and `0.7.0b` and subsequent versions, where MacVim freezes when the autocompletion is initiated.

Debugging suggestions appreciated - I tried following the directions in the README but nothing jumped out at me when I tried the `-u` flag to the debug.vim file.
##

**Comment by diresi** [comment]
Hi, any news on this issue?
I think @zarath is right, strace shows that vim/rope is searching all subdirectories, doing that in $HOME is probably not the best idea ...

**Comment by diresi** [comment]
Ahhh, rope is not only searching $PWD and $PYTHONPATH but also the "source folders", which seem consist of the project root folder and all subdirectories ([PyCore::_find_source_folders](https://github.com/klen/python-mode/blob/develop/pymode/libs2/rope/base/pycore.py#L218)).

I don't know why that is, since the python importer wouldn't do so, therefore I removed these 2 lines, resulting in tremendous performance improvents, at least when the project root is $HOME or something similar with lots of subdirectories/files.
```diff
diff --git a/pymode/libs2/rope/base/pycore.py b/pymode/libs2/rope/base/pycore.py
index 32056a0..f429fc2 100644
--- a/pymode/libs2/rope/base/pycore.py
+++ b/pymode/libs2/rope/base/pycore.py
@@ -215,8 +215,8 @@ class PyCore(object):
             if resource.name.endswith('.py'):
                 result.append(folder)
                 break
-        for resource in folder.get_folders():
-            result.extend(self._find_source_folders(resource))
+        #for resource in folder.get_folders():
+        #    result.extend(self._find_source_folders(resource))
         return result
 
     def run_module(self, resource, args=None, stdin=None, stdout=None):
```

**Comment by scymen** [comment]
Just hit the same issue.
let g:pymode_rope_lookup_project = 0  doesn't work for me.
I've tried many times and tired, I don't know how to solve this.
And now I use davidhalter/jedi-vim  + flake8-vim instead of pymode. Simply works for me.

**Comment by fladd** [comment]
So, given that this issue, which prevents people from actually using vim-mode, has not been fixed in 1.5 years, is it safe to assume that this project is abandoned?

Does anyone know of good alternatives? I see jodi-vim mentioned above. Any other plugins that can take over other parts of python-mode?

**Comment by apollovy** [comment]
https://github.com/scrooloose/syntastic — for checking (using pylint/pep8/pyflakes…)
https://github.com/python-rope/ropevim — rope standalone
https://github.com/Valloric/YouCompleteMe — autocompletion (jedi-based)
https://github.com/jmcantrell/vim-virtualenv — virtualenv support
And python-mode itself — for jumps, for example. You’ve to play with configs and disable in python-mode that is enabled by other tools. And in fact it all works like a charm, almost no issues.

**Comment by johnathanz** [comment]
same issue with python-mode autocomplete freezing on a i7 quadcore Macbook pro 2015. Ended up disabling autocomplete in python-mode, and falling back to YouCompleteMe for completion which I use for everything else.

**Comment by hacpai** [comment]
+1

**Comment by c4traz** [comment]
+1 freezes on "regenerate rope cache" for easily 20 seconds.

**Comment by lianzisong** [comment]
same problem . but it seems better in the vim (takes about 3- 10 secends),  but macvim will hang until i press the command+q. BTW ,I use the Mac OS 10.9.3.  I think if this bug will kill this project .

**Comment by mzhou15** [comment]
Given the fact that auto completion isn't the most attractive feature of python-mode, disabling it works for me. I rely on YouCompleteMe to do the job. I'm on VIM 7.4 and Mac OS 10.10.5. 
```
let g:pymode_rope_completion = 0
let g:pymode_rope_complete_on_dot = 0
```
BTW, if your .vimrc is configured to auto reload view, make sure to delete those saved views, otherwise the new configuration won't take effect on old files you have opened. In my case, deleting all saved views is:
```
rm -rf ~/.vim/view/*
```

**Comment by wkoszek** [comment]
+1 same problem here. I couldn't type:
```
import os

hostname = os. <- would freeze here
```
Repeatable, just like previous guys wrote.

I added:
```
let g:pymode_rope_completion = 0
let g:pymode_rope_complete_on_dot = 0
```

I had nothing to delete with this:

```
rm -rf ~/.vim/view/*
```

It helped. So I typed:
```
hostname = os.system("hostname")
print hostname
```

But my attempt to save caused hanging too.

@diresi is right. Moving the file to a separate directory (instead of junk in my $HOME) I no longer get a hang.

**Comment by piepiper** [comment]
let g:pymode_rope = 0
let g:pymode_rope_lookup_project = 0
let g:pymode_rope_complete_on_dot = 0

works for me. OSX 10.11.3 , vim 7.4.258 .

**Comment by MadWombat** [comment]
Disabling rope is hardly a solution. If it is not used for anything, why not get rid of it altogether? If it is used, this needs fixing.

**Comment by MadWombat** [comment]
The issue still remains after I added
```
let g:pymode_rope = 0
let g:pymode_rope_lookup_project = 0
let g:pymode_rope_complete_on_dot = 0
```

**Comment by amirelemam** [comment]
Setting no permissions to .ropeproject folder worked for me
`chmod 000 ~/.ropeproject`

**Comment by MadWombat** [comment]
Again, all of these "solutions" seem to be about preventing rope from working. Uninstalling rope does wonders for that. I kinda like the autocomplete and other features it provides, I just want it not to freeze.

**Comment by fmv1992** [comment]
Rope completely freezes my system even for simple auto complete `os.pa`[tab] (meaning `os.path`).

**Comment by MadWombat** [comment]
I tried switching to jedi for autocomplete and it seems to freeze in the same manner. For the moment, I uninstalled both rope and jedi and use default autocomplete (not sure if vim-easytags are helping things or not). I kinda miss rope though.

**Comment by fmv1992** [comment]
I tried switching to jedi as well. It does not perform better.
Now I'm using:
https://github.com/Valloric/YouCompleteMe
which is bullet-fast; the only thing is that you have to apply a fix if you use large projects such as numpy:
https://github.com/Valloric/YouCompleteMe/issues/777 
> I just change parameter TIMEOUT_SECONDS = 0.5 to 2 in file with path ~/.vim/YouCompleteMe/python/ycm/client/completion_request.py

But I'm already in love with it (10 minutes trying).

**Comment by james97** [comment]
This happens when I create a python file in a folder with lots of subfolders and files. For small projects, it is ok

**Comment by amirelemam** [comment]
I created my own vimrc file, plugins include vim-commentary, vim-surround,
ctrlp, jedi-vim, syntastic and vim-better-whitespace. I use flake8 on
Syntastic.

It's not as fast as I wished, but faster than before. Syntastic is the
thing, when it is disabled, vim is bullet-fast.

You can check out the whole vimrc file at github.com/amirelemam/dotfiles

2016-11-02 16:44 GMT-02:00 james97 <notifications@github.com>:

**Comment by MadWombat** [comment]
@amirelemam if I am reading this right, your vimrc doesn't have python-mode anywhere. Are you suggesting dropping python-mode altogether as a solution to this issue? :)

**Comment by amirelemam** [comment]
Well, I used python-mode in the beginning, when I started with both vim and
python, 6 months ago. Got this advice on some blog out there.
Those changes that I made have been working so far, but I'll test
python-mode again soon.

What I suggest is to you to try different combinations between the plugins
that I use with and without python-mode, and see what works best for you. :)

2016-11-02 18:10 GMT-02:00 Dmitriy Kropivnitskiy <notifications@github.com>:

**Comment by amirelemam** [comment]
I got a solution (or at least an explanation) about what's going on:
First: filetype indent on (required for python-mode) makes vim half second slower.
Second: pylint and rope take long to process (it's normal) and vim doesn't work asynchronously, so that's the reason why this issue happens.
Solution: move to neovim (vim with enhancements, like running asynchronously) or you have to turn a blind eye to this issue.

**Comment by eevee** [comment]
@amirelemam The recently-released vim 8 supports asynchronous I/O.

**Comment by brycepg** [comment]
I'm interested in making the rope cache generation asynchronous for both neovim and vim. However, anything that requires immediate user feedback like autocompletion probably wouldn't benefit from using jobs and will require another solution.

**Comment by MadWombat** [comment]
YouCompleteMe project seems to be using an external daemon started on vim startup to do completion caching in the background. I wonder if we could adopt a similar approach.

**Comment by amirelemam** [comment]
@eevee Although it does support asynchronous I/O, the plugins were not made for it, so they are not taking advantage of this feature.
@MadWombat There is a plugin for neovim called deoplete, it pretty much does what you intent, check it out at https://github.com/Shougo/deoplete.nvim

**Comment by MadWombat** [comment]
@amirelemam I don't think having everyone switch to neovim is a viable solution :)

**Comment by Qiu-Ye** [comment]
I just hit this issue when completing "os.". I fixed it with:
`let g:pymode_rope_completion = 0`
`let g:pymode_rope_complete_on_dot = 0`

**Comment by fmv1992** [comment]
We are revisiting the entirety of this plugins' functionality.

According to the dicussion in https://github.com/python-mode/python-mode/issues/805 we are giving low priority (for now) for fixing autocompletion issues as we think that there are already dedicated, multi-language plugins that excel at this job.
