### ISSUE TITLE
pymode & python3

### ISSUE THREAD

**Issue by razvanc-r** [python-mode/python-mode#344]
I've seen that you closed the ticket on Python 3 compatibility but I'm getting a a lot of errors when checking the files for syntax & pep8 (that is at save time). Note that in debug mode using vim -u debug.vim this doesn't throw errors because I have vim with python and python3.

PymodeTroubleshooting gives:
# Pymode diagnostic

VIM:704, OS: Linux, multi_byte:1, pymode: 0.7.8b, python: python3
## VIM python paths:

/home/razvan/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint
/home/razvan/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint
/home/razvan/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint
/home/razvan/.vim/bundle/python-mode/pymode/libs3
/home/razvan/.vim/bundle/python-mode/pymode/libs
/home/razvan/.vim/bundle/python-mode
/usr/local/lib/python3.2/dist-packages/pip-1.4.1-py3.2.egg
/usr/local/lib/python3.2/dist-packages/distribute-0.7.3-py3.2.egg
/usr/local/lib/python3.2/dist-packages/setuptools-1.0-py3.2.egg
/usr/lib/python3.2
/usr/lib/python3.2/plat-linux2
/usr/lib/python3.2/lib-dynload
/home/razvan/.local/lib/python3.2/site-packages
/usr/local/lib/python3.2/dist-packages
/usr/lib/python3/dist-packages
_vim_path_
/home/razvan/.vim/bundle/ultisnips/plugin
## Pymode variables:

let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 1
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''

Most of the errors were try except related and print function related in pylint but after trying to fix those I get this error:

```
File "/home/razvan/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pylint/logilab/common/decorators.py", line 30, in _is_generator_function
    return callableobj.func_code.co_flags & 0x20
```

AttributeError - no func_code found for function (I couldn't copy this)

Ok... so I just figured out that pylama_pylint is not Python 3 compatible but if `pymode_lint_checkers` is set to `['pyflakes', 'pep8', 'mccabe']` why does pymode still want to use pylama_pylint?... or is this the right behaviour?

Thanks
##

**Comment by Victor-Savu** [comment]
I am actually havind the same problem:
[Pymode] invalid syntax [pyflakes] due to an `yield from` which is python3

**Comment by thorhunter1** [comment]
Same here, any chance to support pylint3?

**Comment by scolby33** [comment]
I would like to bump this issue with a similar problem: `print('Stuff', file=sys.stderr)` gets marked as invalid syntax by pyflakes unless `print_function` has been imported from `__future__`, even if `g:pymode_python` has been set to `'python3'`.
