### ISSUE TITLE
SyntaxError: Encoding declaration in Unicode string

### ISSUE THREAD

**Issue by mgill25** [python-mode/python-mode#352]
I get this when I try to execute the code using `<leader>r`.  The code runs fine from the command line, this is just the issue with python-mode. 

The issue is fixed when I remove the encoding line `# -*- coding: utf-8 -*-` from the files, although I don't fancy deleting the lines from all the existing files that I have.  ;-)
##

**Comment by yfli** [comment]
Mac, has same issue

**Comment by fmv1992** [comment]
@yfli 
can you give me the output of
`:set fileencoding?`
`:set fileencodings?`
for your vim
and
`$ echo $LC_CTYPE`
`echo $LANG`
for your terminal?

**Comment by yfli** [comment]
@fmv1992 

fileencoding=utf-8
filenecodings=ucs-bom,utf-8,default,latin1

> yfli@YFMBA:python$ echo $LC_CTYPE
UTF-8
yfli@YFMBA:python$ echo $LANG
  

yfli@YFMBA:python$ vi --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  1 2016 19:37:21)
Included patches: 1-898
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv

**Comment by fmv1992** [comment]
@yfli,

I'll investigate this issue. It probably has to do on how vim handles the source code to the executer (?) (I'm not very familiar with this part of the code). I am unsure of the process but googling errors like these points to passing encoding declarators to exec functions and the like in python.

I'll post something back in a couple of days.
