### ISSUE TITLE
don't show line numbers

### ISSUE THREAD

**Issue by jabbalaci** [python-mode/python-mode#356]
I'm new to this vim plugin. When I open a Python source, line numbers are shown automatically. How to switch them off? I don't want to see the line numbers. Thanks.

**Comment by bngsudheer** [comment]
setlocal nonumber
by default would be good. Simpler way to change the setting would be even better!

**Comment by powelleric** [comment]
Actually @nidico's solution did work for me and was not overwritten like what happened to @Leonidas-from-XIV

**Comment by alfonsoIST** [comment]
This is working for me:
```:set nonumber```
