### ISSUE TITLE
Pyflakes invalid syntax

### ISSUE THREAD

**Issue by aciceri** [python-mode/python-mode#359]
I have this code:
`a, b, *c = [1, 2, 3, 4]`
It correctly works, so I have a = 1, b = 2 and c = [3, 4]
If I use:
`pyflakes this_example.py`
I don't have any output, so there are no errors (pyflakes version is 0.7.3).
If I open this_example.py with vim and save the file there are no errors.
But, if I add on purpose an error, then save(it correctly show me the invalid syntax), then delete the error and then resave, it show me a wrong warning.
So, why?

Sorry for my basic english

PS: I'm using the last python-mode version

**Comment by PegasusWang** [comment]
I use `g:pymode_python = 'python3'`, but when I use python3.5 `async def` I get syntax error:
`[Pymode] invalid syntax [pyflakes]`.

Also syntax error when I use rope:
```
Traceback (most recent call last):
  File "/home/wnn/.vim/bundle/python-mode/pymode/libs/rope/base/pyobjectsdef.py", line 189, in _init_source
    ast_node = ast.parse(source_bytes, filename=filename)
  File "/home/wnn/.vim/bundle/python-mode/pymode/libs/rope/base/ast.py", line 21, in parse
    return compile(source, filename, 'exec', _ast.PyCF_ONLY_AST)
  File "app.py", line 23
    async def init(loop):
            ^
SyntaxError: invalid syntax
```
can anyone help ?
