### ISSUE TITLE
vim segfaults on write

### ISSUE THREAD

**Issue by exhuma** [python-mode/python-mode#367]
**Edit**: Also happens on simple `:w`

Two colleagues of mine have told me that thei vim segfaults regularly. But only on save/quit (`:wq`). I tried to find out why, but could not find the culprit. We all have pretty much the same plugins installed.  In any case, we have rules out plugins for a while. After all  I have all those installed as well, and have no seg-faults.

Recently I upgraded python-mode. Since then I get the same problem.

I cannot tell you much more other than it seems to happen _only_ on write+quit.
##

**Comment by dwf** [comment]
I'm seeing a version of this on Vim 7.3.315 on an old, old Fedora Core 14 install (my university department is horribly behind). Specifically, if I run `:PymodeLint` either by writing or manually, nothing seems to go wrong per se, but when I quit I do see 

```
Vim: Caught deadly signal SEGV
Segmentation fault
```

printed on the console.

**Comment by AbeHandler** [comment]
I'm having this problem too.
