### ISSUE TITLE
Error when saving on git cache using fugitive

### ISSUE THREAD

**Issue by santiycr** [python-mode/python-mode#369]
Steps to repro:
- Install [vim-fugitive](https://github.com/tpope/vim-fugitive)
- open a file inside a git repo, edit and save
- type `:Gdiff`
- while focus is on the left pane (the index), save (`:w`)

https://www.evernote.com/shard/s35/sh/ae793721-5ee8-439c-b12d-30c9fb20edf5/b118d351e073dbd0567b3a48e241a8ad/deep/0/o_lwjp.py-(fugitive----Users-sso-SauceLabs-sauce-.git--0-lib)---VIM1.png
##

**Comment by lucc** [comment]
I am also seeing this issue. The error message is 
```
Error detected while processing function pymode#buffer_post_write:
line    8:
E121: Undefined variable: b:pymode_modified
E15: Invalid expression: g:pymode_lint_unmodified || (g:pymode_lint_on_write && b:pymode_modified)
```
The file uses a special fugitive filename: `fugitive:///home/luc/src/music-sync/.git//0/music-sync.py`.
Is there any chance that this can be fixed in pymode or should I look for a drop in fix?
