### ISSUE TITLE
Disable new window auto documentation

### ISSUE THREAD

**Issue by asimos** [python-mode/python-mode#384]
Rookie in vim and python mode :-(
How can I disable auto documentation when writing (not the pop up window with the available options but just the window up of my code with docs).
##

**Comment by pavelwen** [comment]
thanks @bmease

**Comment by zevav** [comment]
@bmease 👍👍👍

**Comment by ipashchenko** [comment]
This (with pymode_rope_complete_on_dot = 0) solved so much annoying problems... Thanks @bmease !

**Comment by naught101** [comment]
If you find the preview window useful, you make it auto close after tab completion is finished with this in out `.vimrc`:

```vim
" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
```

from http://stackoverflow.com/a/3107159/210945

**Comment by mingrammer** [comment]
Thanks @bmease
