### ISSUE TITLE
[Pymode]: error: Pymode requires vim compiled with +python. Most of features will be disabled.

### ISSUE THREAD

**Issue by pengyuan** [python-mode/python-mode#389]
when I open a .py file, some error ocurred:
[Pymode]: error: Pymode requires vim compiled with +python. Most of features will be disabled.
and it seems from D:/Vim/vimfiles/bundle/python-mode/autoload/pymode/virtualenv.vim.
What's wrong with it?  can anybody help me?

I'm using Vim7.4 on Windows7 64bit. I just install vim using the msi-installer instead of compiling it by myself.

**Comment by peterdemin** [comment]
If you are using Debian-based OS, you can install vim with python support by
`sudo apt-get install vim-nox`
