### ISSUE TITLE
syntax turned off after PymodeLintAuto in autocmd

### ISSUE THREAD

**Issue by j5shi** [python-mode/python-mode#396]
I have add below line in my _vimrc which fix PEP8 errors automatically

```
au BufWritePre *.py PymodeLintAuto
```

and after then I found every time I save my python script, the syntax will be turned off and I have to turned it on again manually.

however if I execute :PymodeLintAuto with a shortcut, the syntax will remain turned on.
##

**Comment by moritzschaefer** [comment]
+1
