### ISSUE TITLE
tb when using Python3 venv

### ISSUE THREAD

**Issue by JohnSpeno** [python-mode/python-mode#406]
Using python-mode within a python 3 virtualenv has an issue:

% vim
Error detected while processing /Users/speno/.vimrc:
line  224:
Traceback (most recent call last):
  File "<string>", line 8, in <module>
IOError: [Errno 2] No such file or directory: '/Users/speno/Documents/venvs/
pika/bin/activate_this.py'

It's true. The virtualenvs created using python3's pyvenv command do not have a bin/activate_this.py file.
##

**Comment by illicium** [comment]
+1

**Comment by egoexpress** [comment]
+1
Creating 'Scripts' and touching 'Scripts/activate_this.py' is a workaround but it would be better if python-mode would properly support Python3 venv.

**Comment by relativistic** [comment]
This also seems to be a problem using python 2 if you use Enthought's canopy. Canopy uses a backport of venv: 
https://support.enthought.com/entries/21802240-Use-venv-not-virtualenv-with-Canopy-Python

Using enthought's canopy, I get:

```
[Pymode]: error: [Errno 2] No such file or directory: '/Users/cpl29573/Library/Enthought/Canopy_64bit/User/Scripts/activate_
this.py'
```

**Comment by gilgamezh** [comment]
+1

**Comment by rusnassonov** [comment]
+1

**Comment by yoshiya0503** [comment]
+1

**Comment by toejough** [comment]
+1

**Comment by renodesper** [comment]
+1

**Comment by mapler** [comment]
+1

**Comment by mysteryk** [comment]
please, fix it :)

**Comment by c4traz** [comment]
+1

**Comment by mvasilkov** [comment]
I second this issue very much.

**Comment by alvus** [comment]
+1

**Comment by kuc2477** [comment]
+1

**Comment by tony** [comment]
+1

Or else python 3 is pretty much broken.

**Comment by searene** [comment]
+1

**Comment by tony** [comment]
#609 did the trick for me on Neovim, vim +python3 and also preserves python 2 completion.

**Comment by Alloctag** [comment]
I have also encountered this problem, the main reason for this problem is the python3 venv module to use the absolute path in the virtual environment configuration.
check  `<virtual environments name>/bin/activate,  found `VIRTUAL_ENV`, modify the correct path will be fix this problem. see below:
```
VIRTUAL_ENV = "/ Users /../../<virtual environments name>"
Export VIRTUAL_ENV¬
```

**Comment by yfli** [comment]
I am still have the same issue. Is it fixed or not?
