### ISSUE TITLE
Different textwidth / line length with comments / docstrings

### ISSUE THREAD

**Issue by blueyed** [python-mode/python-mode#461]
From http://legacy.python.org/dev/peps/pep-0008/#maximum-line-length:

> Maximum Line Length
> 
> Limit all lines to a maximum of 79 characters.
> 
> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

I have found a Vimscript on StackOverflow to support this:
http://stackoverflow.com/a/4028423/15690

I think this would be a great fit for this plugin.
What do you think?

(also reported at https://github.com/hynek/vim-python-pep8-indent/issues/31)
##

**Comment by blueyed** [comment]
JFI: three people actually also liked it.
I do not care that much myself: I consider jedi-vim to be my python-mode replacement (without even using its default auto-setup).

**Comment by fmv1992** [comment]
It is indeed a good idea. I'm reopening this issue.
