### ISSUE TITLE
no refactoring performed

### ISSUE THREAD

**Issue by kraxli** [python-mode/python-mode#465]
Hi,

I've just started to use your great plugin. First of all thanks for providing and maintaining it!! I tried to refactor an object in a very simple script from emp3 to xxx by setting the cursor on in an hitting my refactoring-key-combination.  I can provide a new name but no refactoring is done after that. 
Would you have a hint what I am doing wrong? 

Below you find information out-putted by pymode, my working environment and my vimrc file setting on pymode-rope. 

**Pymode output:**
[Pymode]  Rename var/function/method/class.
[Pymode] Renaming method/variable. New name: [emp3] > xxx

[Pymode]  Rename var/function/method/class.
[Pymode] Calculate changes ... - done 100%
[Pymode] Choose what to do:
1. perform
2. preview

[Pymode] Apply changes ... - done None%    

**I am working on** Windows7 with gvim 32 bit (compiled by Haroogan: https://bitbucket.org/Haroogan/vim-for-windows/src) and python 2.7 (pythonxy).  

My pymode-rope settings in my **vimrc file**:
"""""""""""""""""""""
" python-mode - rope
"""""""""""""""""""""  
let g:pymode_rope = 1

" 4.1 Rope-Completion
" By default you can use <Ctrl-Space> for autocompletion. The first entry will be automatically selected and you can press <Return> to insert the entry in your code. <C-X><C-O> and <C-P>/<C-N> works too.  
" Turn on code completion support in the plugin  
    let g:pymode_rope_completion = 0
" Turn on autocompletion when typing a period
    let g:pymode_rope_complete_on_dot = 0
" Keymap for autocomplete  
    let g:pymode_rope_completion_bind = '<C-Space>'
" Extended autocompletion (rope could complete objects which have not been imported) from project  
    let g:pymode_rope_autoimport = 0
" Load modules to autoimport by default       _'g:pymode_rope_autoimport_modules'_
    let g:pymode_rope_autoimport_modules = ['os', 'shutil', 'datetime']
" Offer to unresolved import object after completion.
    let g:pymode_rope_autoimport_import_after_complete = 0   

" go to and refactoring  " <leader>d 
 let g:pymode_rope_goto_definition_bind = '<C-cg' 
" Keymap for rename method/function/class/variables under cursor " '<C-c>rr' 
 let g:pymode_rope_rename_bind = '<leader>r'  
##

**Comment by mcepl** [comment]
If you can reproduce the issue without `python-mode` (i.e., uninstall it completely, and install [rope](https://github.com/python-rope/rope), [ropemode](https://github.com/python-rope/ropemode), and [ropevim](https://github.com/python-rope/ropevim), please file an issue report at `ropevim` issue tracker. Thank you.

**Comment by kraxli** [comment]
Hi Matej,

thanks for your reply! I will definitely try it out asap I'll find the time
to test it. Currently I am pretty happy with jedi.

I'll get back to you.

Thanks,
David

**Comment by mcepl** [comment]
> Currently I am pretty happy with jedi.

Yes, but doesn't do much any refactoring, does it? (except for renaming) I heard from many people that it has better completion though.

**Comment by kraxli** [comment]
absolutely, that is why I want to give rope another try :-)

**Comment by dset0x** [comment]
@kraxli Could you checkout branch [dset0x/refactoring-calls](https://github.com/dset0x/python-mode/tree/refactoring-calls) and give this another try?

Alternatively, please provide a specific example (entire file you are refactoring and what actions you do).

**Comment by kraxli** [comment]
sorry for my late replay. I checked out your branch and did the following
without success. Am I doing something wrong?

[image: Inline image 1]

**Comment by kraxli** [comment]
with the newest ropevim (https://github.com/python-rope/ropevim) the issue
disappeared :-)
