### ISSUE TITLE
red line in the middle of the terminal

### ISSUE THREAD

**Issue by sandeepbalouria** [python-mode/python-mode#466]
Hi
 i am getting a red line in the middle of the terminal when  i open any py file in vi .
using pymod everthing else is work fine.

Any help would be appriciated.

Thanks!
##

**Comment by StasMerzlyakov** [comment]
Thank you too

**Comment by mahsa-kohandel** [comment]
Thanks. Adding this line to .vimrc file worked. 
let g:pymode_options_colorcolumn = 0

**Comment by danuker** [comment]
If you still want >80 chars highlights, but only on the offending characters (without the thick vertical column), check out [John Crepezzi's way in this video](https://youtu.be/BhwtnCaFTFk?t=452):

```vim
let g:pymode_options_colorcolumn = 0
au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
```
