### ISSUE TITLE
can't turn off high light on column 80

### ISSUE THREAD

**Issue by timfeirg** [python-mode/python-mode#473]
python mode automatically set highlight on 80 column, I can't seem to find a way to disable it, pylint report errors if I ever wrote a line longer than 79 so I don't need this column highlight

**Comment by scirelli** [comment]
This is not working for me.  Setting
`let g:pymode_options_colorcolumn = 0`
does nothing, that red line is still there.

**Comment by joergsch** [comment]
`set cc=`
should eliminate the red line
