### ISSUE TITLE
Python mode and virtual machines

### ISSUE THREAD

**Issue by seanh** [python-mode/python-mode#474]
I wonder if anyone has got python-mode working in the following scenario:

I'm using a Vagrant/VirtualBox virtual machine for development, the Python web app that I'm working on is installed inside the VM. I don't want to install terminal vim inside the VM and use it, I'd rather use GVim running on my host machine.

I can share the source code files of the app between the VM and host machine, and then edit them using GVim running on the host machine - fine.

But certain python-mode features won't work when working like this, for example autocomplete and linting. These features need to be aware of the virtualenv that the code belongs to.

So I need to figure out a way to activate a virtualenv that's inside a vm, in my GVim running on the host machine.

Is this possible?
##

**Comment by ir4y** [comment]
Same issue for docker.
Is posible to use python interpreter from docker container for autocomplete and linting ?

**Comment by wklm** [comment]
+1
