### ISSUE TITLE
:PymodeLintAuto failed to reformat

### ISSUE THREAD

**Issue by lookforit** [python-mode/python-mode#477]
Hi,
The command `:PymodeLintAuto` does nothing for reformatting code lines.
But the command `:PymodeLint` works normally to generate the error and warning items.

What's wrong?
`:PymodeVersion` result is :
`Pymode version: 0.8.1 interpreter: python lint: 1 rope: 1`

VIM version is `7.4.334`
##

**Comment by pinggit** [comment]
I see the issue. can we reopen it?

**Comment by diraol** [comment]
Sure we can @pinggit. I saw a similar issue too. I saw, once, similar behavior and restarting vim made it work (only one time, then I had to restart vim again).

But I am without spare time to dedicate to the project to fix it, so contributions are very welcome!
