### ISSUE TITLE
Suggestion: Add colorcolumn setting for user

### ISSUE THREAD

**Issue by linlinlinlin** [python-mode/python-mode#484]
In the new version of python-mode already provide `pymode_options_colorcolumn` for user.
Is it possible also provide color setting?
Because if I want to set `let &colorcolumn=join(range(81,999),",")`
After 81 will full of red. 
##

**Comment by jmorsecode** [comment]
I'm also curious if there's a way to customize the color of the PEP8 line width column.  Using a solarized theme especially, the red is way too distracting.
