### ISSUE TITLE
Syntax highlighting fails when file not opened at line 1

### ISSUE THREAD

**Issue by pierz** [python-mode/python-mode#491]
I have vim setup so it jumps to the last line I was working on when I open a file - using command: ' + " i.e:
http://stackoverflow.com/questions/774560/in-vim-how-do-i-get-a-file-to-open-at-the-same-line-number-i-closed-it-at-last
But when I do this the syntax highlighting fails to work properly in python-mode. Without python-mode activated the normal vim Python syntax highlighting works fine when using this approach.
##

**Comment by dset0x** [comment]
@pierz 

I'm using this instead and I have never had this problem:
```vim
  autocmd BufReadPost *
        \ if ! exists("g:leave_my_cursor_position_alone") |
        \     if line("'\"") > 0 && line ("'\"") <= line("$") |
        \         exe "normal g'\"" |
        \     endif |
        \ endif
```

Could you try with a new `python-mode` version with both methods?
