### ISSUE TITLE
Docs say to use $HOME/pylint.rc but $HOME/.pylintrc is what works

### ISSUE THREAD

**Issue by drennalls** [python-mode/python-mode#507]
`:help pymode-lint` has this regarding pylintrc customization..

```
      Pylint options (ex. disable messages) may be defined in $HOME/pylint.rc
      See pylint documentation.
```

..however $HOME/pylint.rc seems to be completely ignored and I had to instead copy my custom pylintrc to $HOME/.pylintrc instead.
##

**Comment by mattamizer** [comment]
+1. This was driving me insane for like a week.
