### ISSUE TITLE
create .ropeproject in root of my git repo

### ISSUE THREAD

**Issue by aliva** [python-mode/python-mode#515]
currently if there is no `.ropeproject`, pymode automatically generates `.ropeproject` in current path (`:pwd`), I think if I'm editing a file which is inside a git repo the `.ropeproject` should be created on the root directory of my git project (whether my current path in a subdirectory of git repo or in an unrelated directory)
##

**Comment by mcepl** [comment]
We are working on this [upstream](https://github.com/python-rope/ropemode/pull/13) in `ropemode`.

**Comment by dset0x** [comment]
@aliva Until `ropemode` amends this, you can try `airblade/vim-rooter`.
Set `let g:rooter_use_lcd = 1` if you use multiple projects per session.
