### ISSUE TITLE
Pymode gets crash when checking default function arguments.

### ISSUE THREAD

**Issue by gnaggnoyil** [python-mode/python-mode#526]
Instead of reporting a syntax error, when the text contains a syntax error where a function has a default arguments that are not the last of the function arguments, pymode in vim simply gets crashed and results a vim "E121: undefined variable: null" error.

For example, I have this piece of Python 3 code in vim:

``` Python
def aaa(arg1, arg2 = 1, arg3):
    print(1)

aaa(1,2,3)
```

Then I run pymode in vim, and pymode crashed with this error:

```
[Pymode] Code checking is running ...
处理 function pymode#buffer_post_write..pymode#lint#check 时发生错误:
第   11 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gnaggnoyil/.vim/bundle/python-mode/pymode/lint.py", line 71, in co
de_check
    env.run('g:PymodeLocList.current().extend', [e._info for e in errors])
  File "/home/gnaggnoyil/.vim/bundle/python-mode/pymode/environment.py", line 18
6, in run
    self.prepare_value(a) for a in args
vim.error: Vim(call):E121: 未定义的变量: null
处理 function pymode#buffer_post_write 时发生错误:
第   10 行:
E171: 缺少 :endif
```
##

**Comment by rphlypo** [comment]
see Issue #452

**Comment by productivememberofsociety666** [comment]
+1, quite annoying.

**Comment by tenor27** [comment]
Can confirm that this error shows up when calling a function and specifying argument names for some arguments and excluding them for others. For example:
     foo(8,9) and foo(x=8, y=9)
will not result in this error from PymodeLint. However,
    foo(x=8, 9) and foo(8, y=9)
will result in the error.
