### ISSUE TITLE
Use flake8 instead of pyflakes

### ISSUE THREAD

**Issue by klen** [python-mode/python-mode#53]
Because its more powerfull tool (pyflakes, pep8, mccabe).

Also maybe set it as default linter instead a pylint?

**Comment by shaypal5** [comment]
Sorry to wake this from the dead, but I'd argue there's a meaningful difference between operating `pyflakes` and `pep8` side-by-side and operating `pyflakes` - the latter allows you to configure `pyflakes` to ignore certain warnings for a certain context (a specific statement, scope or module), which is much stronger and is an almost mandatory ability; I want to be sure that when I ignore a statement for an unused import warning, I don't lose the ability to get warnings on other errors!
