### ISSUE TITLE
Inappropriate Using of Location Winodw Instead of Quickfix Window

### ISSUE THREAD

**Issue by j5shi** [python-mode/python-mode#540]
It is clearly stated in the help doc that python-mode uses **quickfix** windows to display errors found:

> Auto open cwindow (quickfix) if any errors have been found...

But what I see is that pymode uses **Location** windows instead, they are different windows.

![incorrectlocationlist](https://cloud.githubusercontent.com/assets/6829121/6541277/3e96bcfc-c502-11e4-90ad-7e76fa64a671.png)
##

**Comment by zoresvit** [comment]
+1 on this. `Location` window is different and doesn't allow easy navigation between errors like `quickfix` window does.

Response on this would be highly appreciated.

Thanks.

**Comment by iugrina** [comment]
+1

**Comment by zoresvit** [comment]
Unfortunately it seems like this project lacks support now. Even Travis CI reports failling build :(

**Comment by alexdunn** [comment]
This could definitely use a fix.

**Comment by lyager** [comment]
It seems that moving towards LocList was done on purpose. I've reverted the commit in my clone at: https://github.com/lyager/python-mode and created the above merge request if @klen finds it appropriate.

**Comment by vsbuffalo** [comment]
+1 — this should be a quickfix window so :cp and :cn can be used to navigate the items — any updates on this?
