### ISSUE TITLE
Bug somewhere around folding

### ISSUE THREAD

**Issue by bestxolodec** [python-mode/python-mode#565]
I  have been  constantly suffering  from vim slowness while editing python files. 
Today things became even worse than ever and i decided to figure what is wrong. 
The main problem is that typing  any character (regardless of its indent) causes vim to freeze for a while. 
I am aware of a rope problem, that also freezes vim (issue #525) and i switched to 

```
let g:pymode_rope = 0
```

It helped a little, but not much.
So i launched profiling and get terrifying results  ([here is the full pofile](https://gist.github.com/bestxolodec/7dda8f701d13bcb6e1f1#file-profile-log-L1039) ): 

```
profile.log-FUNCTION  pymode#folding#expr()
profile.log-Called 17592 times
profile.log:Total time:  12.632305
```

There was the only action a performed when running profiling: typed `print(list`. It took me more that 7 seconds to see this text on the screen :-( .
Now i am happy, i finally figured it out and switched off folding:

```
let g:pymode_folding = 0
```

Everything is working fine now and i am able to type code as fast as i can produce keystroke :-) .
Is there any method to eliminate such a behavior ? 

And the second problems with folding was posted in the [ycm issues](https://github.com/Valloric/YouCompleteMe/issues/1451). Is there any way to cure such a disease ?  
##

**Comment by olsoneric** [comment]
Thank you - disabling folding for now helped stop a long hang I was getting.
