### ISSUE TITLE
name 'rope' is not defined

### ISSUE THREAD

**Issue by dkrasner** [python-mode/python-mode#575]
Error flashes on first vim write - it's disappears within a second and then no more errors, but but pymode is showing errors and warnings: 0, i.e. no longer working. I can see that the last line says 

``` bash
name 'rope' is not defined
```

Trying either the 'develop' or 'master' branches (as suggested in [this](https://github.com/klen/python-mode/issues/437) issue) didn't help. 

Rope is definitely installed. 

``` python
In [3]: rope.VERSION
Out[3]: '0.10.2'`
```

I tried loading vim with only python-mode enabled (using debug.vim) to reproduce the error but the same as above happens. Error flashes then disappears and pymode is not functioning. 

here is the output from  running :PymodeTroubleshooting 

``` bash
Pymode diagnostic
===================
VIM:703, OS: Darwin, multi_byte:1, pymode: 0.8.1, pymode-python: python


+python: 1
+python3: 0

/Users/danielkrasner/.vim/bundle/python-mode/pymode/libs2
/Users/danielkrasner/.vim/bundle/python-mode/pymode/libs
/Users/danielkrasner/.vim/bundle/python-mode
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/pdbpp-0.7.2-py2.7.egg
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/wmctrl-0.1-py2.7.egg
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/fancycompleter-0.4-py2.7.egg
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/pyrepl-0.8.4-py2.7.egg
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.9.8-py2.7-macosx-10.5-x86_64.egg
/Users/danielkrasner/src/flanker
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/progressbar2-3.0.0-py2.7.egg
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/rope
/Users/danielkrasner/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_ppylint
/Users/danielkrasner/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_pyflakes
/Users/danielkrasner/anaconda/lib/python27.zip
/Users/danielkrasner/anaconda/lib/python2.7
/Users/danielkrasner/anaconda/lib/python2.7/plat-darwin
/Users/danielkrasner/anaconda/lib/python2.7/plat-mac
/Users/danielkrasner/anaconda/lib/python2.7/plat-mac/lib-scriptpackages
/Users/danielkrasner/anaconda/Extras/lib/python
/Users/danielkrasner/anaconda/lib/python2.7/lib-tk
/Users/danielkrasner/anaconda/lib/python2.7/lib-old
/Users/danielkrasner/anaconda/lib/python2.7/lib-dynload
/Users/danielkrasner/anaconda/lib/python2.7/site-packages
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/PIL
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/aeosa
/Users/danielkrasner/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 1
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''
```

No vim related changes or updates have occurred lately, but I did upgrade to the latest [conda python distribution](http://continuum.io/downloads). 

Any ideas? thanks!
##

**Comment by awisse** [comment]
Same here. The full message can be revealed by the command :messages (see below).

The error can be traced to python 2.7.10 (in /usr/local/bin for me). When setting the PATH so as to find the Apple Python (2.7.6 on Yosemite), there is no error. It would be nice to be able to tell vim to use the /usr/bin/python.

    Error detected while processing /Users/wisse/.vim/bundle/python-mode/autoload/py
    mode/rope.vim:
    line    3:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/wisse/.vim/bundle/python-mode/pymode/rope.py", line 10, in <modul
    e>
        from rope.base import project, libutils, exceptions, change, worder # noqa
      File "/Users/wisse/.vim/bundle/python-mode/pymode/libs2/rope/base/project.py",
     line 8, in <module>
        from rope.base import exceptions, taskhandle, prefs, history, pycore, utils
      File "/Users/wisse/.vim/bundle/python-mode/pymode/libs2/rope/base/pycore.py", 
    line 6, in <module>
        import rope.base.oi.doa
      File "/Users/wisse/.vim/bundle/python-mode/pymode/libs2/rope/base/oi/doa.py", 
    line 7, in <module>
        import tempfile
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7
    /lib/python2.7/tempfile.py", line 32, in <module>
        import io as _io
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7
    /lib/python2.7/io.py", line 51, in <module>
        import _io
    ImportError: dlopen(/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/
    Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_Rep
    laceException
      Referenced from: /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/V
    ersions/2.7/lib/python2.7/lib-dynload/_io.so
      Expected in: flat namespace
     in /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib
    /python2.7/lib-dynload/_io.so
    Error detected while processing function pymode#rope#show_doc:
    line    3:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
