### ISSUE TITLE
cannot set g:pymode_breakpoint_cmd in .vimrc

### ISSUE THREAD

**Issue by coomteng** [python-mode/python-mode#582]
Hi, 

the g:pymode_breakpoint_cmd will be overwritten in breakpoint.vim.

You may need to add
else
    return
in line 13 of  python-mode/autoload/pymode/breakpoint.vim.

Best wishes,
Ting
##

**Comment by ptzz** [comment]
+1

**Comment by belugame** [comment]
+1
