### ISSUE TITLE
multiple descriptors don't get into fold

### ISSUE THREAD

**Issue by HuStmpHrrr** [python-mode/python-mode#587]
to illustrate the issue, please see following example:

in a piece of my code:

``` python
    @show_effect
    @field_diff
    def do_sync(self, line):
        ...
```

and if i fold it, it comes to this:

```
    @show_effect
    def do_sync(self, line): ------------------------------------------------------- 29---
```

is that intended behavior that fold only collapses one descriptor? wouldn't it be nice if collapes none or all?
##

**Comment by knight-erraunt** [comment]
They are called decorators and not descriptors I believe. There was later an issues - #675 , I created two pull requests, comment on them if you have preference towards one behavior or the other (none or all).

**Comment by knight-erraunt** [comment]
https://github.com/klen/python-mode/issues/675
