### ISSUE TITLE
importError: No module named site

### ISSUE THREAD

**Issue by jikk** [python-mode/python-mode#589]
Hi, I installed _python-mode_ as a part of spf13-vim. But, it prevents vim editor from opening any python files. It simply fails with the following message. 

```
importError: No module named site
```

Do you have any idea how can I solve it?
##

**Comment by grmarcil** [comment]
@jikk I just encountered this same problem immediately after installing python-mode. I found [these instructions](http://wizardmode.com/2012/07/mountain-lion-and-homebrew-vim-importerror-no-module-named-site/) which fixed my problem immediately. Seems to be that OS X updates at some point(s) did not play particularly well with python environments relative to homebrew installed vim. Note the article refers to macvim but worked fine for my (homebrew managed) terminal vim.

**Comment by jikk** [comment]
@grmarcil  thanks a lot! I will try it right away!
