### ISSUE TITLE
Project is unmaintained?

### ISSUE THREAD

**Issue by ccope** [python-mode/python-mode#593]
It appears that no development has happened in this repo for ~7 months. @klen, do you plan on continuing to manage this project? Are there fundamental issues?
##

**Comment by mpyatishev** [comment]
+1
Maybe anyone can take project in his arms?

**Comment by jikk** [comment]
+1

**Comment by K-Guan** [comment]
Really? However this project is perfect.

**Comment by klen** [comment]
:+1:

**Comment by knight-erraunt** [comment]
+1

**Comment by sdlarsen** [comment]
+1
