### ISSUE TITLE
Disable whole plugin and only enable syntax check?

### ISSUE THREAD

**Issue by esn89** [python-mode/python-mode#610]
Is that possible?

I have first set let g:pymode = 0 and then all the lines after that I did:
let g:pymode_syntax = 1 and that seems to not work.

At the moment, I can skip the docs functionality I would just like the syntax to be checked on save without all the extra features, is that achievable?

I would use syntastic, but syntastic's python check is buggy and that is what made me come here

Thanks
##

**Comment by judgedreads** [comment]
`g:pymode=0` will disable everything (including syntax checking) so it should be set to 1. You need to read the docs on github (https://github.com/klen/python-mode/blob/develop/doc/pymode.txt) or in vim (`:help pymode`) and disable individual features that you don't want. That said, these options will probably suffice:
```
let g:pymode_virtualenv = 0
let g:pymode_breakpoint = 0
let g:pymode_folding = 0
let g:pymode_rope = 0let g:pymode_run = 0
let g:pymode_options_colorcolumn = 0
let g:pymode_lint_on_write = 1
"set the complexity check high to essentially disable it
let g:pymode_lint_options_mccabe = {'complexity': 30}
```
