### ISSUE TITLE
ImportError: No module named pymode.virtualenv

### ISSUE THREAD

**Issue by iTeam91** [python-mode/python-mode#613]
I opened the file

``` terminal```
$ vim ~/.vim/bundle/python-mode/debug.vim
```

and then typed it:

```
:PymodeTroubleshooting
```

As a result i received this message:

```
Error detected while processing /Users/iTeam/dotvim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pymode.virtualenv
```

How can I fix it?
##

**Comment by artyomboyko** [comment]
Same issue

**Comment by mistakeking** [comment]
here the same
