### ISSUE TITLE
py-mode became slow in zsh, in mac OX EI Capitan

### ISSUE THREAD

**Issue by fortyMiles** [python-mode/python-mode#615]
I found when after using pymode sometimes, the zsh terminal will became **very** slow. The _completion_, _movement_, and others became slow. But when I change _zsh_ to _bash_, the pymode function became normal. 

Anyone has this problem too? 

Thanks :)
##

**Comment by alexlafroscia** [comment]
I'm using `zsh` as my shell but haven't seen any performance issues with `python-mode`

**Comment by outcoldman** [comment]
@fortyMiles I had the same perf issue, I am on zsh + El Capitan. Did not know if this was something zsh/OSX 10.11 specific, so I played with all settings pymode has to figure it out what is slow. Disabling breakpoint helped me (rope also disabled long time ago)

```
let g:pymode_breakpoint = 0
```
