### ISSUE TITLE
Using Python3/Anaconda with Pymode

### ISSUE THREAD

**Issue by CleverProgrammer** [python-mode/python-mode#617]
# How can I use pymode with Anaconda?

**Here is what I tried:** 
1. I added `let g:pymode_python = 'python3'` in my vimrc and saved it with `:w<cr>`
2. `source ~/.vimrc` in my .py file
3. `PymodeRun` in my .py file 

However, it still used **python2.7** to execute my .py script. I want it to use my python3 install through anaconda but if it cannot do that, I will still be happy if I can get it to use **python3**.

It could not understand my `@functools.lru_cache(None)` in my .py file. When I ran it from outside **vim** simply using `python foo.py` my script worked just fine.

Any help would be greatly appreciated,
Thanks!
##

**Comment by stanleyjs** [comment]
I also have this issue.  I have tried numerous paths to fixing this, including editing my environment variables $PYTHONPATH, etc

here is the output from mvim
```
"test.py" [New File]
Error detected while processing function pymode#init:
line    2:
E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.5/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.
line    3:
E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.5/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.
line    4:
E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.5/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.
Error detected while processing /Users/jaystanley/.vim/bundle/python-mode/autoload/pymode/virtualenv.
vim:
line    3:
E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.5/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.
Error detected while processing function pymode#breakpoint#init:
line   27:
E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.5/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.
Error detected while processing /Users/jaystanley/.vim/bundle/python-mode/ftplugin/python/pymode.vim:

line   25:
E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.5/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.     
```

Here is my ~/.vimrc (it is a mess i know)
'''
let $PYTHONHOME="/Users/jaystanley/anaconda/bin/"
let $PYTHONPATH="/Users/jaystanley/anaconda/bin/"

let g:pymode_python = 'python3'
let g:pymode_paths = "/Users/jaystanley/anaconda/bin/"
let g:pymode_lint = 0


set nocompatible              
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'jelera/vim-javascript-syntax'
Plugin 'pangloss/vim-javascript'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'othree/html5.vim'

let g:used_javascript_libs = 'jquery,backbone,underscore,angularjs,jasmine,chai'

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


syntax enable
set background=dark
colorscheme solarized
cmap w!! %!sudo tee > /dev/null

" Pathogen load

call pathogen#infect()
call pathogen#helptags()

set modeline
set tabstop=8
set expandtab
set softtabstop=4
set shiftwidth=4
filetype indent on
syntax on
'''

and here is my output from troubleshooting

```
Error detected while processing function pymode#troubleshooting#test:
line   50:
E837: This Vim cannot execute :py3 after using :python
E263: Sorry, this command is disabled, the Python library could not be loaded.
line   51:
E121: Undefined variable: output
E116: Invalid arguments for function append    
```

```
Pymode diagnostic
===================
VIM:704, OS: Darwin, multi_byte:1, pymode: 0.8.1, pymode-python: python3


+python: 1
+python3: 0

VIM python paths:
-----------------

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 0
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = '/Users/jaystanley/anaconda/bin/'
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 1
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''
```

**Comment by Alechan** [comment]
```
" Pymode
" 1) Set the python as python 3
let g:pymode_python = "python3"
" 2) Set the 'virtualenv' as my anaconda path. It's not a virtualenv per sé but i don't use the system python path.
let g:pymode_virtualenv_path = "/home/<user>/anaconda3"
```

It worked for almost every script. One gave me an import conflict with configparser. By running PymodeRun instead of a normal python call, it's importing pymode's configparser instead of my system's configparser. I don't know if this is fixable.
