### ISSUE TITLE
PEP8 option seems doesn't work

### ISSUE THREAD

**Issue by NoAnyLove** [python-mode/python-mode#622]
According to 3.1 Set code checkers options, pep8 options can be set as (there is an redundant `)` inside documentation)

```
let g:pymode_lint_options_pep8 =
        \ {'max_line_length': g:pymode_options_max_line_length})
```

I tried the configuration below,

```
let g:pymode_options_max_line_length = 120
let g:pymode_lint_options_pep8 =
        \ {'max_line_length': g:pymode_options_max_line_length}
```

but it doesn't work.

I also tried,

```
let g:pymode_lint_options_pep8 =
        \ {'select': 'E,W'}
```

but still doesn't work.
##

**Comment by krader1961** [comment]
On Fri, Nov 20, 2015 at 10:44 PM, NoAnyLove <notifications@github.com>
wrote:

> According to 3.1 Set code checkers options, pep8 options can be set as
> (there is an redundant ) inside documentation)
>
> let g:pymode_lint_options_pep8 =
>         \ {'max_line_length': g:pymode_options_max_line_length})
>
> I tried the configuration below,
>
> let g:pymode_options_max_line_length = 120
> let g:pymode_lint_options_pep8 =
>         \ {'max_line_length': g:pymode_options_max_line_length}
>
> but it doesn't work.
>

Works for me.


> I also tried,
>
> let g:pymode_lint_options_pep8 =
>         \ {'select': 'E,W'}
>
> but still doesn't work.
>

This doesn't have any effect because showing all errors and warnings is the
default. Try ignoring specific errors; e.g.,

    'ignore': 'E301,E302'

That works for me.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by NoAnyLove** [comment]
That's weird, the configuration below, doesn't work for me. I tried disable other plugins, but it's still doesn't work.

```
let g:pymode_options_max_line_length = 120
let g:pymode_lint_options_pep8 =
         \ {'max_line_length': g:pymode_options_max_line_length}
```

I still get errors showing `test.py|8 col 80 C| E501 line too long (100 > 79 characters) [pep8]`

I use `let g:pymode_lint_options_pep8 = {'select': 'E,W'}` because I want to enable E226, but select 'E,W' seems doesn't work. I also tried `{'select': 'E226'}`, it doesn't make any difference.

Besides, the `let g:pymode_lint_select = "E,W"` setting can effect the behavior of autopep8, but doesn't affect pep8.

**Comment by kartynnik** [comment]
let g:pymode_options_max_line_length = 120
I also have recently faced the issue that this particular option stopped working (this was like not more than several weeks ago - I'm living with NeoBundle autoupdates - and worked before).

**Comment by kartynnik** [comment]
Actually, in pymode/__init__.py, I see:
     21         max_line_length = 79
Why not vim.eval('g:pymode_lint_options_max_line_length')?

**Comment by kartynnik** [comment]
The previous comment related to `:PymodeLintAuto`; for `:PymodeLint`, I believe the `g:pymode_options_max_line_length` value should be passed to `parse_options` in `pymode/lint.py:code_check`?

**Comment by kartynnik** [comment]
This line inserted at `pymode/lint.py:29` (after `env.debug(options)`) solves the problem:
`options.linter_params['pep8'] = {'max_line_length': int(env.var('g:pymode_options_max_line_length'))}`
May not be the most elegant/right way to do this, though.

**Comment by ethervoid** [comment]
What about this issue? I'm facing the same problems :(

**Comment by peikk0** [comment]
Same problem here

**Comment by soulomoon** [comment]
Same problem here +1
