### ISSUE TITLE
freezes after matplotlib show() function 

### ISSUE THREAD

**Issue by elchinot7** [python-mode/python-mode#632]
After running (with `<leader> r` in python-mode ) a simple code that creates and shows matplotlib plots by using the ´pyplot.show()´ function, the plot is displayed correctly but vim crashes after trying to close the plot window. 
Here a simple example that produces the issue:

``` python
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)

t = np.linspace(0, 1, 10)
ax.plot(t, 2*t)
plt.show()
```

**Comment by Jeybla** [comment]
I'm currently working a lot with matplotlib. Is there a possible workaround?
