### ISSUE TITLE
syntastic.txt pops up when :help pymode is executed

### ISSUE THREAD

**Issue by searene** [python-mode/python-mode#636]
I installed both `syntastic` and `pymode` through `Vundle`, when I run `:help pymode` in vim, `syntastic.txt` pops up and the following text is displayed:

> 7.8 python-mode                                             _syntastic-pymode_
> 
> Syntastic can be used along with the "python-mode" Vim plugin (see
> https://github.com/klen/python-mode). However, they both run syntax checks by
> default when you save buffers to disk, and this is probably not what you want.
> To avoid both plugins opening error windows, you can either set passive mode
> for python in syntastic (see |'syntastic_mode_map'|), or disable lint checks in
> "python-mode", by setting |pymode_lint_on_write| to 0. E.g.: >
>     let g:pymode_lint_on_write = 0

It seems to be part of syntastic documentation that contains `pymode`. Is it a problem of pymode or vim? How to deal with it?

**Comment by searene** [comment]
It's fixed after upgrading to version 0.8.1

**Comment by jarandaf** [comment]
I'm experiencing the same issue:

- Syntastic version is 3.7.0-134
- Python-mode version is 0.8.1

**Comment by jloehel** [comment]
**vim:** Vi IMproved 8.0 (2016 Sep 12)
**syntastic:** scrooloose/syntastic@9041bc7
**python-mode:** python-mode/python-mode@51c66fa

Configuration:
```
let g:syntastic_mode_map = { 'passive_filetypes': ['python'] }
```

**Case 1:** No buffer opened or  a buffer with a non-python file
`:help pymode` opens `syntastic-pymode`.
`:help pymode.txt` E149: pymode.txt does not exist

**Case 2:** A opened buffer with a python file
`:help pymode` opens pymode-faq. 
`:help pymode.txt` works correctly :1st_place_medal: 

@searene I think this should be documented or fixed.

**Comment by diraol** [comment]
`pyhton-mode` plugin is only loaded when you are handling a python file, this is why this happens. There is no `fix` needed here. You won't have python-mode features if it isn't loaded. And we don't load `python-mode` outside of a `python environment` to keep vim lean.

By the way, that `syntastic` config has nothing to do with `python-mode`, it is a `syntastic` config.

**Comment by jloehel** [comment]
> `pyhton-mode` plugin is only loaded when you are handling a python file, this is why this happens. There is no `fix` needed here. You won't have python-mode features if it isn't loaded. And we don't load `python-mode` outside of a `python environment` to keep vim lean.
> 
> By the way, that `syntastic` config has nothing to do with `python-mode`, it is a `syntastic` config.

But why is it not documented? If I read this: https://github.com/python-mode/python-mode#documentation, I expect it works always like this.
