### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by FedericoCeratto** [python-mode/python-mode#639]
Hello and thank you for developing python-mode. Having the tool packaged in Debian (and derivatives e.g. Ubuntu) would be nice.

Python-mode embeds many 3rd party libraries that should not be part of the package.
Are the libraries patched for Pymode?
If not, would Pymode work if the libraries were provided from different locations?
Are there strict requirements for the versions of such libraries?

Debian packaging request: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807961
Thank you.

**Comment by diraol** [comment]
Hi @FedericoCeratto python-mode has changed a lot since your suggestion and we have drastically reduced the 'embeding' of third party libraries (they are now submodules), but still there are some work to do about it.

Would you help us decrease such 'hardcoded' dependencies?
