### ISSUE TITLE
An error because of lint.vim / Python 3

### ISSUE THREAD

**Issue by Asher256** [python-mode/python-mode#641]
Hi,

Thank you for this excellent vim plugin!

I recently had an issue with python-mode and Python 3:
1. When i open vim in a Python 2 virtualenv, python-mode works well.
2. But when i open vim in a Python 3 virtualenv, i have the error below:

```
Error detected while processing /home/asher/.vim/bundle/python-mode.vim/autoload/py
mode/lint.vim:
line    1:
Traceback (most recent call last):

Error detected while processing /home/asher/.vim/bundle/python-mode.vim/autoload/py
mode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/asher/.vim/bundle/python-mode.vim/autoload/py
mode/lint.vim:
line    1:
  File "/home/asher/.vim/bundle/python-mode.vim/pymode/lint.py", line 9, in <module
>
Press ENTER or type command to continue
    from pylama.lint.extensions import LINTERS
  File "/home/asher/.vim/bundle/python-mode.vim/pymode/libs/pylama/lint/extensions.
```

Any idea ?

Thank you in advance.

Asher256

PS: my vim is compiled with python3 and other python related plugins like vim-jedi are working well.

**Comment by MortalCatalyst** [comment]
I receive error in both python 2 & 3.

```bash
sayth@:~/Projects/playground$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
```

**Comment by bl4ckb1rd** [comment]
I workaround by editing file `/path/to/plugin_vim/python-mode/pymode/libs/pylama/lint/pylama_pyflakes.py` and comment line 20 and 21.

When comment line 20 `checker.messages.ReturnWithArgsInsideGenerator.message` the same error show with line 21 `checker.messages.ReturnOutsideFunction.message = "E0104 'return' outside function"`

**Comment by flmmartins** [comment]
For me it didn't work commenting the lines. My error:

Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fmartins/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fmartins/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 30, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fmartins/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 21, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import io
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fmartins/.pyenv/versions/2.7.11/lib/python2.7/io.py", line 51, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import _io
Press ENTER or type command to continue
Error detected while processing /Users/fmartins/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: dlopen(/Users/fmartins/.pyenv/versions/main/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCo
decInfo_GetIncrementalDecoder
Press ENTER or type command to continue
.....

**Comment by monological** [comment]
This happens because there are still old python2 .pyc files. To fix this go to the python-mode directory and run `find . -name '*.pyc' -delete`. This made the error go away for me.

Of course you have to have python3 installed, and vim configured with the --with-python3 and have `let g:pymode_python = 'python3'` set in your vimrc file.
