### ISSUE TITLE
how to exist "Run python code (<leader>r)"

### ISSUE THREAD

**Issue by bladechen** [python-mode/python-mode#653]
while running command "(<leader>r)", there would be a window below showing the result that excutes the python code. But how can i close this window quickly.
I mean print a key in the keyboard would do this for me.
Currently i switch window to the result window and enter ":q" to exist this window.
thanks

**Comment by nerolin91** [comment]
control+w+j/k to jump to ur origin code window

**Comment by bladechen** [comment]
thanks, but i think the "run python code window" should be closed through combination of pressing key.
do you have any idea about that?

**Comment by spybdai** [comment]
Yes, I agree with @bladechen 

Currently, after execution, u have to first switch the the result window, and then :q to exit the window, and the c+h/j/k/l/ to back to the code window. this is really troublesome...

there should be a "press enter or any other key to exit the result window", I think.

**Comment by cs-moushuai** [comment]
I think this problem should be solved
