### ISSUE TITLE
cimport not recognised as valid syntax by pyflakes in .pyx (cython) files

### ISSUE THREAD

**Issue by willfurnass** [python-mode/python-mode#660]
I get: `invalid syntax [pyflakes]`.  

Looks like `~/.vim/bundle/python-mode/syntax/pyrex.vim` references the `cimport` keyword, but not sure if/how this is enabled for `.pyx` files.  Tried adding the following to my `~/.vimrc` to no avail:

``` vim
au BufRead,BufNewFile *.pxd,*.pxi,*.pyx set filetype=pyrex
```

FYI plugins currently installed are:

```
gmarik/Vundle.vim
klen/python-mode
vim-scripts/MatlabFilesEdition
guns/vim-clojure-static
tpope/vim-fireplace
tpope/vim-salve
vim-scripts/paredit.vim
editorconfig/editorconfig-vim
derekwyatt/vim-scala
drmikehenry/vim-extline
vim-scripts/taglist.vim
altercation/vim-colors-solarized
```

**Comment by weatherfrog** [comment]
I have the same problem. Have you found a solution in the meantime?
