### ISSUE TITLE
Provide an option for disable automatic folding

### ISSUE THREAD

**Issue by kapsh** [python-mode/python-mode#668]
It would be useful if pymode has not only `pymode_folding` option. Because with this user can only completely disable or enable it. I know people that don't like when all folds are collapsed by default. So I suggest to add another option (e.g. `pymode_folding_auto`) with the the following behavior: 

As it works now — all folds are collapsed after file opening:

```
pymode_folding = 1
pymode_folding_auto = 1
```

Still can fold manually, but no folds are collapsed on freshly opened file:

```
pymode_folding = 1
pymode_folding_auto = 0
```

Generally no folding, second option is ignored:

```
pymode_folding = 0
pymode_folding_auto = 0
```

**Comment by Batur24** [comment]
`set nofoldenable` is not a good answer, but you can try it.
