### ISSUE TITLE
Why does python-mode have linter feature?

### ISSUE THREAD

**Issue by DXist** [python-mode/python-mode#67]
There are a lot of different plugins that provide code-checking feature. One of the most functional of them is Syntastic.

What I liked in Syntastic is:
- several ways to show error information
- support of several languages
- ability to highlight errors from different checkers in one style
- location list usage - quickfix window can be used by other plugins

So It does one thing and IMHO it does it well. Why does python-mode have own toolset to lint python code?

**Comment by tony** [comment]
https://github.com/scrooloose/syntastic/issues/558#issuecomment-219268142

Syntastic now supports multiple linters + aggregating results
