### ISSUE TITLE
several decorators and folding

### ISSUE THREAD

**Issue by mmosharov** [python-mode/python-mode#675]
hi!
thanks for great work!
my issue is when i add several decorators to a function, it does not show last when folded
for example, this:

``` python
@decorator1
@decorator2
@decorator3
def my_function():
    ...
```

appears as:

``` python
@decorator1
@decorator2
def my_function(): ----------------------------------------------------------------------------
```

can i see all of them?
thanks!

**Comment by knight-erraunt** [comment]
Hi, I read the code which was intended to do the folding and I think that the intention of the plugin author was that all the decorators should be folded with the function definition. Created two pull requests, one doing what you wanted to be done, and one with what I think was the intention of the author. I reckon you could comment something on the pull requests if you believe that the decorators should not be folded or something.
