### ISSUE TITLE
ImportError: No module named __future__

### ISSUE THREAD

**Issue by dimidd** [python-mode/python-mode#680]
I'm using MacVim, and getting this error each time I open a python file. I've install pymode manually.
I guess this is because I'm using python3, is it compatible with pymode?

```
Error detected while processing /Users/dimidd/.vim/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dimidd/.vim/pymode/__init__.py", line 3, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
Error detected while processing /Users/dimidd/.vim/ftplugin/python/pymode.vim:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dimidd/.vim/pymode/__init__.py", line 3, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```

**Comment by kiminoa** [comment]
Same issue for 2.7. I just switched from system python to brew python and got this. Trying brew unlinking and re-linking python and macvim to no avail. So I think it's more about vim being confused about what binary to use, rather than the binary itself.

**Comment by kiminoa** [comment]
This fixed it for me, fwiw. ymmv.

http://stackoverflow.com/a/34223629/2049086
