### ISSUE TITLE
pymode 's fold cause open/close file slow when file is over 1000 line.

### ISSUE THREAD

**Issue by pangchol** [python-mode/python-mode#683]
hi, I find I open and close python file slow when this file is over 1000 lines (2000 line is very obvious) ,  I spend some time to find reasion, at last , I find the pymode's fold mode cause this problam, I think it maybe cause by the pymode#folding#expr() function is too complex. so I want know if some good idea to let the pymode's fold function warking more faster?

**Comment by timfeirg** [comment]
install fastfold, you'll be amazed
https://github.com/Konfekt/FastFold

**Comment by pangchol** [comment]
er, I think fastfold is not suit for me, I read the pymode#folding#expr() function and the help of fold.txt, in vim's fold.txt help file， I find these description：

Note: Since the expression has to be evaluated for every line, this fold
method can be very slow!

Try to avoid the "=", "a" and "s" return values, since Vim often has to search
backwards for a line for which the fold level is defined.  This can be slow.

it ment expr fold easy to cause fold slow and especially using "=" as return values
in pymode#folding#expr() function I find many position return the "=" , so I think this function maybe Optimized to do not return the "=".

**Comment by timfeirg** [comment]
I found fastfold in https://github.com/klen/python-mode/issues/523#issuecomment-70078642, I have no clue if it didn't work out for you, I already disabled all the functionalities with pymode except rope refactoring stuff, here's my [vimrc](https://github.com/timfeirg/workspace-setup/blob/master/.nvimrc)

you know, this project is unmaintained.

**Comment by pangchol** [comment]
This project is really a pity nobody maintenance . I install the fastfold.vim and try use today, the fastfold seem realy bring the python-mode's fold Perform better. but the fastfold.vim bring some not convenient features ,such as it always fold all function when reopen a file. I read the fastfold.vim file and try to find what change is helpful to python-mode, at last I find fastfold.vim always set the foldmethod=manual after buffer enter.  so I try change the python-mode/ftplugin/python/pymode.vim 's code from:

if g:pymode_folding
    setlocal foldmethod=expr
    setlocal foldexpr=pymode#folding#expr(v:lnum)
    setlocal foldtext=pymode#folding#text()
endif

to:

if g:pymode_folding
    setlocal foldmethod=expr
    setlocal foldexpr=pymode#folding#expr(v:lnum)
    setlocal foldtext=pymode#folding#text()
    autocmd BufWinEnter * setlocal foldmethod=manual
endif

after this change I find large python file can close faster. and when reopen it all fold will reserve the state before closing. of course, I add the auto loadview and mkview in my vimrc like this:

autocmd BufEnter,BufWinEnter * silent! loadview
autocmd BufLeave,BufWinLeave * silent! mkview

maybe set foldmethod to manual after buffer  enter is the reason of why fastfold.vim can solve python-mode fold's performance issues.

**Comment by pangchol** [comment]
bacause manual fold method can't auto create and update fold, I add a <F5> key maping in big file to using create or update fold.

" Python folding
if g:pymode_folding
    setlocal foldexpr=pymode#folding#expr(v:lnum)
    setlocal foldtext=pymode#folding#text()
    if line("$") > 1500
        " in big file ,after Buffer enter, set foldmethod=manual
        autocmd BufEnter * setlocal foldmethod=manual
        " in manual mode fold with no auto creat and update
        " if you want using fold or update it, using <F5>
        map <F5> :setlocal foldmethod=expr<cr>zj:setlocal foldmethod=manual<cr>
    else
        " in small file using expr fold method to get auto creat and update fold
        autocmd BufEnter * setlocal foldmethod=expr
    endif
endif

**Comment by pangchol** [comment]
`" Python folding
if g:pymode_folding
    setlocal foldexpr=pymode#folding#expr(v:lnum)
    setlocal foldtext=pymode#folding#text()
    if line("$") > 1500
        " in big file ,after Buffer enter, set foldmethod=manual
        autocmd BufEnter * setlocal foldmethod=manual
        " in manual mode fold with no auto creat and update
        " if you want using fold or update it, using <F5>
        map <F5> :setlocal foldmethod=expr<cr>zj:setlocal foldmethod=manual<cr>
    else
        " in small file using expr fold method to get auto creat and update fold
        autocmd BufEnter * setlocal foldmethod=expr
    endif
endif
`
