### ISSUE TITLE
How to ignore errors from pep257?

### ISSUE THREAD

**Issue by crazy-canux** [python-mode/python-mode#685]
" Default code checkers
let g:pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe', 'pep257']

" Skip errors and warnings that you don't want to see.
let g:pymode_lint_ignore = "D101, D102, D103"

But I still see the errors which should be ignored?

**Comment by ZelphirKaltstahl** [comment]
Same here.

**Comment by lodagro** [comment]
For me this used to work, using for example
```let g:pymode_lint_options_pep257 = {'ignore': 'D100,D101,D102,D103'}```

Just did an upgrade to latest github code, and this no longer works. The *ignore* is ignored.

**Comment by fmv1992** [comment]
@lodagro,

The code has changed since then. Check the documentation:

https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L312

Best,

**Comment by lodagro** [comment]
@fmv1992 thanks for the tip. That works.

Confusing part is that docs still mention ```pymode_lint_options_pep257```

https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L369

**Comment by fmv1992** [comment]
I thank you as well. Unfortunately we are having a hard time maintaining everything and some parts of the documentation is not up to date.
