### ISSUE TITLE
Unknown function: pathogen#infect and Unknown function: pathogen#helptags

### ISSUE THREAD

**Issue by notaduck** [python-mode/python-mode#687]
i have done exactly as you described in the readme 

```
% cd ~/.vim
% mkdir -p bundle && cd bundle
% git clone https://github.com/klen/python-mode.git

# Added the lines to .vimrc in /home/user

" Pathogen load
filetype off

call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
syntax on
```

But when i try to start vim i do get his output?

```
Error detected while processing /home/daniel/.vimrc:
line    4:
E117: Unknown function: pathogen#infect
line    5:
E117: Unknown function: pathogen#helptags
Press ENTER or type command to continue

```

**Comment by blub123muh** [comment]
You need to install tpope's [pathogen](https://github.com/tpope/vim-pathogen) first:
pathogen is a very basic (but great) package managing system which allows to put plugins as a whole in a subdirectory of (such as 'bundle') and manages the runtimepath for you.

```
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
```

**Comment by rvnath** [comment]
I have installed pathogen correctly.  vim works correctly with .vimrc, but neovim fails with the below error:

```
rvnath@debian:~/.vim$ nvim
Error detected while processing /home/rvnath/.config/nvim/init.vim:
line    4:
E117: Unknown function: pathogen#infect
E15: Invalid expression: pathogen#infect()
Press ENTER or type command to continue
```
I am yet figuring out, how to fix it.

**Comment by rvnath** [comment]
OK, I missed symlinking the directory and files correctly.
I was supposed to symlink .vim and .vimrc both as below.
```
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim
```
But I realized, I didn't do the directory linking (step#1).  After rectification, the error is gone.

**Comment by fmv1992** [comment]
Nice : )
