### ISSUE TITLE
当我运行tornado项目时，vim卡住，无响应了。

### ISSUE THREAD

**Issue by fjqp** [python-mode/python-mode#688]
`
import tornado.ioloop
import tornado.web

class MainHandler(tornado.web.RequestHandler):
    def get(self):
        self.write("Hello, world!")

def make_app():
    return tornado.web.Application([
        (r'/', MainHandler),
    ])

if **name** == '**main**':
    app = make_app()
    app.listen(8888)
            #####@#@tornado.ioloop.IOLoop.current().start()
`

按<C-S-e>就会卡住。
注意，这个代码拷贝进去就会出现这样的格式，作者你要假设这个代码无任何错误，这是必须条件。

**Comment by timfeirg** [comment]
klen 不懂中文，也不再维护项目了

pymode 里边的runner并不接受stdin，个人认为在vim里调试python意义也不大，建议ctrl-z回到shell里调试，或者试试neovim的terminal

**Comment by fjqp** [comment]
Think you very much for your reply, your Chinese is good, 可以用python脚本另起一个线程，maybe will solve it,



发自我的小米手机在 timfeirg <notifications@github.com>，2016年7月8日 下午3:14写道：klen 不懂中文，也不再维护项目了

pymode 里边的runner并不接受stdin，个人认为在vim里调试python意义也不大，建议ctrl-z回到shell里调试，或者试试neovim的terminal

**Comment by fjqp** [comment]
你好我已经写了个插件在我的repos里，进去点个赞



发自我的小米手机在 timfeirg <notifications@github.com>，2016年7月8日 下午3:14写道：klen 不懂中文，也不再维护项目了

pymode 里边的runner并不接受stdin，个人认为在vim里调试python意义也不大，建议ctrl-z回到shell里调试，或者试试neovim的terminal

**Comment by fjqp** [comment]
klen真的好可惜



发自我的小米手机在 timfeirg <notifications@github.com>，2016年7月8日 下午3:14写道：klen 不懂中文，也不再维护项目了

pymode 里边的runner并不接受stdin，个人认为在vim里调试python意义也不大，建议ctrl-z回到shell里调试，或者试试neovim的terminal

**Comment by fjqp** [comment]
这么好的项目为什么不维护了



发自我的小米手机在 timfeirg <notifications@github.com>，2016年7月8日 下午3:14写道：klen 不懂中文，也不再维护项目了

pymode 里边的runner并不接受stdin，个人认为在vim里调试python意义也不大，建议ctrl-z回到shell里调试，或者试试neovim的terminal

**Comment by yaochao** [comment]
因为他比较忙，because he is busy

**Comment by fjqp** [comment]
我现在用ycm了



发自我的小米手机在 yaochao <notifications@github.com>，2016年7月19日 下午5:53写道：因为他比较忙，because he is busy

**Comment by Batur24** [comment]
It's fun to read Chinese here :-)

**Comment by Dana3** [comment]
这么好的项目为什么不维护了。
