### ISSUE TITLE
auto completion doesn't work with pyenv's vritualenv.

### ISSUE THREAD

**Issue by d0u9** [python-mode/python-mode#697]
I have python-mode installed in neovim, and created a virtual environment via `pyenv virtualenv 2.7.11`. After installing `beautifulsoup` library in this virtual environment, I find that python-mode can't auto complete any `beautifulsoup` functions.

The python client of neovim is python 3.5.2, and virtual env python is 2.7.11.

---

Is that python-mode use the neovim's default python interpreter as its backend python runtime env? if it is, How can I change it to the virtualenv's python interpreter?

**Comment by brycepg** [comment]
Duplicate of #403
