### ISSUE TITLE
Python executes raw_input before the print command

### ISSUE THREAD

**Issue by mohithkaranth** [python-mode/python-mode#703]
hi,
Example code:

print "How old are you?",
age_input = raw_input()
print age_input

print "How heavy are you?",
weight_input = raw_input()
print weight_input

when i execute this, i am asked for the raw_input before the "How Old are you?" is displayed on screen.
any reasons?

**Comment by fmv1992** [comment]
I used to have problems like this with print.

This is probably not an python-mode issue.

See:

http://stackoverflow.com/questions/230751/how-to-flush-output-of-python-print

In a nutshell: you need to flush the buffer in order for it to surely appear in the same order as the order of your code.

**Comment by mohithkaranth** [comment]
Thanks :)
