### ISSUE TITLE
Issue with %matplotlib inline

### ISSUE THREAD

**Issue by mohithkaranth** [python-mode/python-mode#704]
Hi,
My code:

import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number
import os
# Enable inline plotting

%matplotlib inline

On execution it says:
    %matplotlib inline
    ^
SyntaxError: invalid syntax

is there anything im missing? Thanks

**Comment by fmv1992** [comment]
This repos is for a vim plugin and the discussion should be centered on issues regarding this plugin/vim.

Your question is clearly from any stand point a syntax question.

Please use the appropriate channels for solving issues like this. Google or StackExchange would be a great place to start.

If you have a problem with python-mode in vim then this is the correct place.
