### ISSUE TITLE
Issus about usage of pdb

### ISSUE THREAD

**Issue by BorisChenCZY** [python-mode/python-mode#710]
When I am debugging python code, i added a break point.
But when the program stops, wherever i enter 'n' will not help to go on debugging.
What should i do?
thanks

**Comment by soulomoon** [comment]
+1 same issue here

**Comment by jennaliu** [comment]
I assume you are trying to debug Python code in python-mode (correct me if I am wrong). You can use a remote debugger to do so, e.g. [rpdb](https://pypi.python.org/pypi/rpdb/). After installing rpdb,  insert a breakpoint with `import rpdb; rpdb.set_trace()`. If you type a command that triggers the breakpoint, Vim will freeze. But you can connect to the debugger with
`telnet localhost 4444` and debug like you normally do with any Python script.
