### ISSUE TITLE
update the Pyflakes version used in python-mode

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [python-mode/python-mode#712]
Currently the pyflakes version used in python-mode does not support some of the keywords of python 3.5, for example `async` and `await`.  How can I fix that, so that it doesn't tell me that there is an error in my code, when there is none?

**Comment by brycepg** [comment]
The included version of pyflakes is a over year outdated, however it had support for the async keyword at that time. 

You will need to let pymode what version of python you are using by adding

    let g:pymode_python = 'python3'

To your vimrc or exrc.
