### ISSUE TITLE
@ symbol after new line causes freeze

### ISSUE THREAD

**Issue by econoraptor** [python-mode/python-mode#717]
I'm writing to a `.py` file using python, and I have some new lines starting with `@` (class decorator).  When the `python-mode` plugin is enabled, these lines cause vim to freeze. 

There don't seem to be any problems if the line with `@` is among the first few, but if it's beyond that and still in the window the file won't display at all.  However, if it's beyond the window the file reads just fine until getting to the line with `@`.

Here's a reproduction:

    with open("output.py", 'w') as outputfile:
        output = ['abcdefg'] * 50
        output.append('@hijk')
        output += ['lmnop'] * 10
        output_str = '\n'.join(output)
        outputfile.write(output_str)

**Comment by brycepg** [comment]
I'm having trouble reproducing this issue.

Can you reproduce with `vim -u <path to python-mode>/debug.vim`?
What is the output of `:PythonModeVersion`?
Did you use install via the master or develop branch?
