### ISSUE TITLE
g:pymode_options_max_line_length doesn't work

### ISSUE THREAD

**Issue by pinggit** [python-mode/python-mode#719]
after I installed pymode I don't see any color in the long line.
I checked this option:
```
let g:pymode_options_max_line_length = 80
let g:pymode_options_colorcolumn = 1
```
all looks good

any way to check what is wrong?

**Comment by brycepg** [comment]
In normal mode, typing `:echo &colorcolumn`  should return  `+1`. 
`echo &textwidth` should print a value greater than zero.

If you have manually disabled textwidth by setting it to 0 or setting `g:pymode_options` to 0, then you must manually set the color column, which you can do by putting:

    set colorcolumn=80

In your .vimrc file

**Comment by pinggit** [comment]
Bryce:
I checked the mentioned setting and they are all correct:

:echo &colorcolumn
:echo &textwidth
:let g:pymode_options

they returned +1 , 80 and 1.

and it looks I have the color column, but I don't see the color before or
after the column, which should be expected, right?

[image: Inline image 1]
