### ISSUE TITLE
one-line functions get folded with the previous block

### ISSUE THREAD

**Issue by anntzer** [python-mode/python-mode#729]
In
```
class C:
    pass

def f(): pass

def g():
    pass
```
`f` currently gets incorrectly folded into `C`.

**Comment by fmv1992** [comment]
Correct.
To fix this modify your
/python-mode/plugin/pymode.vim
from
`call pymode#default("g:pymode_folding_regex", '^\s*\%(class\|def\) \w\+')`
to
`call pymode#default("g:pymode_folding_regex", '^\s*\%(class\|def\) .\+\(:\s\+\w\)\@!')`

basically it says match def followed by some characters but those characters should not be followed by colon followed by any words.
In this case mult line defs are not affected, nor single line ended with `: `

**Comment by anntzer** [comment]
Your suggestion does not seem to work for me (for the example above).

**Comment by fmv1992** [comment]
@anntzer , you are correct. And that was funny because I indeed caught an error which was not yours.

The issue with your code is that definitions should be spaced with 2 blank lines; folding blocks take those into account. This convention is backed up by PEP 8:

> Surround top-level function and class definitions with two blank lines.

https://www.python.org/dev/peps/pep-0008/#blank-lines

So doing 
```
class C:
    pass


def f(): pass


def g():
    pass
```
should fix your issue and comply with PEP8 at the same time.

Best,

**Comment by anntzer** [comment]
But PEP8 also states that
> Blank lines may be omitted between a bunch of related one-liners (e.g. a set of dummy implementations).

which is certainly the case here.

**Comment by fmv1992** [comment]
I'm sorry for the late reply.

I don't agree with you. I don't see a bunch of one liners.

These would be a bunch of one liners:
```
def a():
    pass


def b():
    pass


def one_liner1(): pass
def one_liner2(): pass
def one_liner3(): pass

def c():
    pass


```
and those get folded correctly (as you and I expect).

Anyways to be as constructive as possible I point you to the piece of code which is responsible for the folding behavior, more specifically lines 119 to 132 and definitions of `BlockStart` and `BlockEnd`. I am also adding a `#TODO` review on my working fork but don't expect this to be timely.

Folding file: https://github.com/python-mode/python-mode/blob/develop/autoload/pymode/folding.vim#L119

**Comment by anntzer** [comment]
> If I'm not wrong you would want to exclude the last blank line to be included in the folding (for example line 3 in my code block). That would give you the intended behavior, but then only apply such exception if it is followed by a one line definition.

I think this is correct.

I don't want to get bogged down into an exegesis of PEP8 (although your interpretation may be the correct one :-)); rather, I'll simply say that even if I adhere pretty closely (I'd like to think) to PEP8, I rarely have control over whether the files I work with, that come from other sources, do.
