### ISSUE TITLE
python-mode wrong indenting for unbalanced parenthesis in string

### ISSUE THREAD

**Issue by orlp** [python-mode/python-mode#734]
If you have the following in your Python file:

    test = "unbalanced{{"

Then opening a new line after this will have incorrect automatic indenting.

**Comment by fmv1992** [comment]
I am not able to reproduce this issue. Can you post the output of this command?
`git rev-parse HEAD`

**Comment by orlp** [comment]
I forgot about this issue. Either way, I just reproduced with a fresh install on Xubuntu 17.10 64 bit, if I disable `python-mode` it doesn't happen, enabled it does.

```
λ git rev-parse HEAD
ed80fdebb5eb5e0e7e404484371221633a3926f6
```

**Comment by orlp** [comment]
@diraol I did, and I can still reproduce. Here are my exact steps to reproduce:

```
mkdir fake_home
cd fake_home

mkdir -p .vim/autoload .vim/bundle
curl -LSso .vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
cd .vim/bundle
git clone https://github.com/python-mode/python-mode.git
git checkout develop
cd ../..

cat > .vimrc <<EOF
set nocompatible
filetype off

call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
syntax on
EOF


cd ..
HOME=$HOME/fake_home vim
```

Then just typing 

    test = "unbalanced{{"

will produce the incorrect indent when opening a new line after it.

**Comment by diraol** [comment]
@fmv1992 is this instruction for pathogen correct? Git clone only, without the `git submodule update --init --recursive`?

**Comment by orlp** [comment]
@diraol  It's what I copied from your install page. Adding `git submodule update --init --recursive` to the script after the `git checkout develop` still has the issue.

**Comment by fmv1992** [comment]
@orlp,

I have just followed your procedure and was not able to reproduce the issue.

Please notice that ed80fdebb5eb5e0e7e404484371221633a3926f6 is more than 6 months old.

It would be kind of you to follow the link provided above and submit the bug according to it.

**Comment by orlp** [comment]
@fmv1992 `ed80fde` was when I did `git rev-parse HEAD` in the `master` branch, in the `develop` branch I get `a68a7a3ad98021372c8f4c58cc5f1bb81f68a2ee` (and still reproduce).

I can not reproduce with `-u <path_to_pymode>/debugvimrc.vim`.

**Comment by fmv1992** [comment]
Vim can cache an old function for a given file, or something like it.

That's why we add those flags `-i` and `-u` to the debug session: to be sure that the opened file is forcibly using the current code.

Feel free to reopen this issue as you see fit.

**Comment by orlp** [comment]
@fmv1992 I don't think that 'caching an old function' is what causes it. Keep in mind that with `-u` I had to type `syntax on` and other commands to even get anything to work, so I think it's more likely it's to do with some combination of settings.

**Comment by orlp** [comment]
@fmv1992 In fact, if I type `:set indentexpr` during `-u <path_to_pymode>/debugvimrc.vim` I find that __pymode doesn't set it__, unlike what it does normally. So the issue is definitely just being hidden. I can not reopen issues, please open the issue back up.

**Comment by orlp** [comment]
Steps to reproduce:

1.  `vim -i NONE -u <path_to_pymode>/debugvimrc.vim`.
2. `:set ft=python`
3. Insert `test = "unmatched{{"` on line 1, followed by an empty line.
4. `:echo pymode#indent#get_indent(2)` and note that it returns `19` instead of `0` as it should.
