### ISSUE TITLE
How to set the execute path of the python in python-mode?

### ISSUE THREAD

**Issue by BlasphemyAngels** [python-mode/python-mode#745]
I have installed another python(Anaconda). But the python-mode use the old python when I run the code. I want to use the new python when I run the code in python-mode. How to do it ? Can set the the python path of the python-mode?

**Comment by jennaliu** [comment]
I had the same issue. It seems like the only way to use another python path is to install Vim from source. Check https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
The following is the options I ran with configure:
`./configure --with-features=huge --enable-multibyte --enable-rubyinterp=yes --enable-python3interp=yes --with-python3-config-dir=/home/vagrant/anaconda3/lib/python3.5/config-3.5m --enable-perlinterp=yes --enable-luainterp=yes --enable-cscope --prefix=/usr`
