### ISSUE TITLE
Can't load python-mode: E887

### ISSUE THREAD

**Issue by miaton** [python-mode/python-mode#749]
It used to work without problem. Recently it starts to show the following errors.

Error detected while processing function pymode#init:
line    2:
E887: Sorry, this command is disabled, the Python's site module could not be lo
ded.
line    3:
E887: Sorry, this command is disabled, the Python's site module could not be lo
ded.
line    4:
E887: Sorry, this command is disabled, the Python's site module could not be lo
ded.
Error detected while processing C:\Users\XX\.vim\bundle\python-mode\autoload
pymode\virtualenv.vim:
line    3:
E887: Sorry, this command is disabled, the Python's site module could not be lo
ded.
Error detected while processing function pymode#breakpoint#init:
line   27:
E887: Sorry, this command is disabled, the Python's site module could not be lo
ded.
Error detected while processing C:\Users\XX\.vim\bundle\python-mode\ftplugin
python\pymode.vim:

**Comment by miaton** [comment]
add the following to .vimrc solved the problem
let g:pymode_python = 'python3'

**Comment by csxvzzzi** [comment]
cat >> ~/.vimrc << EOF
" Disable virtualenv in Pymode 
let g:pymode_virtualenv = 0 
" Disable pymode init and lint because of https://github.com/python-mode/python-mode/issues/897
let g:pymode_init = 0
let g:pymode_lint = 0
