### ISSUE TITLE
error when processing lint.vim

### ISSUE THREAD

**Issue by apeforest** [python-mode/python-mode#750]
The issue in #600 still happens to me even if I am using the develop branch with python version 2.7.13:

Stacktrace:
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/lyuan/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/lyuan/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 30, in
<module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/lyuan/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 21, in
<module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import io
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py
", line 51, in <module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import _io
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/pyt
hon2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder

**Comment by qingzew** [comment]
I have the same problem, it only works on python 2.7.10?

**Comment by jefferickson** [comment]
Same here with Python 2.7.13.

**Comment by cula** [comment]
Same here with python 2.7.13. 
The following is the errors:
"~/test.py" [New File]
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/huangyichao/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/huangyichao/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 30, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/huangyichao/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 21, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import io
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import _io
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  Expected in: flat namespace
Press ENTER or type command to continue
Error detected while processing /Users/huangyichao/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

**Comment by benjamingoodrich** [comment]
Getting the same error with Python 2.7.13

**Comment by bfgoodrich** [comment]
Getting the same error with Python 2.7.13

**Comment by cula** [comment]
@bfgoodrich 
I workaround this by upgrading vim from version 7.4 to version 8.0 on my mac and adding compilng with python 2.7

**Comment by bfgoodrich** [comment]
@cula - thanks, that worked!

**Comment by jefferickson** [comment]
Works here too. Thanks @cula

**Comment by ColinHuang** [comment]
Getting the same error with Python 2.7.6  and Vim 8.0

**Comment by hawkeyej** [comment]
Same problem with Python 3.6.1 and Vim 8.0

**Comment by sanjayankur31** [comment]
Getting this here too now:

```
[asinha@ankur  ~]$ python3 --version
Python 3.6.1
[asinha@ankur  ~]$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 27 2017 07:44:44)
Included patches: 1-679
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread    -O2 -g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/python3.6m -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro   -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -lnsl  -lselinux   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro  -Wl,-z,relro  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -lnsl -ldl -lm -lcrypt -lutil -lc
[asinha@ankur  ~]$
```

**Comment by sanjayankur31** [comment]
I think I'm seeing this too:

```
"pynest/nest/tests/test_sp/test_update_synaptic_elements.py" 72L, 2488C                                                                                                  
Error detected while processing /home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:                                                
line    1:                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                       
Press ENTER or type command to continue                                                                                                                                  
Error detected while processing /home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:                                                
line    1:                                                                                                                                                               
  File "<string>", line 1, in <module>                                                                                                                                   
Press ENTER or type command to continue                                                                                                                                  
Error detected while processing /home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:                                                
line    1:                                                                                                                                                               
  File "/home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/pymode/lint.py", line 9, in <module>                                                             
Press ENTER or type command to continue                                                                                                                                  
Error detected while processing /home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:                                                
line    1:                                                                                                                                                               
    from pylama.lint.extensions import LINTERS                                                                                                                           
Press ENTER or type command to continue                                                                                                                                  
Error detected while processing /home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:                                                
line    1:                                                                                                                                                               
  File "/home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 38, in <module>                                     
Press ENTER or type command to continue                                                                                                                                  
Error detected while processing /home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:                                                
line    1:                                                                                                                                                               
    from pkg_resources import iter_entry_points                                                                                                                          
Press ENTER or type command to continue                                                                                                                                  
Error detected while processing /home/asinha/Documents/100_dotfiles/vimfiles/bundle/python-mode/autoload/pymode/lint.vim:                                                
line    1:                                                                                                                                                               
ImportError: bad magic number in 'pkg_resources': b'\x03\xf3\r\n'      
```

Here's the version info:

```
[asinha@ankur  ~]$ python3 --version
Python 3.6.1
[asinha@ankur  ~]$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 27 2017 07:44:44)
Included patches: 1-679
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread    -O2 -g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/python3.6m -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro   -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -lnsl  -lselinux   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro  -Wl,-z,relro  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -lnsl -ldl -lm -lcrypt -lutil -lc
[asinha@ankur  ~]$
```

**Comment by sanjayankur31** [comment]
Seems like it was caused by some old pyc files. Running the following in the bundle directory: `find . -name \*.pyc -delete` fixed it for me. No more errors now.

**Comment by hawkeyej** [comment]
Thanks, that worked for me as well.

**Comment by ALoay94** [comment]
I use Manjaro, I first installed `python-pylint`but didn't work, then I installed `python2-pylint`, and it fixed it for me.

**Comment by resetreboot** [comment]
Here I was having the same problem after an update, Vim 8.0 and Python 3.5, the clearing of .pyc files did the trick!

**Comment by nickcorona** [comment]
Needs re-opening. This issue isn't solved.

**Comment by fmv1992** [comment]
Hey @nickcorona,

Thanks for your update on this bug. Issue reopened.

I know this is a bit of a hassle but can you please submit the output of your bug report as suggested in our [troubleshooting session](https://github.com/python-mode/python-mode#troubleshootingdebugging)?

**Comment by mgresko** [comment]
I see same issue as @jingpengw

**Comment by mgresko** [comment]
@jingpengw `git submodule update --init --recursive` fixes issue

**Comment by jingkungao** [comment]
I pointed vim to /usr/local/bin/vim (version 8.0 installed --with-lua using brew) and it solved the problem. The original vim was from /usr/bin/vim pre-installed with the mac system.

**Comment by matteoshen** [comment]
@mgresko thanks, works for me

**Comment by deathweaselx86** [comment]
Strangely enough, I was having this problem with a fresh virtualenv and Python 2.7.15. To sort of fix it, I am using the OS X system python(!?)

**Comment by diraol** [comment]
which python version from your OSX?

**Comment by deathweaselx86** [comment]
@diraol Python version for OS X is also 2.7.15.

This totally makes me sad because I depend on this plugin and I'd rather have a version of vim that has python 2 and 3 support.

**Comment by diraol** [comment]
@deathweaselx86 As far as I remember vim supporting both python2 and 3 interpreters at the same time has always been an issue (and not just with python-mode).

What people usually do is to have two "vim"s on the OS, one with python2 support (aliased to vim2) and another with python3 support (aliased to vim or vim3).

Regarding `python-mode` support to python2, we have a [goal](https://github.com/python-mode/python-mode/issues/935) of dropping python2 support in favor of python3, to avoid extra complexity in supporting both, since we don't have many contributors and the few we have have been struggling with time to dedicate to the project.

**Comment by roaming-debug** [comment]
I entered the python-mode directory and used `git pull`. Problem solved
