### ISSUE TITLE
How on earch can I set the indent to 2 space?

### ISSUE THREAD

**Issue by eduOS** [python-mode/python-mode#754]
80 characters are often not enough for one line, then I consider setting the indent to be 2 to save space, but I have tried many methods and all failed. How can I do it easily? Is there a straightforward way? Thanks very much.

**Comment by fmv1992** [comment]
I highly advise you against doing this. It is against PEP8 [https://www.python.org/dev/peps/pep-0008/#indentation].

Anyways this is not a python-mode issue:
`:help 'shiftwidth'` for information about the relevant variable
`set shiftwidth=2` will 'solve' your problem

**Comment by eduOS** [comment]
I have tried that. I t doesn't work. It's indeed againt PEP8, but many set like that: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py. It does saves space and look good at the same time.

**Comment by jennaliu** [comment]
set tabstop=2 shiftwidth=2 expandtab. This is a problem of how to use VIM, not an issue of python-mode btw.

**Comment by timfeirg** [comment]
close this issue? @eduOS

**Comment by 7AC** [comment]
@jennaliu I tried your suggestion but it doesn't work, is it possible those settings are overridden regardless? The only thing that seems to work is `let g:pymode_indent = 0` but that's too big of a hammer because it results in a lot of "continuation line under-indented for visual indent".

**Comment by timfeirg** [comment]
you can use `:verbose set tabstop?` and `:verbose set shiftwidth?` to check if these variables are overridden somewhere in your .vimrc or other plugins. @7AC

**Comment by 7AC** [comment]
I have another plugin setting `shiftwidth` which I knew about, but my point is is there a way to tell `python-mode` to use that value for indentation?

**Comment by StephaneKazmierczak** [comment]
I couldn't change the indent either from my vimrc because it would get overwrite in here: 
~/.vim/plugged/python-mode/after/indent/python.vim

**Comment by eduOS** [comment]
That would be awesome! @StephaneKazmierczak

**Comment by jennaliu** [comment]
If you really want to overwrite it in vimrc, you can add this line to your vimrc
`autocmd FileType python set shiftwidth=2 tabstop=2 expandtab`

**Comment by fmv1992** [comment]
Hello,

The documentation is explicit: Just `let g:pymode_indent = v:false`. Then set your indent as you wish. See: the file python-mode/after/indent/python.vim for further details.

**Comment by fmv1992** [comment]
Hello,

The documentation is explicit: Just `let g:pymode_indent = v:false`. Then set your indent as you wish. See: the file `python-mode/after/indent/python.vim` for further details.

**Comment by tunkul** [comment]
This was really bugging me as well. On Ubuntu, vim 8.1.*, the override of my ts=2 was coming from:

/usr/share/vim/vim81/ftplugin/python.vim

And to disable it, the below in my .vimrc did the trick:

let g:python_recommended_style = 0

**Comment by themadsens** [comment]
@tunkul This is indeed the correct way of doing this.
As documented in ":help PEP8"

**Comment by bevinhex** [comment]
for somepeople that even this didn't fix, keep in mind that vim-polygot plugin will mess with indentation as well, for me
had to add those two together, found out culprint by `grep shiftwidth -R ~/.vim`
```
let g:polyglot_disabled = ['autoindent']
let g:python_recommended_style = 0
```

**Comment by jingzhaoou** [comment]
I struggled for quite a while and finally found the solution here. Yeah, the settings are overwritten somehow. Thanks so much!

```
autocmd FileType python set shiftwidth=2 tabstop=2 expandtab
```
