### ISSUE TITLE
Pymode reports "Error detected while processing BufEnter Auto commands for "*":" when running code 

### ISSUE THREAD

**Issue by beebird** [python-mode/python-mode#756]
Can someone help take a look?

![image](https://cloud.githubusercontent.com/assets/3321149/25325046/e89c1080-28fb-11e7-9a8a-68fa4b2f483a.png)

>Pymode diagnostic
===================
VIM:800, OS: Darwin, multi_byte:1, pymode: 0.9.0, pymode-python: python3

+python: 0
+python3: 1

VIM python paths:
-----------------
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/waitress
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/tern_runtime
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/requests
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/racerd
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/OmniSharpServer
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/godef
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/gocode
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/frozendict
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/argparse
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/requests-futures
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/pythonfutures
/Users/xxxxx/.vim/bundle/YouCompleteMe/python/ycm/../../third_party/ycmd
/Users/xxxxx/.vim/bundle/YouCompleteMe/autoload/../python
/Users/xxxxx/.vim/bundle/jedi-vim
/Users/xxxxx/.vim/bundle/python-mode/pymode/libs
/Users/xxxxx/VirtualHome3/lib/python3.6/site-packages
/Users/xxxxx/.vim/bundle/python-mode
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Users/xxxxx/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/python-future/src
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
_vim_path_
/Users/xxxxx/.vim/bundle/python-mode/pymode/libs/astroid/brain

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>B'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 0
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 1
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 1
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = '/UsersxxxxxVirtualHome3'
l

**Comment by aropan** [comment]
[Comment](https://github.com/tpope/vim-fugitive/issues/414#issuecomment-171566518) - check you .vimrc a something `autocmd BufEnter * lcd %:p:h`.

**Comment by fmv1992** [comment]
Definitely not enough info to even hint that this is this plugin's fault.

Please log a full traceback.
