### ISSUE TITLE
pyflakes doesn't handle unicode filenames in imports

### ISSUE THREAD

**Issue by WPettersson** [python-mode/python-mode#762]
The below files run fine in python. Additionally, pyflakes-1.5.0 finds no fault in either of them. However, pyflakes in pymode does complain about column 8, line 3 of helloworld.py, notably the ß character. This, as best I can test, applies to any file with a unicode name. Is there any chance of upgrading the version of pyflakes used in python-mode? Or potentially just calling out to the system-installed version of pyflakes?

If no one is looking at this, I can take a look on the weekend and see if I can work it out myself, but I wanted to check first to see if anyone else was working on it.

teßt.py:
```
#!/usr/bin/env python3


def hello():
    return "Hello"
```

helloworld.py
```
#!/usr/bin/env python3

from teßt import hello

print("%s world" % (hello()))
```

**Comment by fmv1992** [comment]
Unfortunately this repo is kind of abandoned... I'm eager to contribute back to it again but I have no spare time for now...
If you are able to solve this issue please submit a PR

: )
