### ISSUE TITLE
Sorry,the command is not availabel in this version: python from pymode import rope

### ISSUE THREAD

**Issue by ClayAndMore** [python-mode/python-mode#765]
when i use '.' to get autocomplete ,the vim show this, Why？Thanks very much.

**Comment by fmv1992** [comment]
The issue is that PythonRope is enabled even though you set those to false:
```
let g:pymode_rope_completion = v:false
let g:pymode_rope_complete_on_dot = v:false
```

It is a bug and I'm trying to track it down.
