### ISSUE TITLE
Old version of pylint

### ISSUE THREAD

**Issue by mstislav-idpowers** [python-mode/python-mode#769]
Good day. 

Maybe i misunderstood something, but how can you use `pylint` version `1.4.4`? It doesn't work at all with `python3`. Maybe it should be updated? Or we can try to use git submodules instead of copy and paste pylint source code.

Thanks!

**Comment by DanThomson** [comment]
The version of `pylint` is no longer `1.4.4`. 
In `pymode/libs/pylint/__pkinfo__.py` line 15:
```numversion = (1, 6, 4)```

It was updated in `commit a8b1fe6887fa3ac875524ce907c4c6396135deb5` which was merged into master with `commit 0f641b1316779f6df66823ede778f332e0f1bb09` on 2017-06-29.

**Comment by brrrrain** [comment]
Thanks. It works.

**Comment by diraol** [comment]
@fmv1992 this issue can be closed ;)

**Comment by fmv1992** [comment]
Thanks : )
