### ISSUE TITLE
pymode/lint.py issue with version 0.9.1 and 0.9.2

### ISSUE THREAD

**Issue by randomizedthinking** [python-mode/python-mode#774]
For the 0.9.1 and 0.9.2 version of python-mode, an error message is thrown whenever I save a file. The issue is in file `pymode/lint.py` line 46: it tries to use pylint yet the default setting does not have it.

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/opensrc/.config/nvim/plugged/python-mode/pymode/lint.py", line 46, in code_check
        options.linters_params['pylint']['clear_cache'] = True
    KeyError: 'pylint'

Everything works okay with version v0.9.0.

**Comment by qwexvf** [comment]
But yeah, if you use the latest version of python-mode has fixed this issue.
why not give a try!!!

**Comment by randomizedthinking** [comment]
Thanks. The fix is in the development branch, so most people won't see it.

**Comment by kimdwkimdw** [comment]
https://github.com/python-mode/python-mode/commit/d2dead6ce9d900b26dbf1a06c52969f4194eda64#diff-61ea1bf6565615311af56f06f3572596R50 

fixed!

**Comment by randomizedthinking** [comment]
Thanks.

**Comment by Limeth** [comment]
I still seem to be having this problem, even with 0.9.2.

**Comment by qwexvf** [comment]
@Limeth you need to switch to the develop branch.

**Comment by eleijonmarck** [comment]
switched to the dev branch but still got the error :(
