### ISSUE TITLE
Upgrade fail with vim-plug

### ISSUE THREAD

**Issue by Coleej** [python-mode/python-mode#776]
I tried to upgrade with vim-plug after neglecting to do so for a couple weeks. All of my other plugins upgraded successfully, but python-mode gave me the following error:

`fatal: refusing to merge unrelated histories`

I don't know much about git merges or rebases, but it seems to be related to that process.

**Comment by chillipeper** [comment]
@Coleej what's the entry in your .vimrc ?

I had a similar issue, but got it fixed when I changed the path of the plugin
from: `Plug 'klen/python-mode'`
to:      `Plug 'python-mode/python-mode'`

**Comment by fmv1992** [comment]
There may have been inconsistencies in this plugin history. If you do not develop it and instead just clone/pull I advise you to remove the folder completely then clone everything again.

I apologize for a possible mismanagement on our part.

If you clone again please do so with `git clone --recursive https://github.com/python-mode/python-mode`.
