### ISSUE TITLE
Max line length default documented incorrectly

### ISSUE THREAD

**Issue by werneta** [python-mode/python-mode#778]
This is a very minor thing.  The documentation for g:pymode_options_max_line_length says that its default value is 79, (doc/pymode.txt:116), but its actual default value in the code is 80 (plugin/pymode.vim:52).

**Comment by simlmx** [comment]
I fixed it with `let g:pymode_options_max_line_length = 79` in my `.vimrc`.

**Comment by werneta** [comment]
I did the same thing.  The ticket was to note that the code and documentation do not match, and one should be updated.

**Comment by fmv1992** [comment]
Fixed in commit 3e37c3c343d6302568aab8cfe27eef23df47f457.

Thanks for reporting!
