### ISSUE TITLE
KeyError: 'pylint'

### ISSUE THREAD

**Issue by zeraus** [python-mode/python-mode#783]
Hello! I'm using Neovim and I got this message when I save the file at first, and then if I check with `:PymodeLint`
I've installed pylint with pip, `pip install pylint`

![Imgur](http://i.imgur.com/aumUiGX.png)
```
Pymode diagnostic
===================
VIM:704, OS: Darwin, multi_byte:1, pymode: 0.9.2, pymode-python: python3


+python: 0
+python3: 1

VIM python paths:
-----------------
/Users/xnu/workspace/automate-the-boring-stuff
/Users/xnu/.local/share/nvim/plugged/python-mode/pymode/libs
/Users/xnu/.local/share/nvim/plugged/python-mode
/Users/xnu/.local/share/nvim/plugged/jedi-vim
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/site-packages
_vim_path_
/Users/xnu/.local/share/nvim/plugged/python-mode/pymode/libs/astroid/brain

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 1
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 1
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 1
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 1
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 0
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''
```
========================================
Python related plugins and configurations from init.vim:
```
"" Plugins
Plug 'klen/python-mode', { 'for': 'python' }
Plug 'davidhalter/jedi-vim', { 'for': 'python' }
Plug 'zchee/deoplete-jedi', { 'for': 'python' }

"" Python
let g:python_host_prog = '/usr/local/bin/python2'
let g:python3_host_prog  = '/usr/local/bin/python3'

" Skip the check of neovim module
let g:python3_host_skip_check = 1
let g:loaded_python_provider = 1

" Avoid jedi-vim's Py2-not-functional message
let g:jedi#force_py_version = 3

"" pymode (fix PymodeRopeRegenerate)
let g:pymode_rope = 0
```

What I'm doing wrong? 
Please help me and also let me know if I left information to provide.

**Comment by zeraus** [comment]
Same with #775, #774.
Is it fixed or not?

**Comment by qwexvf** [comment]
Hello, i dont know why they still keep that fix in the develop branch but you can switch to develop branch to get the fix.
if your using vim-plug for example
```Bash
Plug 'python-mode/python-mode', {'branch': 'develop'}
```
Something like this.
Good luck sir.

**Comment by zeraus** [comment]
Hi @qwexvf, thanks for the answer. It's fixed somehow after last update.
I will try as you guided if I got it next time.
Again, thank you!

**Comment by eleijonmarck** [comment]
I still get same problem. It appears everytime. It is very annoying :(

**Comment by diraol** [comment]
@eleijonmarck you may need to clear the cache/compiled files:

https://github.com/python-mode/python-mode/issues/777#issuecomment-336736623

**Comment by eleijonmarck** [comment]
Thanks that worked

**Comment by cuducos** [comment]
I'm still having this issue. I'm using a brand new computer (formatted yesterday, reinstalled the OS), and even cleaning `__pycache__` and `*.pyc` the error pops in.

Is changing `options.linters_params['pylint']` by something `options.linters_params.get('pylint')` a valid solution? Why?

**Comment by diraol** [comment]
Hi @cuducos !

where exactly are you proposing to make this change?

**Comment by cuducos** [comment]
> where exactly are you proposing to make this change?

Hum… ok, my bad. I should have better studied the way branches and releases work in this repo. Let me try to clarify. The error I'm getting is as follows:

![screen shot 2019-03-01 at 10 01 41](https://user-images.githubusercontent.com/4732915/53925292-3ca41300-405e-11e9-8bbb-fc52c0c6a50f.png)

However, now I see that this code is not present at the `develop` branch anymore. Thus I'm not sure if it still makes sense to do what I was planning to do, which was to use `.get` on the dictionary to avoid the `KeyError`…

**Comment by diraol** [comment]
No problem! You were probably using the master branch and, indeed, our current maintained working branch is the develop.

Take a look to see if it works if you change to the develop branch, please. ;)

**Comment by cuducos** [comment]
> Take a look to see if it works if you change to the develop branch, please. 

Indeed: worked like a charm. Many thanks : )
