### ISSUE TITLE
Setting g:pymode_lint_ignore triggers an AssertionError in autopeps8.py

### ISSUE THREAD

**Issue by rubenvereecken** [python-mode/python-mode#786]
The assertion error in question is triggered by this line: https://github.com/python-mode/python-mode/blob/develop/pymode/autopep8.py#L3035

It happens with for example this line in my `.vimrc`:

```
let g:pymode_lint_ignore = "E501"
```

which I got from the help file. Obviously the function where the assert takes place expects a list but gets a string instead, but I'm not sure where `pymode_lint_ignore` is or should be parsed into a list (from a comma-delimited string).

**Comment by rubenvereecken** [comment]
This is fixed on the user side by using a list of strings as a value instead of a comma-delimited list. If this is expected behaviour, the docs need an update.

**Comment by mxlian** [comment]
Thanks for you'r research, really helped. Will put a PR to update the docs

**Comment by rubenvereecken** [comment]
Sweet, thanks!

**Comment by fmv1992** [comment]
Thanks guys; fixed with 76c582b9df2c3895cc34ef7b238ff0ddfabeea1e.
