### ISSUE TITLE
Python 3 & 2 Syntax

### ISSUE THREAD

**Issue by kierun** [python-mode/python-mode#788]
I know I can use:

```
let g:pymode_python = 'python3'
```

to switch to Python 3. However, I have some project on Python 3 and some on Python 2. Is there a way to switch seamlessly (aka not edit `~/.confg/nvim/init.vim`) from one to the other?

**Comment by diraol** [comment]
Hi @kierun , I think you have two ways to go here.

You can may try using [vim modeline](http://vim.wikia.com/wiki/Modeline_magic] in every file to set python2 (or python3). I personally think this would be hard to maintain, and I am not sure if this would work.

One other option is to create two different config files, one for python2 and other for python3 (like `~/.vimrc.py2` and `~/.vimrc.py3`) and then create two aliases to use each one of these files:
```
alias vim2='vim -u ~/vimrc.py2'
alias vim3='vim -u ~/vimrc.py3'
```

**Comment by kierun** [comment]
@diraol Nice work around. Thank you.

**Comment by kierun** [comment]
Using @diraol work around and [zsh autoeven](https://github.com/Tarrasch/zsh-autoenv) you can achieve this automatically so you can type `gvim` and `nvim` anywhere and it does the right thing™:

```
# Autoenv.
function gvim {
    nvim-qt --geometry 970x512 -- -u ~/.config/nvim/init-py3.vim "$@" &
}
alias nvim='nvim -u ~/.config/nvim/init-py3.vim'
echo -n "Switching to virtual environment: "
printf "\e[38;5;93m%s\e[0m\n" "ook"
workon ook
#eof
```

This does require using an "autoeven" (bash/zsh), virtual environments, and set it all up (copy-and-past?) between projects. However, one might use those tools in any case. Still, there should be a pure (neo)vim solution really…

**Comment by fmv1992** [comment]
Thanks for your post but this discussion is not within the scope of this plugin's reach.

Vim 'forces' you to either load one python or the other once per session/file.
