### ISSUE TITLE
Error encounter in python-mode

### ISSUE THREAD

**Issue by duytrung** [python-mode/python-mode#790]
Hi

I use vim with vim plug to install python mode

This is the log when I first run:

```
vim learnpython.py
```

Results:
```

"learnpy.py" 6L, 75C
Error detected while processing C:\Users\William\.vim\plugged\python-mode\autoload\pymode\lint.vim:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing C:\Users\William\.vim\plugged\python-mode\autoload\pymode\lint.vim:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing C:\Users\William\.vim\plugged\python-mode\autoload\pymode\lint.vim:
line    1:
  File "C:\Users\William\.vim\plugged\python-mode\pymode\lint.py", line 9, in <module>
Press ENTER or type command to continue
Error detected while processing C:\Users\William\.vim\plugged\python-mode\autoload\pymode\lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Press ENTER or type command to continue
Error detected while processing C:\Users\William\.vim\plugged\python-mode\autoload\pymode\lint.vim:
line    1:
  File "C:\Users\William\.vim\plugged\python-mode\pymode\libs\pylama\lint\extensions.py", line 38, in <module>
Press ENTER or type command to continue
Error detected while processing C:\Users\William\.vim\plugged\python-mode\autoload\pymode\lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Press ENTER or type command to continue
Error detected while processing C:\Users\William\.vim\plugged\python-mode\autoload\pymode\lint.vim:
line    1:
ImportError: No module named 'pkg_resources'
Press ENTER or type command to continue

```

Could anyone suggest anything?

**Comment by icemanx7** [comment]
I am getting the same error. What could be causing this?

**Comment by edwardreed81** [comment]
I am experiencing this error too.

**Comment by ConradP** [comment]
I'm getting this error aswell.

**Comment by moorepants** [comment]
Same error here.

**Comment by bbbco** [comment]
https://github.com/python-mode/python-mode/issues/750#issuecomment-315538093 seems to have a great solution:

> Seems like it was caused by some old pyc files. Running the following in the bundle directory: find . -name \*.pyc -delete fixed it for me. No more errors now.

**Comment by moorepants** [comment]
Deleting the pyc fixes this for me too.

**Comment by moorepants** [comment]
Deleting the pyc files did seem to work, but with anything higher than version 0.9.0 the linters don't see to find any errors even if there are errors. Checking out 0.9.0 fixes things.

**Comment by dc3671** [comment]
I finally find the reason. 

In Ubuntu16 LTS, vim is default compiled with `+python3` rather than `+python`. So if you run `:PymodeTroubleshooting` in vim, it will show `+python: 0` which means no support for python2. However, the pymode's code is python2 version.

SOLUTION: Install `vim-nox-py2` for Ubuntu16 without GUI support or `vim-gnome-py2` with GUI support.

**Comment by fmv1992** [comment]
Thanks. I'll mark this thread as solved.

Feel free to reopen it.
