### ISSUE TITLE
linters omitted from g:pymode_lint_checkers are still used

### ISSUE THREAD

**Issue by smheidrich** [python-mode/python-mode#791]
Maybe I'm misunderstanding what the option does, but if I set, for instance,
```vim
let g:pymode_lint_checkers = [ 'pyflakes' ]
```
I don't expect to see any errors from e.g. the ``pycodestyle`` linter, because it's not in the list.

Yet in the current revision of the ``develop`` branch I get errors from at least all of Pylama's default linters no matter what I put in the list, and it's bugging me a bit.

Let me know if I'm mistaken about how the ``g:pymode_lint_checkers`` option is supposed to work, maybe this is intended?

**Comment by fmv1992** [comment]
Already fixed in a prior pull request.

I'm sorry for the delay.

Let me know if you still encounter this issue.

**Comment by smheidrich** [comment]
Thank you! :+1:
