### ISSUE TITLE
Enable remote interpreters 

### ISSUE THREAD

**Issue by wklm** [python-mode/python-mode#794]
The possibility to use a remote python environment (like a one running in docker container or on a remote server) would be super useful. Pycharm has this feature already and vs code plugin is going to have it in the near future as well https://github.com/DonJayamanne/pythonVSCode/issues/123

**Comment by fmv1992** [comment]
Dear @wklm,

I appreciate this suggestion but we are in the midst of a re prioritization of
issues and before we add more functionality we have to be sure to have what we
already have working well.

Thus I'm marking this as low priority.

Thanks for your feedback and understanding.

As always, feel free to help us implement this feature!
