### ISSUE TITLE
pymode#trim_whitespaces() is incompatible with plugins that use :saveas

### ISSUE THREAD

**Issue by Heptite** [python-mode/python-mode#797]
See this page: https://vi.stackexchange.com/questions/13638/why-does-rename-fails-with-python-files-if-there-is-no-trailing-space

Simply put, the substitute command in pymode#trim_whitespaces() just needs an "e" flag:

```
" DESC: Remove unused whitespaces
fun! pymode#trim_whitespaces() "{{{
    if g:pymode_trim_whitespaces
        let cursor_pos = getpos('.')
        silent! %s/\s\+$//e
        call setpos('.', cursor_pos)
    endif
endfunction "}}}
```

**Comment by fmv1992** [comment]
Thanks, will be pushed soon!
