### ISSUE TITLE
python run 

### ISSUE THREAD

**Issue by kerwinxu** [python-mode/python-mode#800]
the below is source code

`A = 99899
B = 88888

def test1():
    global A
    global B
    tmp1 = A + B
    tmp1 = A - B
    tmp1 = A * B
    tmp1 = A / B
    A = A + 1
    B = B + 1
    return tmp1

if __name__ == '__main__':
    from timeit import Timer
    t1 = Timer("test1()", "from __main__ import test1")
    print(t1.timeit(1000))`

below is error 
testspeed.py|28 error| in <module> t1 = Timer("test1()", "from __main__ import test1")
D:/Anaconda3/lib/timeit.py|178 error| in timeit timing = self.inner(it, self.timer)
<timeit-src>|3 error| in inner ImportError: cannot import name 'test1

**Comment by alphaCTzo7G** [comment]
doesnt seem to be anything related the python-mode plugin..

**Comment by kerwinxu** [comment]
when i 
:!python %
it is ok
when i 
	let g:pymode_run_bind = '<F5>'
it is error .

**Comment by steven-walton** [comment]
I can confirm I am having the same issue. Using timeit inside of python-mode, I get an error that it is unable to import whatever variables/classes/functions I am trying to import from __main__ . Running the same script outside of vim on the same virtual environment had no error.

**Comment by fmv1992** [comment]
Please provide an idented version of the code for reproducibility.

Also please see the new section https://github.com/python-mode/python-mode#troubleshootingdebugging for submitting bugs.

Thanks : )
