### ISSUE TITLE
One buffer save, cursor jumping declarations

### ISSUE THREAD

**Issue by tony** [python-mode/python-mode#814]
Around November 21, 2017,  2e027cb , this started happening

If I remove *python-mode*, this behavior goes away.

Pymode version: 0.9.4 interpreter: python3 lint: 0 rope: 0

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 17 2017 12:01:00)
macOS version
Included patches: 1-1305
Compiled by Homebrew
```

My python-mode settings:

```vim
function! StartPymode()
    let g:pymode_virtualenv = 1 " Auto fix vim python paths if virtualenv enabled        
    let g:pymode_folding= 1  " Enable python folding
    let g:pymode_rope = 0

    let g:pymode_lint = 0
    if g:pymode_lint != 0
        if exists('flake8')
          let g:pymode_lint_checkers = []
          autocmd BufWritePost *.py call Flake8()
        else
          let g:pymode_lint_checkers = ['pep8', 'pep257', 'pyflakes', 'mccabe']
        endif
        let g:pymode_lint_ignore = 'C0111,D100,D101,D102,D103'
        let g:pymode_lint_sort = ['E', 'C', 'W', 'R', 'I', 'F', 'D']
        let g:pymode_lint_unmodified = 1
    endif
endfunction

call PlugOnLoad('python-mode', 'call StartPymode()')
```

https://github.com/tony/vim-config-framework/blob/01def0b72494febbb6d7a05d9990c8a92a088593/plugins.settings/contrib/pymode.vim

Whole vim config https://github.com/tony/vim-config-framework/tree/01def0b72494febbb6d7a05d9990c8a92a088593/

**Comment by tony** [comment]
b66198d5147d1e2b6ec57c47819828b37981a494 works.

The behavior starts in 5b6e92d4f7a1d45691a6ac53ee076b8efd2ce400

It happens on buffer write, and also when I open buffer and first unfold, the cursor jumps to a method inside of a class (I haven't determined any pattern)

Expected behavior: Cursor shouldn't navigate anywhere at all.

**Comment by fmv1992** [comment]
Bug confirmed.

I will fix it later today! Meanwhile I suggest that you turn off folding by: `:set fdm=marker`. It masks the problem until then.

I apologize for the inconvenience!

**Comment by fmv1992** [comment]
@tony,

If you can please submit the bug report according to the https://github.com/python-mode/python-mode#troubleshootingdebugging section that would be useful!

By using it on a folded file I get a different problem: on writing it does not move but it does messes up input mode (a more serious problem then).

**Comment by tony** [comment]
I tried using `vim -i NONE -u ~/.vim/plugged/python-mode/debugvimrc.vim`

I can't recreate it there.

[pymode_debug_file.txt](https://github.com/python-mode/python-mode/files/1491766/pymode_debug_file.txt)

**Comment by tony** [comment]
I even added my config settings to debugvimrc.vim, and can't recreate.

**Comment by fmv1992** [comment]
@tony,

Thanks for your bug report.

That how life is like for vim plugin users :'D

I sometimes have bugs that cannot replicate and neither discover their origins.
It's very frustrating.

However your bug report was useful for me to realize another one.

Let me know if you have further insights on this issue.

**Comment by fmv1992** [comment]
Please see post on https://github.com/python-mode/python-mode/issues/815:

* * *
Hey guys,

Hopefully commit 0eb845240bde8683dd1fc43dfab99da945fe61e6 and the one
before have solved this issue.

Short story: moved view and cursor position restore to the exact place where
they move.

No autocommands needed (which is good!).

As of now I'm writing tests to ensure this behavior will be consistent with
future releases. Folding for pymode is so complex :/.

Best,
* * *

I'm closing this issue; please leave further comments on #815.
