### ISSUE TITLE
Strange behaviour after 'dd' 'cc'

### ISSUE THREAD

**Issue by duikboot** [python-mode/python-mode#815]
When I want to delete a line `dd`, the line is deleted, but de cursor move up to the top of the class, or function when in a function.
When hitting `cc`, it deletes the line, moves to the toplevel function or class and goed into insert mode

This behaviour is only there when I install python-mode.

**Comment by fmv1992** [comment]
@duikboot,

Bug confirmed and its related to
https://github.com/python-mode/python-mode/issues/815.

This was partially fixed yesterday with
60c638d0b9393a1ec86e42229e2da9de786b7405.

Since when you `dd` you do not enter insert mode this bug circumvents the
aforementioned fix.

I'll fix it in ~12h. Meanwhile I suggest that you add the following to your
vimrc file:

`let g:pymode_folding = 0`

Thanks for reporting!

**Comment by diraol** [comment]
@fmv1992 , #815 is the current issue.... ;)

**Comment by fmv1992** [comment]
: )

*related to https://github.com/python-mode/python-mode/issues/814

**Comment by fmv1992** [comment]
Hey guys,

Hopefully commit 0eb845240bde8683dd1fc43dfab99da945fe61e6 and the one
before have solved this issue.

Short story: moved view and cursor position restore to the exact place where
they move.

No autocommands needed (which is good!).

As of now I'm writing tests to ensure this behavior will be consistent with
future releases. Folding for pymode is so complex :/.

Best,

**Comment by diraol** [comment]
Yest, it seems to be working now. =)

**Comment by songww** [comment]
default:
![image](https://user-images.githubusercontent.com/8115960/33203622-b6cff664-d13b-11e7-90b4-96bb752aed1f.png)

open class:
![image](https://user-images.githubusercontent.com/8115960/33203647-c54f921c-d13b-11e7-8d18-b1a86a54d14c.png)

open after_init:
![image](https://user-images.githubusercontent.com/8115960/33203669-d53833e6-d13b-11e7-942d-45f6da88617a.png)

file is `https://gitlab.com/pycqa/flake8/blob/master/src/flake8/formatting/base.py`
:(.

**Comment by fmv1992** [comment]
@songww,

Bug confirmed and solved.

I'll upload to our repos in the near future. Meanwhile please apply the
following patch:

~~~~~~
From b6c602dac3739e3d8d9b070b4b6b7c17b6befd39 Mon Sep 17 00:00:00 2001
From: "Felipe M. Vieira" <fmv1992@gmail.com>
Date: Fri, 1 Dec 2017 12:45:44 -0200
Subject: [PATCH] fixed false positive folding for single line on multiline

---
 autoload/pymode.vim         |  2 +-
 autoload/pymode/folding.vim | 18 +++++++++++++++---
 2 files changed, 16 insertions(+), 4 deletions(-)

diff --git a/autoload/pymode.vim b/autoload/pymode.vim
index 6beb89a..9736fc7 100644
--- a/autoload/pymode.vim
+++ b/autoload/pymode.vim
@@ -134,7 +134,7 @@ fun! pymode#debug(msg) "{{{
         let g:pymode_debug_counter += 1
         " NOTE: Print a separator for every message except folding ones (since
         " they could be many).
-        if a:msg !~ 'has folding:'
+        if a:msg !~ 'has folding:' && a:msg !~ 's:Is_opening_folding:'
             echom l:info_separator
         endif
         echom '' . 'pymode debug msg ' . g:pymode_debug_counter . ': ' . a:msg
diff --git a/autoload/pymode/folding.vim b/autoload/pymode/folding.vim
index 5baf36e..25be278 100644
--- a/autoload/pymode/folding.vim
+++ b/autoload/pymode/folding.vim
@@ -129,7 +129,7 @@ fun! pymode#folding#foldcase(lnum) "{{{
         return {'foldcase': l:foldcase, 'foldlevel': l:foldlevel}
     endif
     if line =~ s:docstring_end_regex
-        if !s:Is_opening_folding(a:lnum)
+        if ! s:Is_opening_folding(a:lnum)
             let l:foldcase = 'close multiline docstring'
             let l:foldlevel = 's1'
         endif
@@ -297,11 +297,24 @@ function! s:Is_opening_folding(lnum) "{{{
     " not just triple quotes (that could be a regular string).
 
     " Iterater over all lines from the start until current line (inclusive)
+    if g:pymode_debug
+        call pymode#debug('s:Is_opening_folding: invoked on line ' . a:lnum)
+    endif
+
     for i in range(1, line('$'))
 
+        if g:pymode_debug
+            call pymode#debug('s:Is_opening_folding: line: ' . a:lnum)
+            call pymode#debug('s:Is_opening_folding: extra_docstrings: ' . extra_docstrings)
+            call pymode#debug('s:Is_opening_folding: fold_odd_even: ' . fold_odd_even)
+            call pymode#debug('s:Is_opening_folding: has_open_docstring: ' . has_open_docstring)
+        endif
+
         let i_line = getline(i)
 
-        if i_line =~ s:docstring_begin_regex && ! has_open_docstring
+        if i_line =~ s:docstring_line_regex
+            " Blank case.
+        elseif i_line =~ s:docstring_begin_regex && ! has_open_docstring
             " This causes the loop to continue if there is a triple quote which
             " is not a docstring.
             if extra_docstrings > 0
@@ -314,7 +327,6 @@ function! s:Is_opening_folding(lnum) "{{{
         elseif i_line =~ s:docstring_end_regex && has_open_docstring
             let has_open_docstring = 0
             let fold_odd_even = fold_odd_even + 1
-
         elseif i_line =~ s:docstring_general_regex
             let extra_docstrings = extra_docstrings + 1
         endif
-- 
2.14.2

~~~~~~

Thanks for reporting.

**Comment by songww** [comment]
Thanks. It is solved in this case.
But asynchronous functions still have problems

**Comment by fmv1992** [comment]
@songww,

can you provide a concrete example?

And please follow the guildelines of https://github.com/python-mode/python-mode#troubleshootingdebugging

Thanks for your support!
