### ISSUE TITLE
All pymode default mappings involving <C-c> fail in Vim 8

### ISSUE THREAD

**Issue by ReeseWang** [python-mode/python-mode#823]
Pythom-mode default mappings such as goto definition (`<C-c>g`) don't work in Vim 8.
Every time you press `<C-c>`, Vim 8 will teach you the way to quit Vim:
`Type   :qa!   and press <Enter> to abandon all changes and exit Vim.`

But I can still somehow map `<C-c>` in Vim 8 using :map command. If I execute
`:map <C-c> :qa! <Enter>`
I'm able to map `<C-c>` to force quit Vim.

Vim 7 seems to pop up that teaching only if I press `<C-c>` for successive two times so I can use python-mode default binding. This isn't the case in Vim 8.

**Comment by tartansandal** [comment]
Tried various remapping operations without success on Vim 8. Ended up just changing the prefix to `<leader>p`

**Comment by rubendibattista** [comment]
This is kinda annoying :).

Any suggested alternatives to the mapping suggested by @tartansandal ?

**Comment by rubendibattista** [comment]
@tartansandal How did you remapped the prefix? Because using `pymode_rope_rename_bind` does not work for me...

**Comment by tartansandal** [comment]
Hi Ruben,

I did it one binding at a time:

let g:pymode_run_bind = '<leader>r'
let g:pymode_breakpoint_bind = '<leader>b'
let g:pymode_rope_show_doc_bind = '<leader>pd'
let g:pymode_rope_goto_definition_bind = '<leader>pg'
let g:pymode_rope_goto_definition_cmd = 'new'
let g:pymode_rope_rename_bind = '<leader>pr'
let g:pymode_rope_module_to_package_bind = '<leader>p1p'
let g:pymode_rope_extract_method_bind = '<leader>pm'
let g:pymode_rope_extract_variable_bind = '<leader>pl'
let g:pymode_rope_use_function_bind = '<leader>pu'
let g:pymode_rope_move_bind = '<leader>pv'
let g:pymode_rope_change_signature_bind = '<leader>ps'

Hope this helps

Kal

**Comment by fmv1992** [comment]
We'll probably move away from `C-c`. Its equivalent to cancel/kill program in Unix. I'm sorry for this bad choice.

Contributions are welcome!

**Comment by kedpter** [comment]
has anyone fixed this problem ?
I rebind `let g:pymode_rope_rename_bind = '<leader>rn'`, `E486: Pattern not found: CTRL-C`, still not working on mac 10.11.6 
Besides, rope not generated even if i typed `:PymodeRopeRegenerate`

**Comment by kedpter** [comment]
After a little debugging, seems to be `rope` not loaded.  
changed `plugin/pymode.vim`
```
" Rope support
" call pymode#default('g:pymode_rope', 0)
call pymode#default('g:pymode_rope', 1)
```
and everything works fine.

**Comment by fmv1992** [comment]
Thanks @kedpter,

However rope should be disabled by default. Are there any other workarounds that you suggest?

**Comment by glennlawyer** [comment]
Hi,
I see that this is stale. However, I'm just setting up my VIM for python, and running into this issue. Would be nice to have it fixed. @fmv1992, what sort of progress are you seeing in moving away from <C-c>?

**Comment by diraol** [comment]
@glennlawyer can you please try the branch `test_new_rope_bindings` from my [fork](https://github.com/diraol/python-mode)?

I've remapped `<C-c>` to `<leader>r` with some other changes.
As far as I could check this won't conflict with other mappings.

**Comment by glennlawyer** [comment]
sorry it took a few days to get to this. 

I'm getting a lot of loading errors, similar to what your "fix-six-import" branch fixed.

And unfortunately,  switch back to the "fix-six-import" branch also gives a long list of errors, likewise when I switch to the "develop" branch on the main repo (which you merged "fix-six-import" into a few days ago.

However, the errors might also be because I just updated to Mojave; I don't know if I've opened a python file since the update. After the Mojave update, I upgraded vim with homebrew; so am using 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 29 2018 04:51:04)
macOS version
Included patches: 1-550
Compiled by Homebrew
```

I also upgraded my python to `Python 3.7.1`, again using homebrew. Prior to this I had been running 3.6.

Managing plugins with `Plugged`.
When  set to
```
Plug 'diraol/python-mode', {'branch':'fix_six_import'}
```
opening `application.py` gives the following errors:
```
"application.py" 390L, 14210C
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'pymode.libs.six'
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
  File "/Users/glennlawyer/.vim/plugged/python-mode/pymode/lint.py", line 9, in
<module>
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
ModuleNotFoundError: No module named 'pylama'
```

and 
```
Plug 'python-mode/python-mode', {'branch':'develop'}
```
gives
```
"application.py" 390L, 14210C
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
  File "/Users/glennlawyer/.vim/plugged/python-mode/pymode/lint.py", line 9, in
<module>
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
  File "/Users/glennlawyer/.vim/plugged/python-mode/pymode/libs/pylama/lint/exte
nsions.py", line 50, in <module>
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
  File "/Users/glennlawyer/.vim/plugged/python-mode/pymode/libs/pkg_resources/__
init__.py", line 3092, in <module>
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /Users/glennlawyer/.vim/plugged/python-mode/auto
load/pymode/lint.vim:
```

**Comment by diraol** [comment]
Try removing all '.pyc' files and '__pycache__' directories from
'pyrhon-mode' directory tree.

Em ter, 11 de dez de 2018 13:25, Glenn Lawyer <notifications@github.com
escreveu:

**Comment by glennlawyer** [comment]
Thanks for this idea. It was easier to just delete the entire `python-mode` directory. I then re-install the  plugin, getting the same results as above.

**Comment by diraol** [comment]
@glennlawyer so the issue is fixed? Can I close it?

**Comment by AdrienLemaire** [comment]
Can someone re-open this issue? Using neovim, pressing `<C-c>` gives me the same error.

> Type  :qa!  and press <Enter> to abandon all changes and exit Nvim

@fmv1992 is moving away from C-c scheduled in python-mode's roadmap?

**Comment by AdrienLemaire** [comment]
@diraol isn't `<leader>r` mapped to run python code already? Why did you choose this mapping as replacement to C-c in your fork?

**Comment by diraol** [comment]
@Fandekasp I've remapped `<leader>r+<someotherkeys>`, not just `<leader>r`, as standing to `rope+<something>`.
But that was just a try, and I don't even remember if I have finished it completely.

Can you please post more information to help us track the problem?

**Comment by AdrienLemaire** [comment]
@diraol I see, as long as we type `<leader>r<something>` quickly, this will work. Thanks for the quick reply.

```console
$  vim --version
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter
-Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Running python-mode ae6f8d5f710007d6bdb9b9da7f9e74eaa1da58a5 (2019-04-15) via vim-plug

```vim
Plug 'python-mode/python-mode', { 'branch': 'develop', 'for': 'python' }
let g:pymode_python = 'python3'
```

If you need more information, please let me know. Regarding a new mapping, I don't mind using what the majority prefers, but I believe it's easier to learn mappings when each vim plugin uses a dedicated prefix. Since this package wants to be a all-in-one plugin for python, you could request the `<leader>p` prefix, and build all shortcuts from there:
* `<leader>pr`: python run
* `<leader>pb`: python breakpoint
* `<leader>pgd` python goto definition (just extending `CTRL-]` is better)
* `<leader>pra` python rope autocomplete (btw I've always used Ctrl-Space as Input Method switching key)
* ...

The reasoning is: Whenever you can, re-use existing maps by extending them (like `K`). Otherwise, use a mnemonic prefix to ease memorization. 
Other plugins use the same convention, like NERDCommenter with `<leader>c`.

**Comment by 1900018250** [comment]
> After a little debugging, seems to be `rope` not loaded.
> changed `plugin/pymode.vim`
> 
> ```
> " Rope support
> " call pymode#default('g:pymode_rope', 0)
> call pymode#default('g:pymode_rope', 1)
> ```
> 
> and everything works fine.



> After a little debugging, seems to be `rope` not loaded.
> changed `plugin/pymode.vim`
> 
> ```
> " Rope support
> " call pymode#default('g:pymode_rope', 0)
> call pymode#default('g:pymode_rope', 1)
> ```
> 
> and everything works fine.

think you

**Comment by 1900018250** [comment]
@kedpter think you!
