### ISSUE TITLE
Bug with folding

### ISSUE THREAD

**Issue by rqy1458814497** [python-mode/python-mode#825]
It works well, until I start editing my `setup.py`.
When I open the file, vim pauses. I press ctrl-c to continue, but once I press any key, it pauses again.
It also occupies a lot CPU time.
If I disable pymode_folding, the problem disappears.
Here is my `setup.py`:
[setup.py](https://github.com/rqy1458814497/RLJ/blob/master/setup.py)

**Comment by fmv1992** [comment]
@rqy1458814497,

Can you please report using our reporting mechanism?

Take a look at:
<https://github.com/python-mode/python-mode#troubleshootingdebugging>

Hope to hear from you soon.

Best.

**Comment by nineKnight** [comment]
I get into the same trouble.
What's more, when I insert in the first line like this:
```python
def my_name():
```
and then input ```Enter``` and go to the second line, I can't edit any more until I press ```<C-c>```. But when I can edit finally, problem comes again and then I press ```<C-c>``` again to make vim show what I've input.
Now, it makes me to disable pymode_folding to get out of it. Jesus!!!

PS: Only when the first line is a ```def``` thing, the problem turns up.

**Comment by fmv1992** [comment]
See issue #839. Let's use that one for discussion (closing this).
