### ISSUE TITLE
Pymode seems to freeze on opening a very simple file and trying to source folding.vim

### ISSUE THREAD

**Issue by kevinkjt2000** [python-mode/python-mode#826]
Most of the output from `nvim -i NONE -u ~/.config/nvim/bundle/python-mode/debugvimrc.vim` has possibly sensitive path names, so here is the tail end of it:
```
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled
pymode_virtualenv_path
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:
39d9ab803c8a7538581050841910af66ae5b03d8
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
pymode debug msg 7: line 1 has folding: >1 with foldcase function declaration
pymode debug msg 8: line 2 has folding: = with foldcase non blank line; first line of block
 or part of it
pymode debug msg 9: line 3 has folding: = with foldcase blank line after non blank line
pymode debug msg 10: line 4 has folding: 0 with foldcase general
pymode debug msg 11: line 5 has folding: >1 with foldcase function declaration
```

The file that I was trying to load:
```python
def spam():
    pass

def eggs():
    pass
```

What I expected is that vim would not freeze when loading this simple of a python file.  I did notice that if I add a newline above the spam function, the file opens and does not freeze vim.  Vim also does not freeze if I remove python-mode from my list of plugins https://github.com/kevinkjt2000/dot-vim/blob/c8eccb09ccc8f71697ba3a4a81049abd5820ec10/plugins.vim#L25

(And by vim, I mean neovim's nvim)

**Comment by fmv1992** [comment]
@kevinkjt2000,

That's unfortunate. And I'm also puzzled because the folding part goes until the end of your file; all 5 lines are assigned a folding value.

I also noticed we don't have commit `39d9ab803c8a7538581050841910af66ae5b03d8`. I have mismanaged some history in the past and possibly have overwritten some commits. The bottom line is that possibly your issue has already been solved as our repos had a lot of improvements lately.

Could you please reassure that you have the latest commit: `2ae7a23` (as of 2017-12-17)?

Much appreciated! Thanks for the reporting!

**Comment by kevinkjt2000** [comment]
Okay, I'm not sure what is up with the commit I have installed at work is not in your history, but at home I have `2ae7a23` installed (in general I update vim plugins about once a week at least).

```
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2017-12-17 20:50:21 with file
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #1
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled
pymode_virtualenv_path
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:
2ae7a2323d7632eaa5fc5170c287608ecf8d25c5
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
pymode debug msg 7: line 1 has folding: >1 with foldcase function declaration
pymode debug msg 8: line 2 has folding: = with foldcase non blank line; first line of block
 or part of it
pymode debug msg 9: line 3 has folding: = with foldcase blank line after non blank line
pymode debug msg 10: line 4 has folding: >1 with foldcase function declaration
```

Same file as I mentioned above.

**Comment by vlcinsky** [comment]
Bingo, I am searching for a solution (and root cause) of very same problem as described here.

More details:
- it happens for some files and does not happen for others. Behaviour seems consistent and specific file dependent.
- If I open such file:
  - file does not open until Ctrl-C which probably stops some background processes and shows the file up. Sometime the file opens, but does not syntax highlight as with other python files. Again, Ctrl-C helps.
  - CPU goes high and stays there until Ctrl-C
  - vim commands such as "cw" (change word) do not function. Nothing happens till Ctrl-C.

Note, that the Ctrl-C is not a workaround as any change of the file becomes a problem (like running with shoe laces tight for both shoes together).

**Comment by vlcinsky** [comment]
@kevinkjt2000 thanks for mentioning, that adding empty line at the top before first function prevents the problem. I can confirm it works in other cases (I have another two files  exhibiting the same problem, adding a line resolved it, I am also able to modify other files to force them into this trouble.).

Simple docstring such as:
```python
"""Docstrings are good.
"""
def spam():
    pass

def eggs():
    pass
```

helps.

The reason this problem hit me more often in last weeks is that I started using `yapf` to format my code and in case there was no import nor doctstring, the first function got at the very top.

**Comment by vlcinsky** [comment]
The issue is biting me so often I had to temporarily disable the folding in my `.vimrc`:

	" Work around python-mode bug with never ending look on fold of very first line
	let g:pymode_folding = 0

Looking forward for some fix.

**Comment by fmv1992** [comment]
@vlcinsky,

I'm sorry for the delayed response.

This plugin has had far too many problems with folding. Folding is very tricky with python in vim.

I've been working on solutions but a definitive one has yet to come. In the meantime I suggest to disable folding just like you did.

:/
