### ISSUE TITLE
Function definition followed by opening docstring folds into one line

### ISSUE THREAD

**Issue by scott-burgess** [python-mode/python-mode#828]
The following code:
```
def setup_parser():
    """
    Setup the command line parameter parser.
    """
    parser.setup()
```
Folds like this:
```
def setup_parser(): --------------------------------------------------------------------- 1-
    Setup the command line parameter parser.
    """
    parser.setup()
```

Whereas I'd expect it to fold like:
```
def setup_parser(): --------------------------------------------------------------------- 4-
```
This doesn't fold at all:
```
def setup_parser():
    """ Setup the command line parameter parser.
    """
    parser.setup()
```

This used to fold how I'd expect it to in an earlier version.
PEP-8 doesn't say which way is recommended, PEP-257 briefly mentions my way:
https://www.python.org/dev/peps/pep-0257/ 

Is this a bug, or have I broken something?

**Comment by fmv1992** [comment]
@scott-burgess,

I have just replied to another post:
"
I'm sorry for the delayed response.

This plugin has had far too many problems with folding. Folding is very tricky with python in vim.

I've been working on solutions but a definitive one has yet to come. In the meantime I suggest to disable folding just like you did.

:/
"

I'll put a folding topic in our FAQ. Thanks for reporting!

**Comment by simian-typist** [comment]
I'm having the exact same problem at the moment. It seems to work for some docstrings and not others.

Though the problem seems to have been exacerbated by moving some functions lower in the file.
