### ISSUE TITLE
Import error inside vim when trying to run

### ISSUE THREAD

**Issue by IceS2** [python-mode/python-mode#830]
I'm trying to run a simple script: `import pandas as pd`

I'm receiving the following error: `"Missing required dependencies {0}".format(missing_dependencies)) Import Error:? Missing required dependencies ['numpy']`

But I've got numpy installed. I can import python nicely from the repl.

**Comment by madhukar93** [comment]
I had a similar issue, see if it helps:
https://github.com/python-mode/python-mode/issues/829

**Comment by IceS2** [comment]
I see... Thing is when I run :!which python it points to my virtualenv nicely

**Comment by fmv1992** [comment]
Hey @IceS2,

Thanks for your update on this bug. I know this is a bit of a hassle but can you please submit the output of your bug report as suggested in our [troubleshooting session](https://github.com/python-mode/python-mode#troubleshootingdebugging)?

**Comment by sulibo** [comment]
I also got a problem when running similar script: `import pandas `
<pre><span style="background-color:#1C1C1C"><font color="#87AFD7">/usr/lib/python3.6/site-packages/pandas/__init__.py</font></span><span style="background-color:#1C1C1C"><font color="#BCBCBC">|</font></span><span style="background-color:#1C1C1C"><font color="#FFD75F">51 </font></span><span style="background-color:#1C1C1C"><font color="#D75F5F">error</font></span><span style="background-color:#1C1C1C"><font color="#BCBCBC">| in &lt;module&gt; plot_params = pandas.plotting._style._Options(deprecated=True) AttributeError: module &apos;pandas&apos;has no attribute &apos;plotting&apos; </font></span><span style="background-color:#1C1C1C"><font color="#3A3A3A"></pre>

But if I run in terminal, there is no such error.
