### ISSUE TITLE
pycodestyle ignores g:pymode_lint_select option

### ISSUE THREAD

**Issue by wilywampa** [python-mode/python-mode#831]
The selected issues specified by `g:pymode_lint_select` do not get passed to the pycodestyle linter. For example, make a Python file with:
```python
x = 1+2
```
then do
```vim
:let g:pymode_lint_select = ['E226']  " or more generally ['E22']
:PymodeLint
```
The error list will be empty instead of giving the missing whitespace around operators error E226.

**Comment by fmv1992** [comment]
I confirm this bug. It looks like the list is not updating or there is some other problem going on.
