### ISSUE TITLE
Spaces highlighted as trailing whitespace immediately after typing

### ISSUE THREAD

**Issue by benlindsay** [python-mode/python-mode#833]
I just installed python-mode, and now in python files it will highlight spaces as I'm typing them instead of waiting until I exit insert mode or move to another line before highlighting trailing whitespace.  This is too annoying to be expected behavior but I'm not sure where it originates or how to fix it. I see this behavior even with my `.vimrc` file is stripped down to the following:

```
set nocompatible
filetype plugin indent on

call plug#begin('~/.vim/bundle')
Plug 'python-mode/python-mode'          " Turn vim into a python ide
call plug#end()
```

and all other plugins besides python-mode are moved to a different directory. Where should I look to try to fix this?

**Comment by fmv1992** [comment]
@benlindsay,

This might be considered annoying but it has to with trailing spaces. Trailing spaces should be inexistent in python files (as well as empty lines with spaces etc).

I'm not sure if its worth changing the code to add highlighting after leaving insert mode. However if you find a suitable solution please submit a PR.

**Comment by abers** [comment]
Just installed python-mode and my immediate thought was "how to turn off this annoying red flashing when typing". If there is currently no way to disable it when typing and to highlight trailing whitespace after exiting insert mode - is there a way to disable whitespace highlighting in python-mode? I already have it set to trim any trailing whitespace so turning off the highlighting shouldn't cause any problems.
