### ISSUE TITLE
How to enable pycodestyle?

### ISSUE THREAD

**Issue by Magicloud** [python-mode/python-mode#836]
Recently I reinstalled my computer, so I reinstalled pycodestyle via Bundle, which means the python-mode may be got upgraded.
Then I noticed that all the coding checking are from pyflakes, instead of pycodestyle.
How do I enable pycodestyle?

**Comment by fmv1992** [comment]
Read the docs:

https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L267

This shows which linters are available and how to use them.
