### ISSUE TITLE
Symbolic links to submodules breaks python-mode on Windows

### ISSUE THREAD

**Issue by jondye** [python-mode/python-mode#837]
Installing python-mode in vim on Windows (using Vundle) checks out the git repo. Symlinks aren't supported on Windows (at least by git and not in any nice way in general). Therefore the pymode/libs directory, which has symlinks to the libraries in the submodules directory doesn't work on Windows and no python libraries can be imported.

**Comment by fmv1992** [comment]
Thanks @jondye for reporting this bug.

I was aware that this could be a problem for vim users in Windows and took quite a while for this to show up (meaning that our Windows user base is rather small). Maintaining a project for different OSes places additional burden on our scarce development team.

To be very honest with you I don't have time to work on this issue for now. I do apologize for that. So I either suggest you to checkout an older version of `python-mode` which does not have symlinks (around the `d2dead6ce9d900b26dbf1a06c52969f4194eda64` commit, from @klen) or help us implementing a solution. A nice place to start is here:

https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

Best,

**Comment by kierun** [comment]
I think I am hitting the same bug but only on one of the two windows machines I use.

Do you need anything to help debug/test?

**Comment by jondye** [comment]
@fmv1992 I though you'd say that :-)

I was trying to think of workarounds and wondered if .pth files might hold a solution. I also wondered if we could add the folders under submodules directly to the python path in python-mode.

I actually got it working on Windows by getting git to generate symlinks but it's not pretty. Under Windows you need to turn on symlinks in the git config (`core.symlinks`) and then checkout as an admin user (because you need a special permission to create symlinks on Windows).

This doesn't work well with Vundle or any other package manager but to be honest, the submodules didn't work with Vundle anyway (even on my linux machine) and required me to manually update the 
 submodules so perhaps that's another issue that needs raising separately.

**Comment by kierun** [comment]
Just reverted to `d2dead6ce9d900b26dbf1a06c52969f4194eda64` and I indeed do not see the error. So, at least that's a work around, if inadequate.

**Comment by fmv1992** [comment]
@jondye,

I know this whole procedure is cumbersome. Actually I have no idea why you need admin rights to make symlinks on Windows... Windows puzzles me everyday I have to deal with it.

As of vim8 there is a recommended package structure (`:help packages`) so notwithstanding the popularity of package managers for vim I'll favor the official method.

I'll take a look at this `.pth` possibility but I have never heard of it.

Thanks for your understanding.
