### ISSUE TITLE
could I launch pdb and debug in vim directly?

### ISSUE THREAD

**Issue by CoinCheung** [python-mode/python-mode#838]
I see there is a feature that can add break points, and I wonder how could I continue debug following that? Can py-mode be a front end of those debuggers such as pdb or so? If there is already this feature, would you please tell me how to activate it?

**Comment by fmv1992** [comment]
I suggest that you use:

<http://pypi.python.org/pypi/pudb>

And create your keybindings to launch from within a vim session.

I personally find it very useful to have vim always open in one screen and then run the python program on a different terminal. It also makes it easier to edit code as you interact in another console (using completion and yanking to paste from vim to the other console).

I don't think `python-mode` should enable this by default.
