### ISSUE TITLE
Replacement for pylama?

### ISSUE THREAD

**Issue by diraol** [python-mode/python-mode#841]
Hi all!

I've got to know yala (http://github.com/cemsbr/yala) which seems to be a nice possible replacement for pylama as a dependency for this project.

I'm saying that because here, at python-mode, we have changed from having the linters codes under our versioning to set them as submodules (external dependencies).

pylama still have linters codes under its git repo, while yala has a more similar approach in regard to linters. This make its code easier to maintain and keep it updated.

Does it make sense? Does anyone thinks that worth trying it?

**Comment by diraol** [comment]
Ow, one possible problem with yala is the support to multiple python versions, I think this will need to be verified more closely.

**Comment by fmv1992** [comment]
I think this is a very good idea. Unfortunately pylama seems barely maintained and I favor the idea that we migrate for something that has current development.

I have no idea on the specifics to implement the change though but I would like to learn since I'll probably do the python-mode version for Scala.

**Comment by diraol** [comment]
@cemsbr would you help us?

**Comment by diraol** [comment]
I think the mains changes would be at:

https://github.com/python-mode/python-mode/blob/13666d8c62363a44b3282fdea5b968e178bd724c/pymode/lint.py

and at

https://github.com/python-mode/python-mode/blob/0f641b1316779f6df66823ede778f332e0f1bb09/pylama.ini

**Comment by cemsbr** [comment]
Hi guys. Yes, I'm willing to help. The purpose of yala is to be small and not to depend on linters' code, in an attempt to make it more maintainable.

Regarding the versions, It was 3.6, now it's 3.5+ and, as the code is small, I can make an effort to make it compatible with other versions if needed.

**Comment by fmv1992** [comment]
@cemsbr,

You are encouraged to contribute :) . I also perceive this change to be beneficial.

I recently started to add some tests to whatever change we do in this project so including some simple tests (very basic to ensure that future changes do not break current code) would be a nice plus!

**Comment by diraol** [comment]
Which python versions do you guys think we should support?

**Comment by fmv1992** [comment]
I think whatever places less burden on the dev team.

For compat we should support 2.7 (unfortunately) and the latest stable python3.x version.

I'm open to different ideas too.

**Comment by cemsbr** [comment]
I'll try to make it compatible with Python 2.7, too.

**Comment by fmv1992** [comment]
I would like to test this as soon as you have an (un)stable version up : )

This will probably move away a lot of code in this repos.

Let me know where to find it!

**Comment by cemsbr** [comment]
Great. I'll dive into this code to see where and how linters are used. Then, I'll make it work with Python 3 first and later, port yala to Python 2.7.
