### ISSUE TITLE
Highlight whatever function name

### ISSUE THREAD

**Issue by nineKnight** [python-mode/python-mode#842]
Here I'm and I've finishded the func by adding the following code into `syntax/python.vim`:
```vimscript
    syn match pythonFunction "\w\+\s*(\@="
```
Now all the function names are being highlighted. Thanks to the work of [octol/vim-cpp-enhanced-highlight](https://github.com/octol/vim-cpp-enhanced-highlight.git).

Hey @fmv1992 , would you mind my `commit` without `fork`?

**Comment by fmv1992** [comment]
@nineKnight,

I do appreciate your effort to contribute to this project.

However I think that highlighting your own defined functions would rather pollute the code. Highlighting is all about code readability. Its like highlighting a text: you would rather make important passages/words important, not the entire page.

I'll let others comment on this issue. If the userbase wants it I'll happily incorporate to our code.

Please I **do encourage you to continue to contribute to this project**.

**Comment by fmv1992** [comment]
I don't see any suggestions on triviality anywhere on my comments.

Rather the opposite. What drew me to this project was folding in the first place and it is the issue that has cost me most in terms of time and I'm aware that the results are still scant. I wish I could take those hours back into other more pressing things in this project.

Folding is not easy in vim and specially in python where no "black and white" rules exist. Just see the code.

I'm longing for other contributors to show up.

**Comment by nineKnight** [comment]
@fmv1992 Understood, thx.

**Comment by mrprofessor** [comment]
@nineKnight @fmv1992 I like the Idea. But It also highlights when I try to create an object.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/11652364/60766787-751b3280-a0cc-11e9-9133-5ff50b0da222.png">
