### ISSUE TITLE
centos7.4  use python-mode have a problem 

### ISSUE THREAD

**Issue by yunqingan** [python-mode/python-mode#843]
I use yum  install vim  ,then use vundle install python-mode  。 When writing a letter, it automatically wraps and spell it in insert mode。I don't know why ?   I want help

**Comment by yunqingan** [comment]
sorry , I use  spf13-vim  install python-mode  ,not vundle

**Comment by fmv1992** [comment]
Hey @yunqingan,

Thanks for your update on this matter. Please see our session on how to install:

https://github.com/python-mode/python-mode#how-to-install

We cannot account for the uncountable methods that exist for installing vim.
