### ISSUE TITLE
Irritating Red line

### ISSUE THREAD

**Issue by lalitmee** [python-mode/python-mode#847]
I am using oh-my-vim for my vim and in that I am using cobalt colorscheme. I don't know why a red color line is showing up in every type of file. I want to remove this. 

**Please help me. Thanks in advance.**
![vimredline](https://user-images.githubusercontent.com/10762218/35776325-2cbd2b5a-09c0-11e8-88a0-f9a3396f29b9.png)

**Comment by rubendibattista** [comment]
I believe that is not related to `pymode`.

https://stackoverflow.com/a/3787678/1334711

It depends on you color scheme and on your configuration in `.vimrc`.

**Comment by vishichoudhary** [comment]
autocmd BufRead *.py setlocal colorcolumn=0 will solve your problem

**Comment by fmv1992** [comment]
Read the diligently crafted help shipped with this program:

```
Enable colorcolumn display at max_line_length.   *'g:pymode_options_colorcolumn'*
>
    let g:pymode_options_colorcolumn = 1

```

**Comment by diraol** [comment]
This seems to be solved, I'm closing it.
If any further assistance is needed, please, comment it to be reopened.
