### ISSUE TITLE
pymode can't be used out of the box?

### ISSUE THREAD

**Issue by ybma-xbzheng** [python-mode/python-mode#848]
I am a vim newbie, after using vundle to install pymode, it becomes like this:
<img width="623" alt="f6212ce3-7343-410e-8c42-30bd7905ce8c" src="https://user-images.githubusercontent.com/13780309/35850131-c39c3d5a-0b5e-11e8-900b-7c70d2a83d8f.png">
Why syntax is not highlighted? Need some other settings?
I have been haunted for a few days, anyone knows where the problem is? Need to provide some logs?

**Comment by diraol** [comment]
@ybma-xbzheng Please, take a look at the project README (How to Install): https://github.com/python-mode/python-mode#how-to-install
