### ISSUE TITLE
Error when processing file 

### ISSUE THREAD

**Issue by xsqr** [python-mode/python-mode#850]
I'm trying to use Vim with installed python
module (https://github.com/python-mode/python-mode). 

When opening VIM for *.py file I'm noticing that error (but any found resolution is not aplicable...)

`:messages`
`Messages maintainer: Bram Moolenaar <Bram@vim.org>`
`"graph.py" 460L, 22558C`
`Error detected while processing /home/karol/.vim/bundle/python-mode/autoload/pymode/lint.vim:`
`line    1:`
`Traceback (most recent call last):`
`Error detected while processing /home/karol/.vim/bundle/python-mode/autoload/pymode/lint.vim:`
`line    1:`
`  File "<string>", line 1, in <module>`
`Error detected while processing /home/karol/.vim/bundle/python-mode/autoload/pymode/lint.vim:`
`line    1:`
`  File "/home/karol/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>`
`Error detected while processing /home/karol/.vim/bundle/python-mode/autoload/pymode/lint.vim:`
`line    1:`
`    from pylama.lint.extensions import LINTERS`
`Error detected while processing /home/karol/.vim/bundle/python-mode/autoload/pymode/lint.vim:`
`line    1:`
`ImportError: No module named 'pylama' `

Please note that Pylama is installed for both versions of Python on server :)

`pylama==7.4.3`

My environment:
VIM:
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)`
`Included patches: 1-197, 322, 377-378, 550, 703, 706-707`
`Modified by pkg-vim-maintainers@lists.alioth.debian.org`
`Compiled by pkg-vim-maintainers@lists.alioth.debian.org`
`Huge version with GTK3 GUI.  Features included (+) or not (-):`
`+acl             +file_in_path    +mouse_sgr       +tag_old_static`
`+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white`
`+autocmd         +float           +mouse_urxvt     +tcl`
`+balloon_eval    +folding         +mouse_xterm     +termguicolors`
`+browse          -footer          +multi_byte      +terminfo`
`++builtin_terms  +fork()          +multi_lang      +termresponse`
`+byte_offset     +gettext         -mzscheme        +textobjects`
`+channel         -hangul_input    +netbeans_intg   +timers`
`+cindent         +iconv           +num64           +title`
`+clientserver    +insert_expand   +packages        +toolbar`
`+clipboard       +job             +path_extra      +user_commands`
`+cmdline_compl   +jumplist        +perl            +vertsplit`
`+cmdline_hist    +keymap          +persistent_undo +virtualedit`
`+cmdline_info    +lambda          +postscript      +visual`
`+comments        +langmap         +printer         +visualextra`
`+conceal         +libcall         +profile         +viminfo`
`+cryptv          +linebreak       -python          +vreplace`
`+cscope          +lispindent      +python3         +wildignore`
`+cursorbind      +listcmds        +quickfix        +wildmenu`
`+cursorshape     +localmap        +reltime         +windows`
`+dialog_con_gui  +lua             +rightleft       +writebackup`
`+diff            +menu            +ruby            +X11`
`+digraphs        +mksession       +scrollbind      -xfontset`
`+dnd             +modify_fname    +signs           +xim`
`-ebcdic          +mouse           +smartindent     +xpm`
`+emacs_tags      +mouseshape      +startuptime     +xsmp_interact`
`+eval            +mouse_dec       +statusline      +xterm_clipboard`
`+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save`
`+extra_search    -mouse_jsbterm   +syntax`
`+farsi           +mouse_netterm   +tag_binary`
`   system vimrc file: "$VIM/vimrc"`
`     user vimrc file: "$HOME/.vimrc"`
` 2nd user vimrc file: "~/.vim/vimrc"`
`      user exrc file: "$HOME/.exrc"`
`  system gvimrc file: "$VIM/gvimrc"`
`    user gvimrc file: "$HOME/.gvimrc"`
`2nd user gvimrc file: "~/.vim/gvimrc"`
`       defaults file: "$VIMRUNTIME/defaults.vim"`
`    system menu file: "$VIMRUNTIME/menu.vim"`
`  fall-back for $VIM: "/usr/share/vim"`
`Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0`
`-I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0`
`-I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/`
`-I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0`
`-I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2` 
`-I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0` 
`-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2` 
`-fdebug-prefix-map=/build/vim-R2d1UQ/vim-8.0.0197=. -fstack-protector-strong -Wformat`
`-Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1`
`Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.24/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm`

Python installed versions:
`karol@machine:~/Branches$ python --version`
`Python 2.7.13`
`karol@machine:~/Branches$ python3.5 --version`
`Python 3.5.3`
`karol@machine:~/Branches$`

Debian release:
`9.3`

**Comment by diraol** [comment]
Hi @xsqr , please, refer to https://github.com/python-mode/python-mode#how-to-install (take a special look at the need of running git submodule commands).

Despite pylama being installed on your python, I think that python-mode tries to address the pylama version within the plugin submodules directory.

**Comment by xsqr** [comment]
Hi @diraol 
I've tried with downloading all dependencies as submodules and I've got the same error ;(

**Comment by fmv1992** [comment]
@xsqr,

Just a guess here but I'm not sure if how an actually installed `pylama` would behave.

To give you a hint of what could be the problem: we have symlinks that connects file from `pylama` to our project. So I would say that this is the issue.

Just to be on the safe side remove the plugin entirely and then clone with the `recursive` flag to ensure all submodules were cloned too (not elegant but this is my best guess).

**Comment by arkwaif** [comment]
Same problem here, tried everything I could find on the internet, including cloning with the recursive flag / deleting .pyc files / updating both vim and python, etc. 

`Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~\test.py" [unix] 31L, 658C
Error detected while processing C:\Users\John\.vim\bundle\python-mode\autoload\pymode\lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing C:\Users\John\.vim\bundle\python-mode\autoload\pymode\lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing C:\Users\John\.vim\bundle\python-mode\autoload\pymode\lint.vim:
line    1:
  File "C:\Users\John\.vim\bundle\python-mode\pymode\lint.py", line 9, in <module>
Error detected while processing C:\Users\John\.vim\bundle\python-mode\autoload\pymode\lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing C:\Users\John\.vim\bundle\python-mode\autoload\pymode\lint.vim:
line    1:
ModuleNotFoundError: No module named 'pylama'
E149: Sorry, no help for pymode-fq`

Vim Version
![image](https://user-images.githubusercontent.com/10572839/36070257-3803e4b4-0f32-11e8-9a6b-ecfcbd293e23.png)

And finally I am using Python 2.7.14 and 3.6.4

Thanks.

**Comment by wangcgfan** [comment]
Same problem too.
![2018-02-11_13-58-59](https://user-images.githubusercontent.com/1514920/36070374-d10cf7d0-0f33-11e8-9ccf-45b11f937add.png)
![2018-02-11_13-59-24](https://user-images.githubusercontent.com/1514920/36070375-d5108f54-0f33-11e8-87e3-869fdb6efd98.png)

**Comment by fmv1992** [comment]
fixed by https://github.com/python-mode/python-mode/pull/852
