### ISSUE TITLE
Folding no-longer works for multiline method docstrings

### ISSUE THREAD

**Issue by matt2000** [python-mode/python-mode#853]
Folding of the docstring no longer works as of commit 5b6e92d, for code such as this: 

```
class Peasant:
    def hello():
        pass

    def is_witch(self, duck):
        """ Check for witchcraft.

        If she weighs the same as a duck, then she's a witch. Also maybe if she's
        made of wood.
        """
        return self.weight == duck.weight

```

**Comment by fmv1992** [comment]
Hey @matt2000,

Thanks for your update on this bug. I know this is a bit of a hassle but can you please submit the output of your bug report as suggested in our [troubleshooting session](https://github.com/python-mode/python-mode#troubleshootingdebugging)?

I have just tested it and it works as expected.

Just a though but this `[space]` should not exist here: `"""[space]Check` (it does not influence the folding though).
