### ISSUE TITLE
Suggestion: make python 3 default

### ISSUE THREAD

**Issue by trevordmiller** [python-mode/python-mode#855]
Now that Python 3 has been out for years, why not make `let g:pymode_python = 'python3'` default?

**Comment by diraol** [comment]
I think this is a good idea. @fmv1992 any thoughts about it?

**Comment by trevordmiller** [comment]
I've moved to https://github.com/sheerun/vim-polyglot. Closing.

**Comment by fmv1992** [comment]
Done: a92bfa4.
