### ISSUE TITLE
Syntax highlighting only

### ISSUE THREAD

**Issue by trevordmiller** [python-mode/python-mode#856]
Is there a way to only use this plugin for the improved Python syntax highlighting? I already use other plugins for formatting / linting etc.

**Comment by deathmaz** [comment]
i think you can just disable other features, like:
`let g:pymode_lint = 0`
`let g:pymode_folding = 0`
...

**Comment by fmv1992** [comment]
@trevordmiller,

Do you mind telling us which linters/other plugins do you use?

: )

Thanks!

**Comment by trevordmiller** [comment]
@fmv1992 Sure!

- Linting + formatting: `ale`
- Syntax: `vim-polyglot`
- Snippets: `ultisnips`

Here is my `.vimrc`:
https://github.com/trevordmiller/dotfiles/blob/master/files/.vimrc

**Comment by trevordmiller** [comment]
I decided to use `sheerun/vim-polyglot` instead as it has only `syntax and indentation support (other features skipped)` which is what I was looking for.
