### ISSUE TITLE
Pymode silently swallows linting errors

### ISSUE THREAD

**Issue by sruggier** [python-mode/python-mode#859]
Hi, before I report anything, I'd like to thank anyone reading this for helping with `python-mode`, it's very helpful.

My `.vimrc` file has historically contained this:

    " Don't complain about missing docstrings, but if one exists, validate it.
    let g:pymode_lint_ignore = "D100,D101,D102,D103"

I updated python-mode, and the linting stopped working. A quick bisect led me to commit 76c582b9df2c3895cc34ef7b238ff0ddfabeea1e, which immediately explained to me what I needed to fix in my vimrc. While searching for duplicates, I also noticed that if I add `let g:pymode_debug = 1`, I can see the ValueError and a traceback for about a second every time linting is run, which is just about enough time to take a screenshot and run tesseract on it:

    [Pymode] Code checking is running ...
    1519330549 ['pyflakes', 'pepB', 'mccabe', 'pep257'] []
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "path/to/python-mode/pymode/lint.py", line 38, in code_check
        raise ValueError ('g:pymode_lint_ignore should have a list type')
    ValueError: g:pymode_lint_ignore should have a list type

 However, a user shouldn't have to know about either of these things to find out that a variable has been set incorrectly. The current behaviour of silently breaking with no useful information is relatively unhelpful. Instead of telling the user that the code has no errors, the lint execution should propagate the exception to the user so they can troubleshoot effectively.

**Comment by diraol** [comment]
Hi @sruggier , thanks for your contribution here =)

I am still understanding how python-mode works, but I am not sure about is the best approach for python-mode. If it propagates all exceptions without the debug flag, it may make vim unusable for users with "bad configs". The same may go for all plugins. Imagine if all plugins throw away every error and exception....
Moreover, this is why the debug mode exists.
May be the debug mode showing the error for a quick time window can be improved, but we have the troubleshooting session on our readme to help users debug such kind of error without the need to take a screenshot and use tesseract....
