### ISSUE TITLE
Erroneous folding

### ISSUE THREAD

**Issue by kierun** [python-mode/python-mode#861]
Using neovim, I have lots of problem with folding. See the simple example below:

![untitled](https://user-images.githubusercontent.com/3079575/36964166-af68854c-204d-11e8-83e4-dbfb9be5df36.png)

![untitled1](https://user-images.githubusercontent.com/3079575/36964167-af88949a-204d-11e8-9f10-03e8d3d8e07d.png)

I *think* that the problem rests with empty lines in the docstring and/or if the last line of the function has a function call -- ending in "()".

**Comment by diraol** [comment]
Thanks for the report @kierun . Indeed we are facing several problems with current folding implementation (if you take a look at the current open issues, most of them are related to it).

We need to either rewrite the folding or integrate an external folding 'tool'.

Contributions are more than welcome if you can give it a try!
