### ISSUE TITLE
Issues running python-mode with VIM on cygwin

### ISSUE THREAD

**Issue by kkparmar** [python-mode/python-mode#876]
Hi,

I am trying to configure python-mode in VIM on cygwin and it gives error:
"ImportError: No module named pylama.lint.extensions"

Full message stack:
:messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing /home/kkparmar/.vim/pack/my-plugins/start/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/kkparmar/.vim/pack/my-plugins/start/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/kkparmar/.vim/pack/my-plugins/start/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/kkparmar/.vim/pack/my-plugins/start/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/kkparmar/.vim/pack/my-plugins/start/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/kkparmar/.vim/pack/my-plugins/start/python-mode/autoload/pymode/lint.vim:
line    1:
**ImportError: No module named pylama.lint.extensions**

VIM version:
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 12 2018 11:42:41)
Included patches: 1-1696
Compiled by kkparmar
Huge version without GUI.  Features included (+) or not (-):
+acl               +cryptv            -footer            +mksession         +path_extra        +syntax            +viminfo
+arabic            +cscope            +fork()            +modify_fname      +perl              +tag_binary        +vreplace
+autocmd           +cursorbind        -gettext           +mouse             +persistent_undo   +tag_old_static    +wildignore
-autoservername    +cursorshape       -hangul_input      -mouseshape        +postscript        -tag_any_white     +wildmenu
-balloon_eval      +dialog_con        -iconv             +mouse_dec         +printer           -tcl               +windows
+balloon_eval_term +diff              +insert_expand     -mouse_gpm         +profile           +termguicolors     +writebackup
-browse            +digraphs          +job               -mouse_jsbterm     +python            +terminal          -X11
++builtin_terms    -dnd               +jumplist          +mouse_netterm     -python3           +terminfo          -xfontset
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      -xim
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       -xpm
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +timers            -xsmp
-clientserver      +ex_extra          +libcall           +mouse_xterm       +ruby              +title             -xterm_clipboard
+clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        -toolbar           -xterm_save
+cmdline_compl     +farsi             +lispindent        +multi_lang        +signs             +user_commands
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +vertsplit
+cmdline_info      +find_in_path      +localmap          -netbeans_intg     +startuptime       +virtualedit
+comments          +float             -lua               +num64             +statusline        +visual
+conceal           +folding           +menu              +packages          -sun_workshop      +visualextra
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -fstack-protector  -L/usr/local/lib -Wl,--as-needed -o vim.exe        -lm -lncurses   -lacl   -Wl,--enable-auto-import -Wl,-
-export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/5.26/x86_64-cygwin-threads/CORE -lperl -lpthread -l
dl -lcrypt -L/usr/lib/python2.7/config -lpython2.7 -ldl   -lruby230 -lpthread -lgmp -ldl -lcrypt

python version:
$ python --version
Python 2.7.14

Steps tried so far:
Deleted all .pyc files
Tried with VIM package of cygwin
Tried with compiling VIM from source

Could you please suggest what could I be missing?

**Comment by diraol** [comment]
@kkparmar , please, take a look at our [README](https://github.com/python-mode/python-mode/blob/develop/readme.md),
specially [the install section](https://github.com/python-mode/python-mode#how-to-install).

**Comment by diraol** [comment]
@kkparmar Sorry for the late response.

I think we are missing some stuff on that doc page.
Try running `git submodule update --init --recursive` while inside the `python-mode` directory before doing the `cp -R * ~/.vim`, please! ;)
