### ISSUE TITLE
Running doctests

### ISSUE THREAD

**Issue by christophe-riolo** [python-mode/python-mode#880]
Hi,

I am starting with Pyton-mode and it is really awsome, thank you for it.
I just had this idea though that it would be interesting to have doctests integrated a bit in the same way as linting. So when we would run a command like `:PymodeDoctest` or on saving, `doctest` would be run and the possible errors shown in quickfix and in the editor windows.
I don't know the feasability, it's a back-of-the-head idea. Does that sound in scope with this plugin ?

Cheers,
Christophe

**Comment by fmv1992** [comment]
Hey @christophe-riolo,

That's a good idea.

Unfortunately this indeed awesome plugin lacks the manpower to expand its features right now.

If you want to contribute you're welcome! That would have to at least:

* Add one more on/off variable eg `g:pymode_doctest_on_save`.

* Update the documentation for it.

* Implement it according to other commands... I would start taking a look at those to see where/how they are implemented and then replicate the necessary for this `PymodeDocTest`

**Comment by christophe-riolo** [comment]
Thanks for your answers, glad you like the idea :)
I know nothing about writing vim plugins for now, but it sounds like an interesting projet so I'll try !

**Comment by fmv1992** [comment]
Slick is the path of those who engage in writing vim plugins. Your help would be much appreciated.
