### ISSUE TITLE
Question startup debug mode

### ISSUE THREAD

**Issue by StephaneKazmierczak** [python-mode/python-mode#885]
Hi I am new to python-mode, I am just trying to disable the default pymode debug print message msg1, msg2, msg3 ... 6, I would like to start straight up into my file. 
I am not sure if it is the right option but I already tried using let g:pymode_debug = 0 without success

**Comment by StephaneKazmierczak** [comment]
my bad I had another pymode_debug set to 1 one elsewhere in my scripts, indeed it works as expected!

**Comment by fmv1992** [comment]
@StephaneKazmierczak,

It happens. Beware that vim often caches functions and options for your files, so even when you change your `vimrc` for instance the changes may not immediately reflect upon your file.

I like to use the function below to clean this "permanent options" for my files:

    function! s:CleanViewFile()
        function! DeleteFromViewdir()
            " # Function to permanently delete views created by 'mkview'
            " https://stackoverflow.com/questions/28384159/vim-how-to-remove-clear-views-created-by-mkview-from-inside-of-vim
            let path = fnamemodify(bufname('%'),':p')
            " vim's odd =~ escaping for /
            let path = substitute(path, '=', '==', 'g')
            if empty($HOME)
            else
                let path = substitute(path, '^'.$HOME, '\~', '')
            endif
            let path = substitute(path, '/', '=+', 'g') . '='
            " view directory
            let path = &viewdir.'/'.path
            call delete(path)
            echom "Deleted: ".path
        endfunction
        function! DeleteFromUndodir()
            " # Function to permanently delete views created by 'mkview'
            " https://stackoverflow.com/questions/28384159/vim-how-to-remove-clear-views-created-by-mkview-from-inside-of-vim
            let path = fnamemodify(bufname('%'),':p')
            let path = substitute(path, '/', '%', 'g')
            let path = &undodir.'/'.path
            call delete(path)
            " echom path
            echom "Deleted: ".path
        endfunction
        function! DeleteFromBackupdir()
            " # Function to permanently delete views created by 'mkview'
            " https://stackoverflow.com/questions/28384159/vim-how-to-remove-clear-views-created-by-mkview-from-inside-of-vim
            let path = fnamemodify(bufname('%'),':t')
            let path = &backupdir.'/'.path.'~'
            call delete(path)
            echom "Deleted: ".path
        endfunction
        " Clean the view file and parse the modeline for current buffer.
        " Clean the view file and parse the modeline for current buffer.

        " Saves the file vithout creating the view file.
        " TODO: winsaveview may be a better option.
        let save_cursor = getcurpos()
        silent! noautocmd w!
        " set filetype=&filetype

        " Buffer name without extension.
        let buffer_name=expand("%:t")
        " Create variable to remove view file for this file.
        let shell_command="rm " . shellescape(&viewdir . "/*" . buffer_name . "*")
        " Clean the view file.
        silent! call system(shell_command)

        " Buffer name without extension.
        let full_buffer_name=expand("%:p")
        " Use sed to remove viminfo options from this file.
        " echom s:cachedir
        " TODO: Use sed to remove viminfo options from this file.
        " let shell_command="sed -i /" . full_buffer_name . "/^\s*$/d " . shellescape(s:cachedir . "/viminfo")
        " echom shell_command
        " silent! call system(shell_command)
        "
        " Full path to buffer.
        silent! execute "normal! :edit! " . full_buffer_name . "\r"
        silent! execute ":e!"
        " Improves by  the modeline reading the modeline.
        doautocmd BufEnter
        let &filetype=&filetype
        call setpos('.', save_cursor)
        call DeleteFromViewdir()
        call DeleteFromUndodir()
        call DeleteFromBackupdir()
    endfunction

Then:

    command! CleanViewFile :call s:CleanViewFile()

And finally I use:

    execute 'silent! tabdo CleanViewFile' | noautocmd xa! | noautocmd qa!

To clean whatever vim has cached for the files I'm currently using.
