### ISSUE TITLE
Highlight equal sign

### ISSUE THREAD

**Issue by lobachevzky** [python-mode/python-mode#886]
Let me just begin by saying that this is a phenomenal plugin. I have searched in vain for a full-functioning Python plugin with Rope functionality, thorough documentation, and transparent mapping to command line utilities, that doesn't slow vim down to a crawl. This is it!

Ok. That said, my one quibble is that I cannot get `=` to show up in a different color as promised by the docs. This should illustrate:
<img width="1440" alt="screen shot 2018-04-28 at 9 46 34 am" src="https://user-images.githubusercontent.com/10344742/39397184-1f6a93a8-4ac9-11e8-986b-4823dfe6bdcd.png">

As you can see on the bottom, `g:pymode_syntax_highlight_equal_operator #1`.

Maybe it's an issue with my terminal? I'm running terminal 2.8.2. Thanks for your help.

**Comment by nianfouyi** [comment]
我也遇见了这个问题，请问你解决了吗？

**Comment by jennaliu** [comment]
What color scheme are you using? I am using "solarized" and the equal signs are highlighted without problems.

**Comment by diraol** [comment]
My equal sign is highlighted too.
It may have something to do with your vim, your term or both, not with python-mode.
