### ISSUE TITLE
how to fix indent in linter

### ISSUE THREAD

**Issue by StephaneKazmierczak** [python-mode/python-mode#888]
Hi, I would like to use 2 spaces instead of 4 in my code. (not my idea ...)
In VScode, which is also using pylint, there is just a parameter to make it works (but I would rather use vim) 

I found indent option in here: .vim/plugged/python-mode/after/indent/python.vim
replacing 4 by 2 worked.  

Anyone know how to change the setting of the linter?

**Comment by fmv1992** [comment]
@StephaneKazmierczak,

I don't think you can change the lint behavior. However you can disable it with `g:pymode_lint_ignore`.
