### ISSUE TITLE
:help pymode failure

### ISSUE THREAD

**Issue by brohan** [python-mode/python-mode#891]
In vim when I enter _:help pymode_  I get: Sorry, no help for pymode

 have installed python-mode using a fresh .vimrc file and using vim-plug

My .vimrc is as follows:

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Below is vim-plug loading plugins (see vim-plug github for more info)
call plug#begin('~/.vim/plugged')
Plug 'python-mode/python-mode', { 'branch': 'develop' }

Upon creating the above vimrc file, I ran vim, then ran :PlugInstall python-mode which appeared to run successfully.

**Comment by iamartin** [comment]
You may try to generate heptags for pymode. First find the location of pymode 'doc' dir, e.g. ~/.vim/pymode/doc', then
run ':helptags ~/.vim/pymode/doc'. Good luck.
