### ISSUE TITLE
Can not find msys-python3.6m.dll

### ISSUE THREAD

**Issue by Ucag** [python-mode/python-mode#895]
I met this problem when pymode initialized. After trying a lot of ways, I failed to fix this problem.
The error code is : E370 
And can't load python packages
I've installed python using anaconda. I'm not sure that whether does pymode or vim itself cause this problem.
By the way, I'm using gitbash on windows and the version of vim I use is along with it. Over 8.0.
Looking for help.
Thx.

**Comment by diraol** [comment]
@Ucag , please provide more info according to: **https://github.com/python-mode/python-mode#troubleshootingdebugging**

**Comment by erwinkinn** [comment]
@diraol, can I just resume an activity here, or I have to create a yet another issue?
