### ISSUE TITLE
Running into git submodule issue when updating the plugin via Vundle

### ISSUE THREAD

**Issue by nachogoro** [python-mode/python-mode#901]
I understand this might be an issue with Vundle, but since all the other plugins update just fine and `python-mode` has a warning about precisely this thing in the `README` file I thought it might go here. I get the following error when attempting to update the plugin:

```
[2018-06-08 11:24:11] Plugin python-mode/python-mode
[2018-06-08 11:24:11] $ cd '/home/user/.vim/bundle/python-mode' && git pull && git submodule update --init --recursive
[2018-06-08 11:24:11] > Already up to date.
[2018-06-08 11:24:11] > error: Server does not allow request for unadvertised object 0949a1609dcd59995ae0e30ae2bb644a1aeae744
[2018-06-08 11:24:11] > Fetched in submodule path 'submodules/snowball_py', but it did not contain 0949a1609dcd59995ae0e30ae2bb644a1aeae744. Direct fetching of that commit failed.
```

Manually running `git submodule update --init --recursive` in `~/.vim/bundle/python-mode` returns the same error.

According to the log, it is updated (and I can see the latest commit in the `git log` is from 2018-06-01, so it looks okay, but the error message is bugging me.

Thanks!

**Comment by diraol** [comment]
Hi @nachogoro.
Can you please send me the content of the `~/.vim/bundle/python-mode/.gitmodules` file?

**Comment by nachogoro** [comment]
Definitely, thanks for the quick reply!
```
[submodule "submodules/autopep8"]
	path = submodules/autopep8
	url = https://github.com/hhatto/autopep8
    ignore = dirty
[submodule "submodules/pycodestyle"]
	path = submodules/pycodestyle
	url = https://github.com/PyCQA/pycodestyle
    ignore = dirty
[submodule "submodules/pydocstyle"]
	path = submodules/pydocstyle
	url = https://github.com/PyCQA/pydocstyle
    ignore = dirty
[submodule "submodules/mccabe"]
	path = submodules/mccabe
	url = https://github.com/PyCQA/mccabe
    ignore = dirty
[submodule "submodules/pyflakes"]
	path = submodules/pyflakes
	url = https://github.com/PyCQA/pyflakes
    ignore = dirty
[submodule "submodules/snowball_py"]
	path = submodules/snowball_py
	url = https://github.com/diraol/snowball_py
    ignore = dirty
[submodule "submodules/pylama"]
	path = submodules/pylama
	url = https://github.com/fmv1992/pylama
    ignore = dirty
```

**Comment by diraol** [comment]
Hum.....

And what about the result of:
```
cd ~/.vim/bundle/python-mode/submodules/snowball_py
git config -l
```
?

**Comment by nachogoro** [comment]
```
user.email=nachogoro.dev@gmail.com
user.name=NachoGoro
core.preloadindex=true
core.trustctime=false
includeif.gitdir:~/personal/.path=~/personal/gitconfig
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.worktree=../../../../submodules/snowball_py
remote.origin.url=https://github.com/shibukawa/snowball_py
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```
The repo seems to be checked out at `f7fb6afc03ee6069b79a3eed861019e12d168596`.

**Comment by diraol** [comment]
@nachogoro, can you try removing the snowball submodule and then reinserting it?

My settings for `git config -l` under `snowball_py` dir is:
```
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.worktree=../../../../submodules/snowball_py
remote.origin.url=https://github.com/diraol/snowball_py
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
```

We are pointing to different repos, and `python-mode` `.gitmodule` file points to my fork of snowball_py, which contains some extra fixes. (Also, it points to ` snowball_py` `develop` branch, instead of `master`)

**Comment by nachogoro** [comment]
Awesome! Reinstalling the whole python-mode plugin fixed the issue. Not
sure how the misconfiguration happened, though, but all good now :)

**Comment by diraol** [comment]
Great!

Probably something from when we changed from branch master to develop and also changed the submodule reference (to my fork).

**Comment by tonitch** [comment]
hey, sorry for reoppening this issue but, I got exactly the same problem with the submodule "pylama" and when nothing when I try to reinstall :'( 
![screenshot from 2018-10-03 20-55-47](https://user-images.githubusercontent.com/26271060/46432503-ba31c300-c74e-11e8-8a68-1acb189e569c.png)

**Comment by diraol** [comment]
Hi @tonitch sorry, can you try again? I think I've made a silly mistake.

**Comment by tonitch** [comment]
yep, it work :D I'v another issue but i'll post it asap :+1: 
![screenshot from 2018-10-03 21-54-01](https://user-images.githubusercontent.com/26271060/46435538-db96ad00-c756-11e8-9033-6192481d2fb0.png)

**Comment by kadrach** [comment]
```
 Plugin python-mode/python-mode                                                                                                                          
 $ cd '/home/neckerskorn/.vim/bundle/python-mode' && git pull && git submodule update --init --recursive                                                 
 > Already up to date.                                                                                                                                   
 > error: Server does not allow request for unadvertised object 837ecd3d7a8597ab5f28bc83072de68e16470f1e                                                 
 > Fetched in submodule path 'submodules/pylama', but it did not contain 837ecd3d7a8597ab5f28bc83072de68e16470f1e. Direct fetching of that commit failed.
```

This is due to `.git/config` and `.gitmodules` referring to different remotes (a fork?) for pylama. Fixed by running `git submodule sync`.
