### ISSUE TITLE
Python-mode's linters not working on 4 vim installations

### ISSUE THREAD

**Issue by srhaymes56** [python-mode/python-mode#902]
I cannot get python-mode's linters to work on 4 vim installations.

On 2 PC's running Windows 10, and Python 2.7.14, I upgraded from vim 7.4 to 8.1.   Steps as follows for vim 8.1:

    mkdir C:\Users\Steve\vimfiles\pack\plugins\opt
    cd C:\Users\Steve\vimfiles\pack\plugins\opt
    git clone https://github.com/python-mode/python-mode
    cd pymode
    git submodule update --init --recursive
    :packadd python-mode
    :helptags ~/vimfiles/pack/plugins/opt/python-mode

my _vimrc and .vimrc (see Ubuntu installations below) for several years have this:

    " pymode - Note:  see :help Pymode for defaults already set
    let g:pymode_trim_whitespaces = 1             " trim unused white spaces on save
    let g:pymode_indent = 1                          " PEP8-compatible python indent
    let g:pymode_doc = 1                         " turns on the documentation script
    let g:pymode_lint_on_write = 1    " check code on save if file has been modified
    let g:pymode_quickfix_maxheight = 12
    let g:pymode_lint_signs = 0                " don't show left error symbol column
    let g:pymode_lint_checkers = ['pylint', 'pyflakes', 'pep8', 'mccabe']

In Windows 10, when I test the linters with deliberate coding errors, nothing happens.

On the 2 PC's running Windows 10, I have the Ubuntu subsystem installed which includes Python 2.7.12, Python 3.5.2, and vim 7.4.  I use Vundle to manage my plugins.  Steps as follows for vim 7.4 with Vundle:

    :PluginClean   (to remove old python-mode)
    :PluginInstall    (to install new python-mode)
    :q
    cd .vim/bundle/python-mode
    git submodule update --init --recursive

In Ubuntu, when I test the linters with deliberate coding errors, the 1st error is reported and then the linters quit.

I have used python-mode's linters for several years on several different computers.  Either something is broken in this version of python-mode, or I did something wrong in 4 python-mode installations.  Please help.

**Comment by diraol** [comment]
Can you provide this ?
https://github.com/python-mode/python-mode#troubleshootingdebugging

**Comment by srhaymes56** [comment]
Diego:

On Windows 10, :messages did not give me a location for the debug file.  Here is the error output in vim though.

Steve

Error detected while processing function pymode#init:
line    2:
E319: Sorry, the command is not available in this version: python import sys, vim
line    3:
E319: Sorry, the command is not available in this version: python sys.path.insert(0, vim.eval('a:plugin_root'))
line    4:
E319: Sorry, the command is not available in this version: python sys.path = vim.eval('a:paths') + sys.path
Error detected while processing C:\Users\Steve\vimfiles\pack\plugins\opt\python-mode\autoload\pymode\virtualenv.vim:
line    3:
E319: Sorry, the command is not available in this version: python from pymode.virtualenv import enable_virtualenv
Error detected while processing function pymode#breakpoint#init:
line    9:
E319: Sorry, the command is not available in this version: python << EOF
line   11:
E492: Not an editor command: from imp import find_module
line   13:
E110: Missing ')'
E15: Invalid expression: ('wdb', 'pudb', 'ipdb', 'pdb'):
line   14:
E488: Trailing characters:     try:
line   22:
E580: :endif without :if:     endif
line   23:
E170: Missing :endfor
Error detected while processing C:\Users\Steve\vimfiles\pack\plugins\opt\python-mode\ftplugin\python\pymode.vim:
line  239:
E319: Sorry, the command is not available in this version: python from __future__ import print_function; import os;import tempfile; marker='|'; print(marker, tempfile.gettempdir(), os.sep, 'pymode_debug_file.txt', marker, sep='', end='')

Error detected while processing C:\Users\Steve\vimfiles\pack\plugins\opt\python-mode\autoload\pymode\lint.vim:
line    1:
E319: Sorry, the command is not available in this version: python from pymode.lint import code_check

**Comment by diraol** [comment]
@srhaymes56 It will be hard to help without the debug information.
I am not sure if the problem you are facing is related to python-mode directly or is a broader problem.

Try finding the `pymode_debug_file.txt` after running `vim -i NONE -u <path_to_pymode>/debugvimrc.vim`. It should be located under a temporary directory.

This may help you:
https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/where-is-the-temporary-folder/44a039a5-45ba-48dd-84db-fd700e54fd56

**Comment by srhaymes56** [comment]
Hi Diego,


I just ran

1. $vim -i NONE -u C:\Users\Steve\vimfiles\pack\plugins\opt\python-mode\debugvimrc.vim
2. :packadd python-mode
3. :split findgdb.py
4. edit py file to introduce some obvious syntax errors
5. :w (to trigger linters on write)

The above steps introduce some errors as I submitted to you before.


I cannot find a recent pymode_debug_file.txt log files under: C:\Users\Steve\AppData\Local\Temp.  In the past, I have worked with log files from other programs in that same location.  Maybe vim puts its log files somewhere else.


Steve

**Comment by srhaymes56** [comment]
To All,

With some additional testing, I can clearly say that on 2 computers running Windows 10, when I move the python-mode directory from:

C:\Users\Steve\vimfiles\pack\plugins\opt

to

C:\Users\Steve\vimfiles\pack\plugins\start

the linters work correctly in vim 8.1.

Sooo..., by following the new default for plugins in vim 8.n (instead of using Vundle as I have done in earlier versions of vim), python-mode does not work when it is in opt, after I type

:packadd python-mode.

I like the idea of the opt directory as I do not need to load python-mode if I am not editing a python file.  Since I used Vundle for several years which always loaded python-mode, I can live with python-mode in start and not opt and it will work OK.

I would like to know the underlying cause of this problem though.  Is this a vim 8.n problem, python-mode problem, or both?

Steve

**Comment by FinchPowers** [comment]
Same linters problem here. I have to use 0.8.1 to have them working. Following the debug procedure, I get

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<path to python-mode>/pymode/lint.py", line 46, in code_check
    options.linters_params['pylint']['clear_cache'] = True
KeyError: 'pylint'
```

**Comment by srhaymes56** [comment]
FinchPowers,

Could you provide some more details?  As I noted above, in Windows 10 and vim 8.1, I was able to get python-mode to work OK when I moved it from opt to start.  That is why at this time, I am wondering if this is a vim 8.n problem, python-mode problem, or both?

Thanks,

Steve

**Comment by FinchPowers** [comment]
* Linux.
* Vim 8.1
* python-mode 0.9.2

If I checkout python-mode 0.8.1 then it works. If you have specific questions I'll be glad to provide more details.

**Comment by FinchPowers** [comment]
* Linux.
* Vim 8.1
* python-mode 0.9.2

If I checkout python-mode 0.8.1 then it works. If you have specific questions I'll be glad to provide more details.

**Comment by HaleTom** [comment]
I also have the same problem with the latest `python-mode`.

In `:messages` I see:

```
Error detected while processing function pymode#lint#check[11]..provider#python#Call:                                                                                                                              
line   18:                                                                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                 
  File "<string>", line 1, in <module>                                                                                                                                                                             
  File "/home/ravi/.local/share/vim/bundle/python-mode/pymode/lint.py", line 46, in code_check                                                                                                                     
    options.linters_params['pylint']['clear_cache'] = True                                                                                                                                                         
Error detected while processing function pymode#lint#check[11]..provider#python#Call:                                                                                                                              
line   18:                                                                                                                                                                                                         
KeyError: 'pylint'
```

```
% pylint --version
pylint 2.3.1
astroid 2.2.5
Python 3.7.0 | packaged by conda-forge | (default, Jul 23 2018, 21:39:36)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
```

Please re-open.

**Comment by HaleTom** [comment]
I found and documented my solution in #1030.
