### ISSUE TITLE
How to break string lines in arrays with autolint?

### ISSUE THREAD

**Issue by RidaAyed** [python-mode/python-mode#905]
Hi

How can break lines using auto lint to format from this

```python
headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
        }
```

to that:  

```python
headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 \
        (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
        }
```

While I receive a warning `[Pymode] E501 line too long (130 > 79 characters) [pep8]`, neither `:PymodeLint` nor `:PymodeLintAuto` breaks the line. Otherwise linting works.

**Comment by diraol** [comment]
@RidaAyed For python auto formatting, currently I'm using https://pypi.org/project/black/ .
I don't know exactly how our current auto-linter works.

**Comment by RidaAyed** [comment]
Thanks @diraol Black doesn't solve either https://github.com/ambv/black/issues/342

**Comment by fmv1992** [comment]
Probably no linter will auto break your strings for you. If you have triple quoted strings the string itself could change with such a feature. With other strings there are just too many ways to do it, and none of them are obvious; most would make your string less readable.
