### ISSUE TITLE
Issue trying to import sklearn with python3.6

### ISSUE THREAD

**Issue by nickcorona** [python-mode/python-mode#911]
`/home/nick/.vim/plugged/python-mode/pymode/run.py|40` error| in run_code exec(code, `context) # noqa
`model.py|1 error| in <module> from sklearn import svm
`/usr/lib/python3.6/site-packages/sklearn/__init__.py|133 error| in <module> from . import `__check_build
`/usr/lib/python3.6/site-packages/sklearn/__check_build/__init__.py|46 error| in <module> raise_build_error

**Comment by Siddharth-Vadapalli** [comment]
Try python 3.5 and below. It works
