### ISSUE TITLE
Folding.. again!

### ISSUE THREAD

**Issue by alphaCTzo7G** [python-mode/python-mode#913]
I was gonig through the recent commits about folding. Seems like you guys have
done a great job adding tests and solving issues. 

However, it appears that folding has been recently turned off in  commit
`c64c71f`. I also noticed folding related commits in `f0b58fa`,`8aeb039`,
`0eb8452`, `60c638d`, `5b6e92d`. 

I am still using `python-mode` from the commit `d2dead6` and did have issues
with folding before, but after finding the `FastFold` plugin, those issues
largely went away.  Folding is important and probably better to have by
default.  The advantage of `FastFold` is that it pretty much solves the problem
completely, and we can retain folding-on behavior by default, and more
importantly close a long standing problem in this plugin (evident by the
numerous issues here and on stackoverflow/exchange about folding).

Since the `python-mode` extension already depends on a number of other
plugings and libraries, what problems do you see in adding `FastFold` as a
dependency? That will remove issues with folding completely, and we wont have
to worry too much about it any more.

As it stands now, I can't use the latest `python-mode`, even though it maybe
better in other areas, because `folding` even when enabled doesn't work as well
as it did in the `d2dead6` commit.

The other option is to add this piece of code, which is stated in the help
documentation by default:
https://github.com/Valloric/YouCompleteMe/issues/1395#issuecomment-361446871

	augroup unset_folding_in_insert_mode
		autocmd!
		autocmd InsertEnter *.py setlocal foldmethod=marker
		autocmd InsertLeave *.py setlocal foldmethod=expr
	augroup END

The reason I think FastFold` is better is because, it is a full-fledged plugin
and probably has already solved all the edge cases, so we dont have to worry
about most of that, other than adding that as a dependency.

Won't that improve the user experience significantly? What problems do you see
in adding `FastFold` as a sub-module or the above code by default?

**Comment by fmv1992** [comment]
I see no issues with it whatsoever. This would indeed solve a long standing problem.

If you are going to make a PR out of this please put this plugin as submodule in the appropriate folder and link it in an appropriate way to the rest of the plugin, making as few changes to the current settings as possible.

Also do delete the relevant current files if you do so.

Such contribution is very welcomed by me!

@diraol / others, any thoughts?

**Comment by diraol** [comment]
Hi friends!

I like very much the idea of solving this old-long-standing issue from python-mode! =)

My only concern is that all submodules we have on python-mode are standalone python libraries (not related to vim), while `FastFold` is a `vim plugin`.
I am not completely sure if adding `FastFold` as a submodule make sense, the best ever approach would be to have it as a `vim plugin dependency` (although there is no such feature on vim plugins, as far as I remember).

But if one can achieve this integration (through submodules) I won't feel bad at all. Having Python-mode with "builtin" folding is indeed a huge improvement and I won't be against it!

**Comment by mckea** [comment]
In my previous instance of vim with python-mode I had folding working well with 2f850dc once I made a minor change - in autoload/pymode/folding.vim I changed:
`let has_numbers = &number || &relativenumber`
to
`let has_numbers = &number`

The latest version gives me E490 error or, with fdm=indent, the folding is kind of ugly and uninformative.

Is there some way to get back the previous behavior?

**Comment by alphaCTzo7G** [comment]
Yeah.. I agree..I think the previous version with FastFold is probably better. Sorry.. I have been trying to debug another issue in my free time.. so I haven't been able to pay too much attention to this..
