### ISSUE TITLE
some error message when starting vim, but pymode seems to be working

### ISSUE THREAD

**Issue by shushi2016** [python-mode/python-mode#915]
Got these when starting vim:
<img width="326" alt="screen shot 2018-07-02 at 9 13 09 am" src="https://user-images.githubusercontent.com/19173281/42190018-da1b79fa-7e0f-11e8-99d9-e750bfeeefd4.png">

On AWS EC2 instance with Amazon Linux.

**Comment by diraol** [comment]
Please, provide the following:
https://github.com/python-mode/python-mode#troubleshootingdebugging

**Comment by Devligue** [comment]
I seem to have similar issue. I use `NVIM v0.3.2-152-g1593ee7cf` on Windows 10.

```
Error detected while processing function pymode#init:
line    2:
E121: Undefined variable: import
E15: Invalid expression: import sys, vim
line    3:
E121: Undefined variable: sys
E15: Invalid expression: sys.path.insert(0, vim.eval('a:plugin_root'))
line    4:
E121: Undefined variable: sys
E15: Invalid expression: sys.path = vim.eval('a:paths') + sys.path
Error detected while processing C:\Users\devligue\.vim\bundle\python-mode\autoload\pymode\virtualenv.vim:
line    3:
E121: Undefined variable: from
E15: Invalid expression: from pymode.virtualenv import enable_virtualenv
Error detected while processing function pymode#breakpoint#init:
line    9:
E15: Invalid expression: << EOF
E15: Invalid expression: << EOF
line   11:
E492: Not an editor command: from imp import find_module
line   13:
E110: Missing ')'
E15: Invalid expression: ('wdb', 'pudb', 'ipdb', 'pdb'):
line   14:
E488: Trailing characters:     try:
line   22:
E580: :endif without :if:     endif
line   23:
E170: Missing :endfor
```

The log above is all that was in my `:messages` after I run `nvim.exe -i NONE -u "C:\Users\devligue\.vim\bundle\python-mode\debugvimrc.vim"` as described [here](https://github.com/python-mode/python-mode#troubleshootingdebugging). There was nothing like `pymode debug msg 1: Starting debug on: 2017-11-18 16:44:13 with file /tmp/pymode_debug_file.txt`

This errors happen when after starting nvim I open any .py file. The next .py file I open does not cause this errors. Also syntax highlighting on python looks working, but I have not tested all pymode features if they work.

**Comment by diraol** [comment]
@shushi2016 and @Devligue can you try again with the updated version? I think we have a fix for the issue. =)

**Comment by jueqingsizhe66** [comment]
> I seem to have similar issue. I use `NVIM v0.3.2-152-g1593ee7cf` on Windows 10.
> 
> ```
> Error detected while processing function pymode#init:
> line    2:
> E121: Undefined variable: import
> E15: Invalid expression: import sys, vim
> line    3:
> E121: Undefined variable: sys
> E15: Invalid expression: sys.path.insert(0, vim.eval('a:plugin_root'))
> line    4:
> E121: Undefined variable: sys
> E15: Invalid expression: sys.path = vim.eval('a:paths') + sys.path
> Error detected while processing C:\Users\devligue\.vim\bundle\python-mode\autoload\pymode\virtualenv.vim:
> line    3:
> E121: Undefined variable: from
> E15: Invalid expression: from pymode.virtualenv import enable_virtualenv
> Error detected while processing function pymode#breakpoint#init:
> line    9:
> E15: Invalid expression: << EOF
> E15: Invalid expression: << EOF
> line   11:
> E492: Not an editor command: from imp import find_module
> line   13:
> E110: Missing ')'
> E15: Invalid expression: ('wdb', 'pudb', 'ipdb', 'pdb'):
> line   14:
> E488: Trailing characters:     try:
> line   22:
> E580: :endif without :if:     endif
> line   23:
> E170: Missing :endfor
> ```
> The log above is all that was in my `:messages` after I run `nvim.exe -i NONE -u "C:\Users\devligue\.vim\bundle\python-mode\debugvimrc.vim"` as described [here](https://github.com/python-mode/python-mode#troubleshootingdebugging). There was nothing like `pymode debug msg 1: Starting debug on: 2017-11-18 16:44:13 with file /tmp/pymode_debug_file.txt`
> 
> This errors happen when after starting nvim I open any .py file. The next .py file I open does not cause this errors. Also syntax highlighting on python looks working, but I have not tested all pymode features if they work.

Same error at the windows10, python3.7, gvim8.1

**Comment by jueqingsizhe66** [comment]
pymode debug msg 1: Starting debug on: 2018-11-28 15:21:04 with file c:\users\yzl\appdata\local\temp\pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Windows
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~\.vim_runtime\my_plugins\python-mode\debugvimrc.vim
  2: C:\Program Files (x86)\Vim\vim80\plugin\getscriptPlugin.vim
  3: C:\Program Files (x86)\Vim\vim80\plugin\gzip.vim
  4: C:\Program Files (x86)\Vim\vim80\plugin\logiPat.vim
  5: C:\Program Files (x86)\Vim\vim80\plugin\manpager.vim
  6: C:\Program Files (x86)\Vim\vim80\plugin\matchparen.vim
  7: C:\Program Files (x86)\Vim\vim80\plugin\netrwPlugin.vim
  8: C:\Program Files (x86)\Vim\vim80\plugin\rrhelper.vim
  9: C:\Program Files (x86)\Vim\vim80\plugin\spellfile.vim
 10: C:\Program Files (x86)\Vim\vim80\plugin\tarPlugin.vim
 11: C:\Program Files (x86)\Vim\vim80\plugin\tohtml.vim
 12: C:\Program Files (x86)\Vim\vim80\plugin\vimballPlugin.vim
 13: C:\Program Files (x86)\Vim\vim80\plugin\zipPlugin.vim
 14: ~\.vim_runtime\my_plugins\python-mode\plugin\pymode.vim
 15: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode.vim
 16: C:\Program Files (x86)\Vim\vim80\filetype.vim
 17: C:\Program Files (x86)\Vim\vim80\menu.vim
 18: C:\Program Files (x86)\Vim\vim80\lang\menu_zh_cn.cp936.vim
 19: C:\Program Files (x86)\Vim\vim80\lang\menu_chinese_gb.936.vim
 20: C:\Program Files (x86)\Vim\vim80\autoload\paste.vim
 21: C:\Program Files (x86)\Vim\vim80\ftplugin.vim
 22: C:\Program Files (x86)\Vim\vim80\ftplugin\python.vim
 23: ~\.vim_runtime\my_plugins\python-mode\ftplugin\python\pymode.vim
 24: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode\virtualenv.vim
 25: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode\breakpoint.vim
 26: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode\debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  c:\users\yzl\appdata\local\temp\pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
Processing function pymode#debug#sysinfo get error:
Line 33 :
E684: List out of index: 0
E116: Invalid arguments for function substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
E15: invalid expressions: substitute( filter( split(l:scriptnames_var, '\n'), 'v:val =~ "/python-mode/"')[0], '\(^\s\+[0-9]\+:\s\+\)\([/~].*python-mode\/\)\(.*\)', '\2', '')
Line 40 :
E121: undefined variable: l:pymode_folder
E116: Invalid arguments for function expand(l:pymode_folder). ' rev-parse HEAD ' )
E116: Invalid arguments for function system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
E15: invalid expressions: system('git -C ' . expand(l:pymode_folder). ' rev-parse HEAD ' )
Line 41 :
E121: undefined variable: l:git_head_sha1
E116: Invalid arguments for function split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Invalid arguments for function filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E116: Invalid arguments for function join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
E15: invalid expressions: join(filter(split(l:git_head_sha1, '\zs'), 'v:val =~? "[0-9A-Fa-f]"'), '')
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo

"test.py" [New file]
|c:\users\yzl\appdata\local\temp\pymode_debug_file.txt|
-------------------------------------------------------------------------------
pymode debug msg 7: Starting debug on: 2018-11-28 15:23:55 with file c:\users\yzl\appdata\local\temp\pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 8: Operating system: Windows
-------------------------------------------------------------------------------
pymode debug msg 9: Scriptnames:
  1: ~\.vim_runtime\my_plugins\python-mode\debugvimrc.vim
  2: C:\Program Files (x86)\Vim\vim80\plugin\getscriptPlugin.vim
  3: C:\Program Files (x86)\Vim\vim80\plugin\gzip.vim
  4: C:\Program Files (x86)\Vim\vim80\plugin\logiPat.vim
  5: C:\Program Files (x86)\Vim\vim80\plugin\manpager.vim
  6: C:\Program Files (x86)\Vim\vim80\plugin\matchparen.vim
  7: C:\Program Files (x86)\Vim\vim80\plugin\netrwPlugin.vim
  8: C:\Program Files (x86)\Vim\vim80\plugin\rrhelper.vim
  9: C:\Program Files (x86)\Vim\vim80\plugin\spellfile.vim
 10: C:\Program Files (x86)\Vim\vim80\plugin\tarPlugin.vim
 11: C:\Program Files (x86)\Vim\vim80\plugin\tohtml.vim
 12: C:\Program Files (x86)\Vim\vim80\plugin\vimballPlugin.vim
 13: C:\Program Files (x86)\Vim\vim80\plugin\zipPlugin.vim
 14: ~\.vim_runtime\my_plugins\python-mode\plugin\pymode.vim
 15: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode.vim
 16: C:\Program Files (x86)\Vim\vim80\filetype.vim
 17: C:\Program Files (x86)\Vim\vim80\menu.vim
 18: C:\Program Files (x86)\Vim\vim80\lang\menu_zh_cn.cp936.vim
 19: C:\Program Files (x86)\Vim\vim80\lang\menu_chinese_gb.936.vim
 20: C:\Program Files (x86)\Vim\vim80\autoload\paste.vim
 21: C:\Program Files (x86)\Vim\vim80\ftplugin.vim
 22: C:\Program Files (x86)\Vim\vim80\ftplugin\python.vim
 23: ~\.vim_runtime\my_plugins\python-mode\ftplugin\python\pymode.vim
 24: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode\virtualenv.vim
 25: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode\breakpoint.vim
 26: ~\.vim_runtime\my_plugins\python-mode\autoload\pymode\debug.vim

**Comment by diraol** [comment]
I think this issue is related to #972, where I'm centralizing the discussions about it.
If this issue is not related to #972, please, reopen it.
