### ISSUE TITLE
Find ocurrences not working

### ISSUE THREAD

**Issue by Sunno** [python-mode/python-mode#921]
Hi, when I'm using <C-c>f it throws this error, not sure if it could be misconfiguration or something in my system

```
Error detected while processing function pymode#rope#find_it:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alvaro/.vim/bundle/python-mode/pymode/rope.py", line 187, in find_it
    env.run('g:PymodeLocList.current().extend', lst)
  File "/home/alvaro/.vim/bundle/python-mode/pymode/environment.py", line 186, in run
    self.prepare_value(a) for a in args
vim.error: Vim(let):E716: Key not present in Dictionary: type
```

I was using an old version but it stopped working with recent versions, I even uninstalled and installed the plugin again.

Any ideas?

**Comment by boatx** [comment]
Hi
I've created pull request to fix this #914

**Comment by boatx** [comment]
Hi

I think it could be solved by  my pull request: #914

**Comment by diraol** [comment]
Hi friends, I haven't had much time to dedicate to the project, so sorry for not reviewing the PR and other issues.

@Sunno can you test @boatx PR (#914) in order to see if his suggestion fixes your problem?

**Comment by Sunno** [comment]
@boatx @diraol it works! not sure if type should be an empty string but it does the work

**Comment by diraol** [comment]
I've tried to find out what should be the content of the `type` variable, but I couldn't.

It may be an important attribute actually (or not... LOL).

Any suggestion @fmv1992 ?

**Comment by boatx** [comment]
This error is related to ``PymodeLocList``. It is used to display places in code where rope has found occurences.
https://github.com/python-mode/python-mode/blob/bb746d0d0cba9adedbac856429e37a0dbfc599c6/autoload/pymode/rope.vim#L60
But it is also (or mostly used) by linters to display line of code with error of warnings (type 'E' or 'W'), when list of locations is extended new entries are filtered over type.
https://github.com/python-mode/python-mode/blob/bb746d0d0cba9adedbac856429e37a0dbfc599c6/autoload/pymode/tools/loclist.vim#L54
This type is later displayed next to line number. I wasn't sure what to put for rope so I've added empty string.

**Comment by diraol** [comment]
@boatx thanks for the explanation! =)

I'll edit your Pull Request in order to add this very important explanation over there, so we can keep it on the git history/log for future reference.
