### ISSUE TITLE
using python-mode with python 3.7 outputs DeprecationWarning about imp at startup

### ISSUE THREAD

**Issue by mattnworb** [python-mode/python-mode#923]
Python 3.7 has added a DeprecationWarning when the `imp` module is imported:

```
$ python3 -V
Python 3.7.0

$ python3
Python 3.7.0 (default, Jul 19 2018, 10:25:42)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
__main__:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

**Comment by mattnworb** [comment]
I see #916 already exists for this, but wanted to create a new issue with a more accurate title / summary.

**Comment by yzlnew** [comment]
https://github.com/vim/vim/issues/3117 should fix this problem.
But still having this WARNING from Pymode.

**Comment by Stark-X** [comment]
I've installed the latest vim and macvim using the homebrew, the patch should be included, but seems the patch is not work for pymode.

Version info:
```
mvim --version | head
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 15 2018 18:27:33)
macOS version
Included patches: 1-280
Compiled by Homebrew
```

```
vim --version | head
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 20 2018 15:49:13)
macOS version
Included patches: 1-250
Compiled by Homebrew
```

**Comment by diraol** [comment]
Hi all, please take a look at #919
Any help is welcome!

**Comment by diraol** [comment]
By the way, I will close this issue in favor of #916, but I'll rename that issue to a more meaningful name.
