### ISSUE TITLE
run code issue - python-mode

### ISSUE THREAD

**Issue by russellb23** [python-mode/python-mode#928]
Folks,

I am migrating to vim and python-mode. I find it very convenient and elegant for full fledged development until recently, when I did bump on to a very weired issue.

When I try to run a script importing `matplotlib` I was prompted with an error message saying,

> /home/russellb/russell/Python/Audio/playAudio/lib/python3.5/site-packages/matplotlib/__init__.py|195 error| in <module> "Matplotlib requires six>=1.10; you have %s" % six.__version__) ImportError: Matplotlib requires six>=1.    10; you have 1.9.0

However, upon checking the virtual environment, I found the six version is `1.11.0`. Even for the system wide installation says it is `1.11.0`. I have no `six-1.9` installed in my system. 

Executing the same script using `atom` or `PyCharm` I am not getting any error. This makes me conclude that it is most probably an issue with how pymode executes the script under buffer. Could someone show some light or way to troubleshoot/fix this issue?

My script:
`import numpy as np `
`import math`
`from matplotlib import pyplot as plt`
`ss = np.arange(100)`
`x_ = math.sin(ss) + math.cos(ss)`
`plt.figure()`
`plt.plot(ss, x_)`
`plt.show()`

**Comment by russellb23** [comment]
The issue has gone after a plain and clean reinstall of pymode without any code completion `Plug`s.

**Comment by russellb23** [comment]
Oh my bad.... This seems to be a bug. The issue has reappeared this morning when I restarted my machine. I am reopening it...

**Comment by russellb23** [comment]
The issue looks like the way python-mode `run` inherits the virtual environment. I have managed to execute the same script without python-mode with the following mapping
`noremap <F12> :w \| !clear && echo "% is running..." && python3 %<CR>`

However, after enabling python-mode, I am prompted with
`ImportError: No module named 'extnsn' `

If this is not a bug, could someone shed some light as to why is this happening to me?

**Comment by diraol** [comment]
@russellb23 can you please try to do it with the branch `six_as_submodule` that is on my fork of python-mode project?
