### ISSUE TITLE
how to proceed to clean the hardcoded `logilab-common` files from this project?

### ISSUE THREAD

**Issue by fmv1992** [python-mode/python-mode#932]
I see that `./pymode/libs/logilab-common-1.4.1` is still a "hard-coded" file in our project.

I think it should be moved out to `./submodules` as other third party projects. This helps to clean this project so our contributors can focus on actual issues. The complication is that `logilab-common` is not a git maintained project:

1. https://pypi.org/project/logilab-common/
1. https://www.logilab.org/project/logilab-common

Thus a different installation approach may be needed.

I thought about creating a `./makefile` for some common operations in this project (including bug reporting: e.g.: cleaning `.pyc` files):

1. **Pro**: easy, clean, well understood and would help integrate non git projects into the installation procedure. `python` is our friend here: just download the `.tar.gz` from a fixed location and extract it into `./submodules`.

1. **Con**: Windows would be one step further away from being supported again in the future (because installation would depend on the `./makefile`.

What do you think?

**Comment by diraol** [comment]
@fmv1992 what about doing:
  - `pip install -U logilab-common -t submodules/logilab-common`; or
  - `pip install -U logilab-common -t vendor/logilab-common`; or
  - `pip install -U logilab-common -t external/logilab-common`.

 We can still version it on our repo, but as it is installed by pip, not the "copied source code" itself. Then it would be easier to "update it". And by versioning it we won't have to handle the installation problem.

Although I don't think that creating a Makefile is that bad.

Would you have some time to create this makefile? (I personally don't think I can handle it right now)

Can we do an intermediate step using "pip install .." for now and then moving to the makefile if you don't have time now?

**Comment by fmv1992** [comment]
@diraol,

Thanks for all the contributions you have made for this repo.

I like your idea; lets install it with `pip install` without admin rights (I'll find the right flags for this). Just to be sure if I got it right: in this scenario no `logilab` files would be versioned within our repo (question 01).

I think this `logilab` thing would be the only exception to our "single-clone-get-everything-working" procedure. I'm not sure if this single exception is enough to call for a `makefile`. On the other hand having a `makefile` would make it easier for us to automate some things, such as `make update` (that would be a `git pull` and the `logilab` update), tests, etc. Can you think of a more simple/elegant/convenient solution or shall we go with make? (question 02)

I'll start working on this tomorrow; I'll have it commited by Sunday.

**Comment by diraol** [comment]
Hi @fmv1992 ! =)

It is a pleasure to contribute to the project!

Regarding the issue itself, my first idea for a faster solution approach is to version the files, not requiring our users to have to run extra non-git commands to install the project.

But I do agree with you that a Makefile would make our life much much easier.

If we go with a Makefile approach, I think we may even stop using "versioned submodules" to go with a more "on-the-fly" installation.
I mean we can clone the repos we want and get the latest tag/version/master while installing the project (`make install` or something like that). Then we won't necessarily need to update our repo to get the latest version of our dependencies. We will just need to do a `pip install` for each one of them.

Seems a really nice idea!

I think I can give you a help with this issue today. =)

Then we can add much more commands to the makefile (update, test, etc).

**Comment by diraol** [comment]
Keeping this issue active because I think it is still relevant.

**Comment by diraol** [comment]
Ping .... one day I'll be back to this...

**Comment by diraol** [comment]
Resolved here: https://github.com/python-mode/python-mode/pull/1054
