### ISSUE TITLE
Replace pylama with prospector

### ISSUE THREAD

**Issue by diraol** [python-mode/python-mode#934]
https://github.com/PyCQA/prospector

**Comment by fmv1992** [comment]
Sounds very promising.

It also integrates most of the tools we use so probably we could get rid of the `submodules` (at least part of them) as well.

**Comment by fmv1992** [comment]
To wrap-it up:

If we go with `prospector`:

1.  This issue: <https://github.com/python-mode/python-mode/issues/932> gets deprecated.

    On the other hand we would probably have to go with `sudo pip3 install ...` to make it work and decrease the maintenance effort. I'm very inclined by this idea as updating the `submodules` everytime is not very elegant, and the plethora of submodules makes the cloning of this repo very lengthy. And once we lose the magic of a single `git clone --recurisve` command I think we should go with a `makefile` so that then a single `sudo make install` does everything.

1.  A lot of the `submodules` get deprecated.

    * `astroid`: absorbed by `prospector`.
    * `autopep8`: not covered by `prospector`. Will be kept.
    * `mccabe`: absorbed by `prospector`.
    * `pycodestyle`: not covered by `prospector`; would probably be abandoned due to high maintenance costs.
    * `pydocstyle`: absorbed by `prospector`.
    * `pyflakes`: absorbed by `prospector`.
    * `pylama`: deprecated by the adoption of `prospector`. Also decreases the burden on the development and maintenance of different modules.
    * `pylint`: absorbed by `prospector`.
    * `rope`: not covered by `prospector`. Will be kept (not sure).
    * `six`: not covered by `prospector`. Will be kept (not sure).
    * `snowball_py`: deprecated by the adoption of `prospector`; afaik it is a support tool for other `submodules`.

    See <http://prospector.readthedocs.io/en/latest/supported_tools.html>.

@diraol, am I missing something?

**Comment by diraol** [comment]
1. I like make install (without sudo)
I am just not sure about #932, since I don't know what are we using that dependency for.

2. Submodules:

    * ~~`astroid`: Agree~~
    * `autopep8`: Agree to keep
    * ~~`mccabe`: Agree~~
    * `pycodestyle`: I think that this [is covered by `prospector](https://github.com/PyCQA/prospector/blob/master/setup.py#L28), but [aliased to pep8](https://github.com/PyCQA/prospector/blob/master/prospector/tools/pep8/__init__.py)
    * ~~`pydocstyle`: Agree~~
    * ~~`pyflakes`: Agree~~
    * `pylama`: Agree \o/
    * ~~`pylint`: Agree~~
    * `rope`: It seems to be a dependency commonly used by our users, it looks like we should keep it.
    * `six`: Not needed if we drop python2 support.
    * `snowball_py`: I have no idea for what we use it....

**Comment by diraol** [comment]
Keeping it up
