### ISSUE TITLE
RFC: Python versions support

### ISSUE THREAD

**Issue by diraol** [python-mode/python-mode#935]
Hi `python-mode` community!

Maintaining multiple compatible python versions has demanded huge efforts for us.

Many python projects already decided to stop supporting python2.7, since its EOL is scheduled to a quite close date. It has been receiving only security updates and bug fixes.

Even python [3.4](https://www.python.org/dev/peps/pep-0429/) and [3.5](https://www.python.org/dev/peps/pep-0478/) versions are receiving mainly security updates and bug fixes, with no expected new features implemented.

So, I would like to propose that we do a "final 2.7" release, supporting python 2.7 to the best that we can, and then shift for supporting only python3.

Even for python 3, since 3.6 is retro-compatible with the previous 3 versions, we may also think about support 3.6+ or 3.5+ (I am not fully sure about which is the best choice here).

So, my proposal is:

Do some final work by updating some of our dependencies with support to python 2.7, create a branch/TAG and a Release for this version.

Work on an updated version of python-mode with support to python 3.X+.
By doing that, we will be able to drop other dependencies, such as `pylama` (which is unmaintained) that can be replaced by `yala` (#841) or `proscpector` (#934).

What do you all think about it?

**Comment by cdleong** [comment]
Seems like a good plan. Thoughts:
* If we switch away from Pylama, will I finally be able to use f-strings on Ubuntu 16.04?
* Is there some way to have python-mode just... use whichever version of python my terminal is currently using, aka will it work with conda environments? If I switch from a conda environment with python 3.6 to python 3.5, can we have the syntax-checkers and such handle the change and check accordingly?

**Comment by diraol** [comment]
@zcodes you've been a great contributor here, I would like to know your thoughts about this topic.

I have updated our submodules locally and it broke my python-mode because some of the dependencies does not support python2 anymore, so we may need to drop its support.

**Comment by diraol** [comment]
@cdleong Regarding your second bullet point, I think you need a vim compiled with python "dynamic" support in order to be able to get such feature, but I'm not sure about it.

Regarding the first one, maybe yes. Anyway, even if we stay with pylama, we need to update some other dependencies (such as astroid and pylint), but they dropped support for python2 in the most recent releases.

**Comment by zcodes** [comment]
@diraol For me, I think the plain seems ok. No matter what's the reason or purpose, working with multiple python versions is hard, and the life is not happy. For now, as the python official team, and many other packages has stoped supporting python2, even old version python3, it will be harder and harder if still supporting them, especially for a projects depends on many others. So, just following the steps may be the best choice.

**Comment by zcodes** [comment]
@diraol I update all submodules to master (or develop) branch locally, and test with python 2.7 and 3.7, for now, there's nothing is wrong.

**Comment by diraol** [comment]
Nice @zcodes I think we can do another release with support for both python versions.
I'll update all submodules here and create a MR so we can have more people testing.

But it worth mentioning that next `pydocstyle` version (3.0.1, currently 3.0.1rc) will not support python 2.7 anymore.

**Comment by diraol** [comment]
Folks, can you all try this Pull Request, please?

https://github.com/python-mode/python-mode/pull/1005

Tks!

**Comment by diraol** [comment]
Updating this issue.

I've bumped a new version for python-mode `0.10.0`, which is intended to be the latest version with support for python2.
From now on, all `0.10.x` versions will receive the minimum patches related to python2, and I intend to focus on developing `0.11.x` with python 3 support (eventually it can work with python2, but I won't look for that).

My first step is trying to update our submodules/dependencies in order to improve support for newer python features (f-strings, async/await, etc). (MR #1005!)

Besides that, I think we can try to improve `python-mode` by removing code that aims to provide support for python2.

**Comment by diraol** [comment]
Hi all.

As I've stated in many issues, I haven't had time to work on python-mode during past months.

But I think I may have some time to dedicate to the project in December.

As python2 EOL is very close, I think that moving on with this issue is the best way to give some future for the project, reducing some complexity, legacy dependency issues and, eventually, enable us to keep it useful for everybody.

So, I'd like to ask if there are other people interested in helping me to remove python2 support and updating the codebase and dependencies (submodules) so we can have many issues possibly fixed.

**Comment by diraol** [comment]
Regarding "what to do", I think we can start looking for on the codebase places where we are checking python version and drop "python2 specific code" (or even python <= 3.5).

Probably the "imp/importlib" module will be the "most relevant" here - that have been causing many troubles. Or eventually the usage of the `six` library too.

After that I would try to update all of our dependencies (submodules) to the latest stable version.

From my side it will be a "trial and error" process, but suggestions are much more than welcome!

Oh, do you think it worth adding a `if python 2 stop right now` block of code in the plugin init?

**Comment by cdleong** [comment]
I'll try to take a look during December as well. I use python-mode on pretty much a daily basis, so it's in my own interest to contribute.

**Comment by avacariu** [comment]
Hi, I'm interested in taking a look at this, too, and can open a PR which removes Python 2 support in the next few days. Does anyone have any work they've already done, or can I just start from the latest commit in `develop`?

**Comment by diraol** [comment]
Hey @avacariu, thanks for you contribution!
I'll try to take a look and review it in the following two weeks.

But if other people can review it and try it would be great too, I think we need more than one reviewer here ;)

**Comment by cdleong** [comment]
> Seems like a good plan. Thoughts:
> 
> * If we switch away from Pylama, will I finally be able to use f-strings on Ubuntu 16.04?
> * Is there some way to have python-mode just... use whichever version of python my terminal is currently using, aka will it work with conda environments? If I switch from a conda environment with python 3.6 to python 3.5, can we have the syntax-checkers and such handle the change and check accordingly?

Dear Future Users: My problem was solved, please see https://github.com/python-mode/python-mode/issues/817#issuecomment-565733484
