### ISSUE TITLE
pymode not working after upgrading from 3.6 to 3.7. 

### ISSUE THREAD

**Issue by yelbmew** [python-mode/python-mode#943]
Does anyone has work around for this ? Pymode works well when running on python 3.6.

Vim version: 8.1
OS: Linux arch 4.18.3

Error message:

"test.py" [dos] 33L, 1067C
Error detected while processing function pymode#breakpoint#init:
line   21:
/must>not&exist/foo:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by little-dude** [comment]
this is probably related to https://github.com/python-mode/python-mode/pull/919

**Comment by diraol** [comment]
Yes it is, I'll close this issue in favor of the oldest one, please, follow that issue for updates.
