### ISSUE TITLE
PyModRun showing 'No output.' on running a unittest

### ISSUE THREAD

**Issue by tankorsmash** [python-mode/python-mode#945]
Similar issue might be https://github.com/python-mode/python-mode/issues/86

```
import unittest

class TestCaseFoo(unittest.TestCase):
    def test_move_to(self):
        self.assertEqual(False, True)

if __name__ == "__main__":
    unittest.main()
```

Hitting `<leader>r` while editing this file shows `'No output.'`. 

I tried to mess around with https://github.com/python-mode/python-mode/blob/develop/pymode/run.py#L65 to set `l:output` to `errors` in case unittest is trying to print to stderr but that didn't seem to work.

I tried also changing https://github.com/python-mode/python-mode/blob/develop/autoload/pymode/run.vim#L60 to use `l:tracebacks` instead of `l:output`, just in case too, but I wasn't able to figure it out.

A simple Python file outputs as expected, but this test case doesn't show any output for a passing or a failing unittest. What am I doing wrong?

**Comment by tankorsmash** [comment]
This may be an issue with unittest though, as the following only prints `"after import"`, even without any tests declared.

```
import unittest
print("after import")

if __name__ == "__main__":
    unittest.main()
    print("after main")
```

**Comment by diraol** [comment]
@tankorsmash any update related to this issue? Are you still facing problems and/or have you found any solution?

**Comment by tankorsmash** [comment]
I haven't made any progress on this

**Comment by diraol** [comment]
But do you think this is an issue with python-mode or unittest?

**Comment by tankorsmash** [comment]
I'll close the issue, and if anything changes I'll make a new issue (or reopen this, if possible). Thanks!
