### ISSUE TITLE
How to change max line limit as save in vim?

### ISSUE THREAD

**Issue by kuchaguangjie** [python-mode/python-mode#952]
I have tried all solutions I could found on Google, but none of them works now.
So, any suggestion how to change the max line limit, when save file in vim, on Linux?

**Comment by diraol** [comment]
Hi @kuchaguangjie what do you mean by "max line limit" and what is the relationship of it with `python-mode`?

**Comment by kuchaguangjie** [comment]
python-mode, limit the max length of a line by default, and I can't find a way to change it. I have already uninstalled it, due to this.

**Comment by diraol** [comment]
@kuchaguangjie like this? https://github.com/python-mode/python-mode/blob/ac97c66a8b65a5811a67e4e6e326f4f6feb037d9/doc/pymode.txt#L120-L122

**Comment by kuchaguangjie** [comment]
Maybe, but downloading the plugin takes so long (due to it's dependency), and as I am not a python programmer, I won't try this. It's better if users could find these options via Google search or document.

**Comment by diraol** [comment]
For the record, my previous comment is a link to the project documentation, that can be found both here in GitHub and directly from vim (as long as the plugin is installed).
