### ISSUE TITLE
Autocomplete not working for some modules

### ISSUE THREAD

**Issue by fjhheras** [python-mode/python-mode#953]
I have installed python-mode via vundle (adding Plugin 'klen/python-mode' to my .vimrc). Variables in my vimrc look like http://bkpathak.github.io/python-and-vim under "Python mode". I am using gvim 8.1.0374-1, from an Arch Linux distro.

Autocomplete works for some modules and not for others. For example, after "import os" writing "os." opens an autocomplete menu. It does not work, for example, for numpy or matplotlib, even though it is installed

The same issue arises when using python within a miniconda environment. I tried adding "let g:pymode_virtualenv_path = "/home/<user>/miniconda3" to vimrc, but still not working. 

Also, not sure about how to troubleshoot, because I see no error message and running ":pymode#troubleshooting#Test" returns:

`E117: Unknown function: pymode#troubleshooting#Test`

**Comment by diraol** [comment]
We have two problems here.

The first one, related to autocomplete, has been better documented at #998 (not yet solved).

The second one, related to "conda" environments, has been documented at #989 and have a solution already (described in the issue, it is not a `python-mode` problem directly, it is more related to conda itself).

So, I'll just close this current issue in favor of the other two issues (one solved and one not yet, but with more descriptive information about the problem).

**Comment by mg979** [comment]
I'm having the same problem. Autocompletion works in some directory, not in others. Jedi is having the same problem

https://github.com/davidhalter/jedi-vim/issues/692#issuecomment-478905644
