### ISSUE TITLE
I can not activate motions 

### ISSUE THREAD

**Issue by alxfed** [python-mode/python-mode#954]
I have Vim 8.1.477 and I installed this python-mode plug-in (natively, in /.vim/pack/bundle/start/ directory with the help of 'recursive' git cloning, as suggested).

Strangely enough, after adding 

    let g:pymode_motion = 1

to .vimrc as it is suggested in the pymode-motion section of the help file all motions besides the `]]` and `[[` do not work as they should according to the script, where they are defined:

https://github.com/python-mode/python-mode/blob/develop/after/ftplugin/python.vim

The `magic` option is on, I checked.

Also, the **rope** completion that seems to be affected by the same script is working fine.

Did anybody have the same problem? These motions are one of the main reasons why I seem to need this plug-in, I edit piles of files... and that's why I use Vim...

**Comment by diraol** [comment]
@alxfed are you still facing this issue? We have made lot's of changes in `python-mode` and I'm trying to review old issues from the repo. Thanks.

**Comment by alxfed** [comment]
I stopped using it and deleted it.
