### ISSUE TITLE
Error detected while processing lint.vim

### ISSUE THREAD

**Issue by lethargi** [python-mode/python-mode#959]
Python-mode throws error messages when I try opening a python file. I am using Ubuntu 16.04 and Vundle to download python-mode. I am attaching my vim version info and error messages with this post.

I tried `git submodule update --init --recursive` in my python-mode folder, but it did not do anything. I even deleted the python-mode that Vundle made and cloned from git using `git clone --recursive https://github.com/python-mode/python-mode.git`. This did not work either. I ran vim with the debugvimrc.vim file in the python-mode folder; it does not include any message about where the log file is saved. I believe this is on account of the error being in line 239 of the pymode.vim file whereas the function for the debugging message is called in line 241.

[vim_version.txt](https://github.com/python-mode/python-mode/files/2572640/vim_version.txt)
[pymode_error_message.txt](https://github.com/python-mode/python-mode/files/2572641/pymode_error_message.txt)

**Comment by gperezcarellan** [comment]
Same problem here, i tried many things but no results.

**Comment by diraol** [comment]
Hi all, I'm trying to see what is going on.
This is the same error as #958, so I'll close this one in favor of the other (that is older) ok?

Any help is welcome!

**Comment by lethargi** [comment]
thanks for your efforts! its fine by me
