### ISSUE TITLE
how to autocomplete when edit python

### ISSUE THREAD

**Issue by MichaelXoXo** [python-mode/python-mode#966]
I have installed python-mode, but when i endit python file, it can't autocomplete, I see the docs, default <C-Space> , but it does not work, need to set ?

**Comment by cdleong** [comment]
Can you include some more information? It is difficult to understand what you have tried, and what is the problem. 

Have you read the help file at https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt?

Have you edited your .vimrc config file?

Edit: Have you added these lines to your config? (Copied from the help file above)

```
    " turn on rope
    let g:pymode_rope = 1

    " turn on completion?
    let g:pymode_rope_completion = 1
```

**Comment by MichaelXoXo** [comment]
Thank you, I try to add the lines to my .vimrc：

```
let g:pymode_rope = 1
let g:pymode_rope_completion = 1
let g:pymode_rope_completion_bind = '<C-Space>'
```

But when I type `pri` and then press `CTRL+Space` in the python file，but it did not appear `print` , need to add something else ?

PS: my vim version is 7.4

**Comment by MichaelXoXo** [comment]
I have solved the proble, if have `set paste` in vimrc file, the pymode autopletion will not work.

reference: 
- https://stackoverflow.com/questions/21628743/cant-get-the-jedi-vim-plugin-to-work/41574760
