### ISSUE TITLE
Utilize python-language-server for autocomplete, formatting, etc.

### ISSUE THREAD

**Issue by khimaros** [python-mode/python-mode#967]
Starting points:

https://langserver.org/
https://github.com/palantir/python-language-server
https://github.com/prabirshrestha/vim-lsp
https://github.com/prabirshrestha/asyncomplete.vim

**Comment by diraol** [comment]
Hi @khimaros would you try to help us implementing it?

**Comment by madhukar93** [comment]
Hi, interested in helping out here.

**Comment by diraol** [comment]
Hi @madhukar93 please, feel free to send us a Pull Request with such proposal!

**Comment by madhukar93** [comment]
@diraol will start work on this soon. I have no experience with viml and plugin dev though, so looking at that right now. What is the vision here? Will the users of python-mode now have a choice between rope vs lsp for these functionalities?
