### ISSUE TITLE
error while opening python file

### ISSUE THREAD

**Issue by Axatchaudhary** [python-mode/python-mode#968]
I installed python-mode using Plug. When I am opening any python file I am getting this error: 
<img width="954" alt="screen shot 2018-12-01 at 6 34 27 pm" src="https://user-images.githubusercontent.com/7285865/49334302-289cd100-f598-11e8-87ac-923198530058.png">

Please help me.

**Comment by diraol** [comment]
@Axatchaudhary there is no much information here for us to help you.

We've merged some updates to the develop branch, try updating your python-mode (and it's submodules) and, if it still not working, please, take a look at:

https://github.com/python-mode/python-mode/blob/develop/readme.md#troubleshootingdebugging
