### ISSUE TITLE
Ephemeral error message

### ISSUE THREAD

**Issue by gcallah** [python-mode/python-mode#969]
When I save a python file after installing python mode, an error message pops up... very briefly!

I would say what the error is, but the problem is precisely that the error message disappears before I even have time to read it, let alone copy it.

What sort of error message is this? If it is a serious error, leave the message up until I hit return or somefin'... if it's trivial, don't keep interrupting my work with it!

As it stands, I'm going to have to decommission python-mode because this is so annoying.

**Comment by gcallah** [comment]
The message says something about 'pymode buff' ... but again, it is gone before I can read it!

**Comment by diraol** [comment]
@gcallah this is a free software project fully maintained by volunteers (currently only me).

If `python-mode` is so bad and so far from your high standards, you are free to replace it with other better alternatives or write your own, instead of being rude with those that are just trying to contribute with the community.

Back to the point, if you want help, you can just ask for it and I or anyone else can try to help you when we can (again, volunteers).

Regarding the message, if you want to see all messages that were created in your vim, you just need to type `:messages` while in `Normal mode` in vim.

**Comment by gcallah** [comment]
My message was critical, but there was nothing rude in it. It is called feedback. Good developers learn from it.

**Comment by diraol** [comment]
@gcallah,

First of all, your initial problem is not with `python-mode`, but with `vim` (on the sense that you don't know how to see vim messages).

Second, you haven't asked any specific question on your initial message. So I can not help you anyway.

Third, yes you were rude by trying "to threaten" "the project" (childishly by the way):

> As it stands, I'm going to have to decommission python-mode because this is so annoying.

Fourth, if the messages are `warnings`, that's what they are, warnings, not errors. And they are handled differently (by vim, not by python-mode).

Fifth, _I have written how you can see the messages, but you still didn't give any useful information to be helped_.

At last but not least, I'm pretty much comfortable with my skills as a developer, and that includes knowing my limitations. Feedbacks are very welcome, and I really like them, no matter if I'm at a volunteer free software project or in my daily work. But threatens, childish behavior, offenses and things like that are not, and IMHO you seem to be the one that does not like feedbacks.

**Comment by gcallah** [comment]
> Third, yes you were rude by trying "to threaten" "the project" (childishly by the way):
> 
> As it stands, I'm going to have to decommission python-mode because this is so annoying.
> 

I was saying I was going to have to take python-mode out of my plugins in .vimrc. How in the world you interpreted that as a threat to your project is beyond me, but as it turns out, you decided I was rude based on a wild misinterpretation of what I wrote.

**Comment by amcgregor** [comment]
I, too, was receiving (a very large number of) short-lived error notifications on save, and occasionally when opening files, often enough that pressing space or another key would just move on to the next error, then the next, then the next, until I'd give up and hit escape to dismiss all of them.  Predominantly about being unable to find/use `rope` (project symbols indexer), or `pylama` (or other external tool), or in relation to the cursed `imp` module (Python 2 vs. 3 issues).  Updating to the latest HEAD via Homebrew and updating my dotfiles submodules (recursively, with force) has corrected this for me.

To pipe in on the earlier confusion, I like to never attribute to malice that which is adequately explained by the low-bandwidth nature of online text.  Tone is hard to convey!  (Case in point the backlash after I wrote an article titled "Promiscuous Django Models"… or filed a ticket entitled "Incredibly abysmal performance". I swear, I use the words I mean to! ;^) I initially read "decommission" not as a threat (or even a verb), but as "I can't keep using this if it's broken" / "move on from".

Edited to add an additional transitory error:

```
[Pymode] Activate virtualenv: /Users/amcgregor/Projects/marrow/.venv
Error detected while processing function pymode#breakpoint#init:
line   20:
/must>not&exist/foo:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Error detected while processing function <SNR>24_activateNode:
line   12:
E171: Missing :endif
```
