### ISSUE TITLE
No module named 'pymode.libs.six'

### ISSUE THREAD

**Issue by lyneca** [python-mode/python-mode#971]
Upon loading a Python file in Vim, I get the following error:
```
Error detected while processing function pymode#breakpoint#init[29]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'pymode.libs.six'
```

I'm using [dein](https://github.com/Shougo/dein.vim) as my plugin manager.

**Comment by lyneca** [comment]
Seems like it could be something to do with my vimrc - the debug one with the `-i NONE` flag works fine.

**Comment by diraol** [comment]
Try cleaning all `pyc` files withing python-mode directory.

**Comment by memoselyk** [comment]
I had a similar problem, I suspect the issue was that I updated the repo (i.e. `git pull`) without updating the submodules.

**Comment by juanflorez** [comment]
git submodule update --init --recursive
