### ISSUE TITLE
Error detected while processing function pymode#init:

### ISSUE THREAD

**Issue by PrzemoF** [python-mode/python-mode#974]
Installed with pathogen on raspbian:

```"src/events.py" 161L, 7099C
Error detected while processing function pymode#init:
line    2:
E319: Sorry, the command is not available in this version: python import sys, vim
line    3:
E319: Sorry, the command is not available in this version: python sys.path.insert(0, vim.eval('a:plugin_root'))
line    4:
E319: Sorry, the command is not available in this version: python sys.path = vim.eval('a:paths') + sys.path
Error detected while processing /home/pi/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
E319: Sorry, the command is not available in this version: python from pymode.virtualenv import enable_virtualenv
Error detected while processing function pymode#breakpoint#init:
line    9:
E319: Sorry, the command is not available in this version: python << EOF
line   11:
E492: Not an editor command: from pymode.libs.six import PY3
line   13:
E121: Undefined variable: PY3:
E15: Invalid expression: PY3:
line   17:
E488: Trailing characters: else:
line   20:
E488: Trailing characters:         try:
line   31:
E170: Missing :endfor
Press ENTER or type command to continue
```

**Comment by diraol** [comment]
@PrzemoF are you sure you have vim with python support enabled?

Would you please follow the https://github.com/python-mode/python-mode#troubleshootingdebugging section and give use the info referenced there?

**Comment by PrzemoF** [comment]
No, I'm not sure that my vim has python support enabled. It's the vim from raspbian. Daft question, but how can I check that? I should be able to do in python3 "import vim"?
 
I'm trying to do it, but even :messages is causing error:

    :messages
    Messages maintainer: Bram Moolenaar <Bram@vim.org>
    "code/src/occ.py" 135L, 5090C
    Error detected while processing function pymode#init:
    line    2:
    E319: Sorry, the command is not available in this version: python3 import sys, vim
    line    3:
    E319: Sorry, the command is not available in this version: python3 sys.path.insert(0,         vim.eval('a:plugin_root'))
    line    4:
    E319: Sorry, the command is not available in this version: python3 sys.path = vim.eval('a:paths') + sys.path
    Error detected while processing /home/pi/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
    line 3:
    E319: Sorry, the command is not available in this version: python3 from pymode.virtualenv import enable_virtualenv
    Error detected while processing function pymode#breakpoint#init:
    line    9:
    E319: Sorry, the command is not available in this version: python3 << EOF
    line   11:
    E492: Not an editor command: from pymode.libs.six import PY3
    line   13:
    E121: Undefined variable: PY3:
    E15: Invalid expression: PY3:
    line   17:
    E488: Trailing characters: else:
    line   20:
    E488: Trailing characters:         try:
    line   31:
    E170: Missing :endfor
    Error detected while processing /home/pi/.vim/bundle/python-mode/autoload/pymode/lint.vim:
    line    1:
    E319: Sorry, the command is not available in this version: python3 from pymode.lint import code_check

**Comment by PrzemoF** [comment]
You can close the issue. My vim is not with python3:

    pi@raspberrypi:~ $ vim --version | grep python
    +cryptv          +linebreak       -python          +viminfo
    +cscope          +lispindent      -python3         +vreplace
