### ISSUE TITLE
Reload python after installing a module through pip

### ISSUE THREAD

**Issue by typoman** [python-mode/python-mode#975]
After installing a package using pip3 I tried to import the package inside Vim but I get an import error. I have to add that the package was installed in a different window of the terminal that Vim was running in. If I restart Vim, the import error goes away. Is there any way to avoid this or it can only be solved by restarting vim?

**Comment by diraol** [comment]
Hi @typoman,

as far as I know there is not a defined way to solve this. You can try to "hack" vim in order to force reloading all python packages, but this is probably going to be much harder than just closing and opening vim.

**Comment by typoman** [comment]
Thank you @diraol, since it doesn't happen often I just restart Vim in this case.
