### ISSUE TITLE
Improve tests with docker

### ISSUE THREAD

**Issue by diraol** [python-mode/python-mode#977]
Hi all!

We have been facing many issues related to vim/python versions.

I've been thinking that we need better way to test those combinations (vim + python) in a more "clean and isolated environment". Manually or not.

I thought about using docker to create such environments.

A possibility is to:

  - start a docker container
  - install the python version we want
  - build vim considering this specific python version
  - run the tests we want to run
  - enable the (python-mode) "developer" to go into the container and see if everything is OK.

I would like to have some feedback from the community regarding this topic and to see if there is anyone to help with it. I would love to do such improvements, but I cannot guarantee that I'll be able to do it in a reasonable time schedule.

**Comment by diraol** [comment]
OK, I have an initial proposal....

**Comment by cdleong** [comment]
I have some CI/Docker experience. Anything in particular you need help with here?

**Comment by jajajasalu2** [comment]
I won't mind helping. What's the status on this?
