### ISSUE TITLE
Dependency symlink failing in windows

### ISSUE THREAD

**Issue by blayz3r** [python-mode/python-mode#978]
I am using windows 10 and Plug 'python-mode/python-mode', { 'branch': 'develop' }.
I get the following error every time I open a python file.

![2019-01-01_13-23-25](https://user-images.githubusercontent.com/12205650/50575306-b7388400-0dca-11e9-8d06-7651a9182b21.png)

The folder looks like this:

![2019-01-01_13-27-22](https://user-images.githubusercontent.com/12205650/50575310-ca4b5400-0dca-11e9-9981-b21656b1b5c0.png)

**Comment by lodagro** [comment]
Observed same issue (on Linux).


Ran a quick bisect to find what caused it
```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[79d0068e85fca4ff2d9d3ff0101282e91661f2f5] Import six from pymode submodule
```

I reverted to
```
0e38320 Merge pull request #965 from sherylynn/develop
(2018-11-29 18:36:59 -0200, 5 weeks ago by Diego Rabatone Oliveira)
````

Or make pymode/libs a package
```
touch pymode/libs/__init__.py
```

**Comment by harryln** [comment]
Hi, encounter the same problem recently after updating by `vim-plug` for Windows 7, Windows 10 and Linux (32 and 64 bit). Also try removing `pyc` or removing everything/installing again. All failed.

**Comment by diraol** [comment]
Good catch @lodagro, I've added `__init__.py` to the `libs` directory.

@harryln and @blayz3r can you pull and try it again, please? =)

**Comment by harryln** [comment]
Hi, after updating, the same problem. Test on Windows 10.

**Comment by tristanbatchler** [comment]
Wow, thanks I pulled the `__init__.py` and now everything's working great!

**Comment by diraol** [comment]
@tristanbatchler which OS are you using?

I think it may have something to do with Windows not being able to handle the symbolic links... =( But that's strange, since this change was made quite a while ago.

@harryln can you try to open the `python-mode/pymode/libs/six.py` file with any text/code editor other than vim to see if this is a "windows specific" issue?

**Comment by harryln** [comment]
@diraol,  contents of `six.py` under Windows is
```
../../submodules/six/six.py
```
By the way, Linux works perfectly.

**Comment by diraol** [comment]
Hum.... any help here is very welcome. I do not have a Windows to test python-mode. We need to figure out how to make this symbolic link work properly (the strange thing is that all other links seems to be working?)

**Comment by lodagro** [comment]
@diraol not sure all other links work, ```six.py``` is probably the first one that fails, and it all ends there.

Neither do i have a windows install.

**Comment by tristanbatchler** [comment]
Sorry, I didn't realise this was a Windows specific issue. I'm running Linux, so that would be why the latest commit fixed the issues on my end.

**Comment by diraol** [comment]
@chazubell, @harryln and @blayz3r can you guys please try one of the solutions from:
https://stackoverflow.com/questions/5917249/git-symlinks-in-windows ?

The three first answers seems to be very helpful! If one of you guys can make it work, let me know, and we will figure out something to do (at least documenting).

Tks!

**Comment by blayz3r** [comment]
> 
> 
> @chazubell, @harryln and @blayz3r can you guys please try one of the solutions from:
> https://stackoverflow.com/questions/5917249/git-symlinks-in-windows ?
> 
> The three first answers seems to be very helpful! If one of you guys can make it work, let me know, and we will figure out something to do (at least documenting).
> 
> Tks!

Hi @diraol I tried the 4th solution(**_only the reinstalling git part_**) in the thread(on windows 10), **enabling developer mode** and **reinstalling git** with the option below:

![2019-01-06_11-57-44](https://user-images.githubusercontent.com/12205650/50739181-a90fac80-11aa-11e9-9d0b-984cda8ab7c2.png)

You will have to unistall and re-install pymode with your plugin manager. 

Before:
![50575310-ca4b5400-0dca-11e9-9981-b21656b1b5c0](https://user-images.githubusercontent.com/12205650/50739197-c47ab780-11aa-11e9-95ae-12f1b126ef54.png)

After:
![2019-01-06_11-58-11](https://user-images.githubusercontent.com/12205650/50739199-cc3a5c00-11aa-11e9-8c1d-13fdec301a03.png)

Pymode now works as it should!! I would like one more person to confirm though.

**Comment by chazubell** [comment]
I will check it out. 

Thanks to all.

-cdu

**Comment by chazubell** [comment]
Followed the link.  Updated git.  Set option per the screens shot.  Updated the clone, etc., etc. Works! 

Thanks to all.

**Comment by diraol** [comment]
Nice to hear! Thanks for reporting the issue and taking time to test the solutions! =)

**Comment by blayz3r** [comment]
> Nice to hear! Thanks for reporting the issue and taking time to test the solutions! =)

No. Thank you for helping resolve the issue so quickly !!!

**Comment by madalinpopa** [comment]
I had the same issue. Windows 10, Vim 8.1. Followed the solution provided by @blayz3r. Works! 👍

**Comment by artkpv** [comment]
Had this also. Thanks. Probably to add this at https://github.com/python-mode/python-mode#how-to-install.

**Comment by g-i-o-r-g-i-o** [comment]
How did you fix this under windows 10?
I get 
error running function pymode#breakpoint#init:

Tracebak...:
file .... submodules/six/six.py
SyntaxError: invalid syntax

**Comment by diraol** [comment]
@GianniGi , please, read the [README](https://github.com/python-mode/python-mode/blob/develop/readme.md) on how to install python-mode (and look for windows related comments over there)
https://github.com/python-mode/python-mode#symlinks-on-windows

**Comment by diraol** [comment]
Since this is an old and solved issue, I'm locking it.
If the content here does not fit anymore, please open an new issue.
