### ISSUE TITLE
Error Detected While Processing Function pymode#breakpoint#init

### ISSUE THREAD

**Issue by chazubell** [python-mode/python-mode#979]
I am running Vim 8.1.687 (python3/dyn enabled) on Windows 10 with Python 3.6.8.

A file was loaded into VIM and the error listed below appeared.  From what I see in the output, the redirection to the file in a different folder is not being performed.  
Question:  Have a missed a setting in my .vimrc file?

Thanks for any suggestions.

Output 
<<<<>>>
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\E461183\vimfiles\bundle\python-mode\pymode\libs\six.py", line 1
    ../../submodules/six/six.py
    ^
SyntaxError: invalid syntax
<<<<>>>>

**Comment by diraol** [comment]
Hi @chazubell this is the same error as the one in #978.

I'll close this issue as a duplicated of the older one, let's keep the talk there. =)
(But no, you have not missed any config in vimrc)

**Comment by chazubell** [comment]
Thanks.
