### ISSUE TITLE
Pymode doesn't run the code E444:

### ISSUE THREAD

**Issue by typoman** [python-mode/python-mode#983]
When I hit tun recently I realized it works for the first time and if I don't close the output window and run the code again it stops working. Here is what I see in the output:
```
[Pymode] Code running ...                                                                                                                                                   
Error detected while processing function pymode#run#code_run[13]..pymode#tempbuffer_open:
line    1:
E444: Cannot close last window
Press ENTER or type command to continue
```
So basically atm can't run any python code inside vim. What do you suggest for diagnosis or fix?

**Comment by diraol** [comment]
@typoman can you provide a more descriptive explanation how can I reproduce the error?
I mean, a sample python file and the sequence of commands.

**Comment by dlbradford** [comment]
I am seeing a very similar issue after installing python-mode today.
"Error detected while processing function pymode#run#code_run[13]..pymode#tempbuffer_open:"
![pymode-error](https://user-images.githubusercontent.com/72617/56855396-6cf88700-6914-11e9-9310-938f36609599.png)

Vim version 8.1.1137
" My Plugins
Plugin 'vim-airline/vim-airline'                                                           
Plugin 'vim-airline/vim-airline-themes'                                         
Plugin 'junegunn/fzf'                                              
Plugin 'python-mode/python-mode'                                                   
Plugin 'kien/ctrlp.vim'                                                        
                                         
I don't know what other information would help you, but please let me know if there is something else I can report.
