### ISSUE TITLE
How to ignore E501 on project level?

### ISSUE THREAD

**Issue by sorsasampo** [python-mode/python-mode#988]
I tried creating `pylama.ini` with:

```
[pylama]
ignore = E501
```

But this does not seem to have an effect?

**Comment by diraol** [comment]
@sorsasampo can you try configuring in `pylint.rc`?

**Comment by sorsasampo** [comment]
@diraol renaming `pylama.ini` to `pylint.rc` made no difference.

**Comment by diraol** [comment]
@sorsasampo can you provide you `.vimrc` file?

**Comment by sorsasampo** [comment]
@diraol no, but I can test with a minimal `~.vimrc` if you provide one, and believe some other plugin is the issue.

**Comment by diraol** [comment]
Sorry @sorsasampo, but I cannot help you if you do not provide information and context.
The best that I can suggest to you is to disable all plugins except python-mode and try our troubleshooting section (from the project Readme).

**Comment by Migacz85** [comment]
Hi a little side not, is that error E501  
Is it autofixable by using :PymodeLintAuto ?

**Comment by diraol** [comment]
@Migacz85 I sincerely don't remember if PymodeLintAuto can fix this type of error (I would just try it) because this can be very tricky to solve.
