### ISSUE TITLE
Vim plugins error 

### ISSUE THREAD

**Issue by iamsourcer** [python-mode/python-mode#994]
I m trying to use vim as my editor and had the following errors.  Not sure how to solve the problem.  Any help / tips will be appreciated.

Cheers

Jon 

![05ea8711-4ed1-45f0-a156-abecab57539d](https://user-images.githubusercontent.com/2893792/53315696-55186e80-38a3-11e9-9012-cc2e0af77e36.png)

**Comment by diraol** [comment]
Hi @jtarrico , you haven't installed python-mode correctly, you are missing the submodules. Please, take a look at our Readme.

**Comment by diraol** [comment]
Later on don't forget to give us a feedback if everything is ok. ;)
