### ISSUE TITLE
Only seeing output on taking input

### ISSUE THREAD

**Issue by archibold9** [python-mode/python-mode#997]
On running with <label>r the run will only take input from my infinite loop and not show any output. I've searched the docs but can't find anything on this.

**Comment by diraol** [comment]
Hi @archibold9 can explain your problems with more details and, if possible, with some straightforward small sample code for us to reproduce the situation?

**Comment by archibold9** [comment]
I'm relatively new to vim and plugins so I'm writing simple python scripts just to get the hang of using them both in parallel.

The important parts of my code is as follows:


```
def get_guess():
    return input("Enter Password: ")

populate_dictionary()
answer = get_random()

while(True):
    guess = get_guess()
    print(guess)

    if guess == 'exit':
        sys.exit(0)
    correct = check_guess(guess, answer)
    print(f"You got {correct}/{len(answer)} correct")
```

On running it with label r it pops up the input section from get_guess() but doesn't print anything out until its terminated.

I have attached screenshots to show this.

<img width="1680" alt="screenshot 2019-02-26 at 11 06 05" src="https://user-images.githubusercontent.com/17754442/53408569-b2e9ab00-39b6-11e9-9021-71b2e1e535af.png">


<img width="1680" alt="screenshot 2019-02-26 at 11 05 56" src="https://user-images.githubusercontent.com/17754442/53408544-a2393500-39b6-11e9-94dc-e51e511617a0.png">

Only after typing my exit input does it show the print statements.

<img width="1680" alt="screenshot 2019-02-26 at 11 06 26" src="https://user-images.githubusercontent.com/17754442/53408693-0cea7080-39b7-11e9-8dba-4b27cf5fe92d.png">

This is probably something i'm doing wrong or not understanding but I couldn't find any other support section for pymode.

Thanks and best wishes

**Comment by diraol** [comment]
Hi @archibold9 sorry, but with this code is not executable (it is missing some methods definitions).

**Comment by archibold9** [comment]
Apologies.

```
import sys
import random
print("Welcome to CRACKER")
words = []

def get_random():
return random.choice(words)

def populate_dictionary():
words.append("TEST")

def check_guess(guess, answer):
counter = 0
if guess == answer:
return len(answer)
else:
for c in guess:
if c in answer:
counter += 1
return counter

def get_guess():
return input("Enter Password: ")

populate_dictionary()
answer = get_random()

while(True):
guess = get_guess()
print(guess)

if guess == 'exit':
    sys.exit(0)
correct = check_guess(guess, answer)
print(f"You got {correct}/{len(answer)} correct")
```
