### ISSUE TITLE
Documentation does not work with import aliases

### ISSUE THREAD

**Issue by tobias-weiss-ai-xr** [python-mode/python-mode#998]
Hello,

First I want to thank all the contributors for the great plug-in.

However, I have a tiny little problem with the documentation lookups via ctrl+k.

If I use
import numpy
numpy.array(...)
everything is fine.

But if I use
import numpy as np
np.array(...)
the documentation is not found.

Am I doing something wrong?

I'm using self-compiled neovim + python3 with the master branch here.

Maybe a hint how I can debug it myself would be enough...

Best,
Tobias

**Comment by diraol** [comment]
Hi @tobiasweede, you are right, it is not working.

I'm not sure how would we fix it neither if this is a "problem" of python-mode or from rope (the plugin that actually offers the autocomplete feature if I am not mistaken).

Any help would be welcome (such as looking for similar issues in Rope repo/issues).

**Comment by smheidrich** [comment]
IMHO this isn't stale (I have the same issue still).

**Comment by smheidrich** [comment]
Nevermind actually: It does work if you have rope enabled (``let g:pymode_rope = 1``). I had it disabled because it tends to make vim quite sluggish...
